### ISSUE TITLE
Thinkabout NMI on by default.

### ISSUE THREAD

**Issue by Gen2ly** [linrunner/TLP#104]
When resuming from hibernation/sleep, I've been getting:

```
Uhhuh. NMI received for unknown reason...
Do you have a strange power saving mode enabled?
Dazed and confused, but trying to continue
```

I've discovered this is from the open-source radeon driver.  Apparently the driver uses NMI to help debug some problems.  I've been having X.org server crashes about one a day.  I usually suspend the laptop to **disk** or to **ram** five... four times a day; and about once a day I was having and X.org server crash.  I enabled the setting and used it five days... now?!... and the resume from sleep issues have disappeared.  I'd have to say with close enough to **100%** certainty _that_ this was the cause of the trouble.  I realize that an [enabled NMI](https://wiki.archlinux.org/index.php/Power_saving#Disabling_NMI_watchdog) can cause decent power draining... however, the extent of thus...

My **thought** is (with preferential knowledge leading to... neither!):
1. Keep disabled and have a listing: like: _NMI may be needed for some drivers for debugging_.
2. Either enable by default and have a likewise suggestion.

**Comment by Kareeeeem** [comment]
I have this same problem when resuming from hibernate. I am on debian sid. What can I do to figure out which driver is the offender?
