### ISSUE TITLE
Return non-zero exit status on error.

### ISSUE THREAD

**Issue by lasso012** [linrunner/TLP#105]
I'd like to create some scripts to automate things. It seems TLP returns 0 on some error conditions:
```
$ sudo tlp setcharge 
Error: setting charge thresholds is possible on ac power only.
$ echo $?
0

$ sudo tlp discharge 
Error: discharge is possible on ac power only.
$ echo $?
0
```

Also, for setcharge, I think it should be okay to set charge thresholds when on battery. The new charge thresholds should apply when the notebook is plugged in.

I'm using TLP 0.6 on Xubuntu 12.04.5 LTS. I'm using the 3.13 kernel based hardware enablement stack.

**Comment by linrunner** [comment]
0.7 released
