### ISSUE TITLE
Power source not detected correctly

### ISSUE THREAD

**Issue by Ecno92** [linrunner/TLP#109]
When I use `sudo tlp-stat ` I see the following in the result:
```
    +++ System Status
    TLP power save = enabled
    power source   = battery
```

I'm using an Intel NUC with ubuntu 14.10 and this device does not have a battery. It seems like TLP is not able to detect the power source correctly on my system .

I didn't remove the laptop-mode-tools in Ubuntu since this is not on the documentation page (but it is in some online tutorials). I expect that this may be the cause, but I'm not sure. 

Can anybody explain me why I'm seeing the wrong power source state in the stat overview?

**Comment by linrunner** [comment]
0.7 released
