### ISSUE TITLE
TLP re enables wifi and applies power saving during shutdown

### ISSUE THREAD

**Issue by CharlesAtum** [linrunner/TLP#113]
During shutdown I see this:
```
Dez 07 20:29:07 mateus-arch tlp[21306]: Enabling radios: wifi.
```
This becomes a problem later because it triggers Network Manager but dbus is not available:
```
Dez 07 20:29:08 mateus-arch NetworkManager[653]: <info> NetworkManager state is now DISCONNECTED
Dez 07 20:29:08 mateus-arch NetworkManager[653]: <warn> (wlp2s0): add_pending_action (2): 'waiting for supplicant' already pending
Dez 07 20:29:08 mateus-arch NetworkManager[653]: file devices/nm-device.c: line 6324 (nm_device_add_pending_action): should not be reached
Dez 07 20:29:08 mateus-arch dbus[517]: [system] Activating via systemd: service name='fi.w1.wpa_supplicant1' unit='wpa_supplicant.service'
Dez 07 20:29:08 mateus-arch dbus[517]: [system] Activation via systemd failed for unit 'wpa_supplicant.service': Refusing activation, D-Bus is shutting down.
Dez 07 20:29:08 mateus-arch dbus[517]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Dez 07 20:29:08 mateus-arch dbus[517]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.nm-dispatcher.service': Refusing activation, D-Bus is shutting down.
Dez 07 20:29:08 mateus-arch NetworkManager[653]: <error> [1417991348.285156] [supplicant-manager/nm-supplicant-interface.c:856] interface_add_cb(): (wlp2s0): error adding interface: Refusing activation, D-Bus is shutting down.
Dez 07 20:29:08 mateus-arch NetworkManager[653]: <info> (wlp2s0): supplicant interface state: starting -> down
Dez 07 20:29:08 mateus-arch dbus[517]: [system] Activating via systemd: service name='fi.w1.wpa_supplicant1' unit='wpa_supplicant.service'
Dez 07 20:29:08 mateus-arch dbus[517]: [system] Activation via systemd failed for unit 'wpa_supplicant.service': Refusing activation, D-Bus is shutting down.
Dez 07 20:29:08 mateus-arch NetworkManager[653]: <warn> (21) failed to call dispatcher scripts: (org.freedesktop.systemd1.ShuttingDown) Refusing activation, D-Bus is shutting down.
Dez 07 20:29:08 mateus-arch NetworkManager[653]: <error> [1417991348.285821] [supplicant-manager/nm-supplicant-interface.c:856] interface_add_cb(): (wlp2s0): error adding interface: Refusing activation, D-Bus is shutting down.
```
The interface_add_cb() error keeps repeating several times in the logs.

Later this also happens:
```
Dez 07 20:29:09 mateus-arch mkinitcpio[21311]: ==> Build complete.
Dez 07 20:29:09 mateus-arch systemd[1]: Started Generate shutdown-ramfs.
Dez 07 20:29:09 mateus-arch tlp[21306]: Applying power save settings...done.
Dez 07 20:29:09 mateus-arch systemd[1]: Stopped TLP system startup/shutdown.
Dez 07 20:29:09 mateus-arch systemd[1]: Stopping Multi-User System.
Dez 07 20:29:09 mateus-arch systemd[1]: Stopped target Multi-User System.
```

**Comment by linrunner** [comment]
I implemented a check if NM is running. This should stop the messages.

You should disable systemd-rfkill when installing TLP as described in the [Wiki](https://wiki.archlinux.org/index.php/TLP#Installation). There can only be one.

**Comment by linrunner** [comment]
Sorry, i had to remove the check for the 0.7 release. There seems to be no simple and reliable way to achieve this during shutdown.

**Comment by danielkza** [comment]
I have a serious suspicion this is causing shutdown issues for me. I have a hung rmmod process sometimes that seems to be related to my Wi-fi device (the a Broadcom BCM4350 chip on a Dell XPS 13). Shouldn't TLP not be attempting to touch the rfkill state at all if the option is disabled in the configuration?

Running TLP 0.8 in Fedora 23.

**Comment by linrunner** [comment]
Hi, 

enabling wifi on shutdown is by design. Just to make sure wifi is enabled within NM for the next boot. 

You may change this behaviour with

    DEVICES_TO_DISABLE_ON_SHUTDOWN="wifi"

With the above configuration you may also need to enable it upon boot with

   DEVICES_TO_ENABLE_ON_STARTUP="wifi"

Have a look the actual code [here](https://github.com/linrunner/TLP/blob/master/tlp-rf-func#L337)

**Comment by danielkza** [comment]
What I would really like is to tell TLP not to touch the Wi-fi state at all, in either boot or shutdown, which is not the same as telling it to always disable it. What exactly was the bug with NetworkManager? Why isn't it better solved by letting systemd and NetworkManager handle rfkill by themselves without involving TLP (as it works perfectly for me)?

**Comment by linrunner** [comment]
May i suggest you open a new issue that specifies your feature request?

**Comment by danielkza** [comment]
Just making always enabling Wi-fi on shutdown optional is enough for me. My issue is that even leaving all the device state options unset still caused TLP to change stuff. I prefer letting systemd handle rfkill if possible, since I really don't need any of the special behaviors that TLP has.

I'll make a PR to that effect in a minute.
