### ISSUE TITLE
TLP Fedora 21 repo

### ISSUE THREAD

**Issue by digititus** [linrunner/TLP#114]
I see there are releases for Fedora 16-20. Are there any plans for Fedora 21 repo?

**Comment by linrunner** [comment]
I asked the TLP repo maintainer to provide acpi-call and tp-smapi packages for F21.

**Comment by linrunner** [comment]
acpi-call and tp-smapi packages for F21 are now in the repo.

**Comment by Speedy-Gonzalez** [comment]
Thanks for adding the package.

I get this error: Package akmod-tp_smapi-0.41-5.fc21.x86_64.rpm is not signed. (also the "tlp-release-1.0.1-4.fc21.noarch.rpm").
Yes I could install the package without gpgcheck, but this wasn't necessary for F20, so I think it would be better if the packages were signed. Thanks

**Comment by linrunner** [comment]
Signed packages have been uploaded. Please test once more.

**Comment by digititus** [comment]
When I run tlp stat I notice I have the following (I have a ThinkPad!):
+++ ThinkPad Extended Battery Functions
tp-smapi   = inactive (kernel module 'tp_smapi' load error)
tpacpi-bat = inactive (kernel module 'acpi_call' not installed)

Fed21. TLP 0.6

**Comment by linrunner** [comment]
@digititus : you didn't reboot after installing tp-smapi and acpi-call packages.

**Comment by digititus** [comment]
> @digititus : you didn't reboot after installing tp-smapi and acpi-call packages.

I did.  Also, running yum install akmod-acpi_call.x86_64 akmod-tp_smapi.x86_64 tells me 'nothing to do' so modules are installed.

**Comment by linrunner** [comment]
When TLP complains, something is definitely wrong. 
1. Which ThinkPad exactly?
2. Show the output of:

    modprobe -v acpi-call

**Comment by digititus** [comment]
1. X1 carbon
2. > modprobe: FATAL: Module acpi-call not found.

Kernel-devel installed

**Comment by Speedy-Gonzalez** [comment]
Same for me:
+++ ThinkPad Extended Battery Functions
tp-smapi = inactive (kernel module 'tp_smapi' load error)
tpacpi-bat = inactive (kernel module 'acpi_call' not installed)

modprobe -v tp_smapi -> modprobe: FATAL: Module tp_smapi not found.

Thinkpad X201

**Comment by Speedy-Gonzalez** [comment]
Ups, kernel-devel was not installed. Thought it was.

Now it's working

**Comment by digititus** [comment]
Seems it relates to this from [Redhat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1178015)

**Comment by linrunner** [comment]
@digititus : please show the following outputs:

    cat /var/cache/akmods/aksmod.log
    cat /var/cache/akmods/acpi_call/.last.log
    uname -a
    ls -l /usr/lib/modules/*/extra/acpi_call/acpi_call.ko
    modinfo /usr/lib/modules/*/extra/acpi_call/acpi_call.ko

**Comment by digititus** [comment]
**cat /var/cache/akmods/aksmod.log**
cat: /var/cache/akmods/aksmod.log: No such file or directory

**cat /var/cache/akmods/acpi_call/.last.log**
2015/01/21 11:02:09 akmods: Building RPM using the command '/bin/akmodsbuild --target x86_64 --kernels 3.18.3-201.fc21.x86_64 /usr/src/akmods/acpi_call-kmod.latest'
warning: user build does not exist - using root
warning: group build does not exist - using root
warning: user build does not exist - using root
warning: group build does not exist - using root
warning: user build does not exist - using root
warning: group build does not exist - using root
error: Bad source: /tmp/akmodsbuild.oQ6Y4OQV/SOURCES/acpi_call-1.1.0.fc21-x86_64.patch: No such file or directory
Installing /usr/src/akmods/acpi_call-kmod.latest
Building target platforms: x86_64
Building for target x86_64
2015/01/21 11:02:09 akmodsbuild: * Rebuilding /usr/src/akmods/acpi_call-kmod.latest for kernel(s) 3.18.3-201.fc21.x86_64: warning: user build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: group build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: user build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: group build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: user build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: group build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: error: Bad source: /tmp/akmodsbuild.oQ6Y4OQV/SOURCES/acpi_call-1.1.0.fc21-x86_64.patch: No such file or directory
2015/01/21 11:02:09 akmodsbuild: Installing /usr/src/akmods/acpi_call-kmod.latest
2015/01/21 11:02:09 akmodsbuild: Building target platforms: x86_64
2015/01/21 11:02:09 akmodsbuild: Building for target x86_64
2015/01/21 11:02:09 akmodsbuild: 
2015/01/21 11:02:09 akmods: Building rpms failed; see /var/cache/akmods/acpi_call/1.1.0-2-for-3.18.3-201.fc21.x86_64.failed.log for details

**uname-a**
Linux x1-local 3.18.3-201.fc21.x86_64 #1 SMP Mon Jan 19 15:59:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**ls -l /usr/lib/modules/*/extra/acpi_call/acpi_call.ko**
ls: cannot access /usr/lib/modules/*/extra/acpi_call/acpi_call.ko: No such file or directory

**modinfo /usr/lib/modules/*/extra/acpi_call/acpi_call.ko**
modinfo: ERROR: Module /usr/lib/modules/*/extra/acpi_call/acpi_call.ko not found.

**Comment by linrunner** [comment]
Please show the detailed log:

     cat /var/cache/akmods/acpi_call/1.1.0-2-for-3.18.3-201.fc21.x86_64.failed.log

I would try to uninstall/reinstall the package *akmod-acpi_call*.

**Comment by digititus** [comment]
akmod-acpi_call removed. However, it isn't possible to reinstall onFC21 as it isn't available in any of the repos. This system was upgraded from FC20, so acpi-call is from that time.

**cat /var/cache/akmods/acpi_call/.last.log**
2015/01/21 11:02:09 akmods: Building RPM using the command '/bin/akmodsbuild --target x86_64 --kernels 3.18.3-201.fc21.x86_64 /usr/src/akmods/acpi_call-kmod.latest'
warning: user build does not exist - using root
warning: group build does not exist - using root
warning: user build does not exist - using root
warning: group build does not exist - using root
warning: user build does not exist - using root
warning: group build does not exist - using root
error: Bad source: /tmp/akmodsbuild.oQ6Y4OQV/SOURCES/acpi_call-1.1.0.fc21-x86_64.patch: No such file or directory
Installing /usr/src/akmods/acpi_call-kmod.latest
Building target platforms: x86_64
Building for target x86_64
2015/01/21 11:02:09 akmodsbuild: * Rebuilding /usr/src/akmods/acpi_call-kmod.latest for kernel(s) 3.18.3-201.fc21.x86_64: warning: user build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: group build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: user build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: group build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: user build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: warning: group build does not exist - using root
2015/01/21 11:02:09 akmodsbuild: error: Bad source: /tmp/akmodsbuild.oQ6Y4OQV/SOURCES/acpi_call-1.1.0.fc21-x86_64.patch: No such file or directory
2015/01/21 11:02:09 akmodsbuild: Installing /usr/src/akmods/acpi_call-kmod.latest
2015/01/21 11:02:09 akmodsbuild: Building target platforms: x86_64
2015/01/21 11:02:09 akmodsbuild: Building for target x86_64
2015/01/21 11:02:09 akmodsbuild: 
2015/01/21 11:02:09 akmods: Building rpms failed; see /var/cache/akmods/acpi_call/1.1.0-2-for-3.18.3-201.fc21.x86_64.failed.log for details

**Comment by linrunner** [comment]
> This system was upgraded from FC20, so acpi-call is from that time.

Ah. You didn't mention this. 8 days ago i wrote

> acpi-call and tp-smapi packages for F21 are now in the repo.

I suggest you review your configured package repos and start all over again. Good luck.
