### ISSUE TITLE
`sudo tlp setcharge ` doesn't work in thinkpad x61

### ISSUE THREAD

**Issue by gansteed** [linrunner/TLP#117]
my system environment is Ubuntu 14.04 x64 with unity as desktop environment , when I type 

```bash
sudo tlp setcharge 80 95 BAT0
Setting temporary charge thresholds for BAT0:
  stop  = 95
  start = 80
Activating...done.
```

yes, it just works in the first 1 second, but after that, it is still charging.

**Comment by linrunner** [comment]
Hi, 

it's a hardware problem. I read about this kind of quirk in the german ThinkPad forum. 

Try to power off to activate the thresholds after setcharge.

**Comment by gansteed** [comment]
I've reboot my system, but it still doesn't work :(

**Comment by linrunner** [comment]
Then your issue is a hardware problem that cannot be solved by software. I suggest you seek advice in a ThinkPad related forum.

**Comment by gansteed** [comment]
All right, thanks anyway :+1:
