### ISSUE TITLE
Machine freezes on boot / panics on suspend

### ISSUE THREAD

**Issue by rmetrich** [linrunner/TLP#125]
Hi,
Since upgrading to latest TLP for ubuntu 12.04 (0.7-1~precise), my machine freezes quickly after Xsession comes up when booting on battery (no issue when on AC).
Also, when suspending while on battery, a kernel panic occurs.
![p1030913](https://cloud.githubusercontent.com/assets/1163635/6185399/37ef47f2-b36e-11e4-88b5-3bb82a1bb9e2.JPG)

These behaviours are gone when disabling TLP.
This is 100% reproducible.

-----------------------------
TLP package:

Package: tlp
Priority: optional
Section: utils
Installed-Size: 278
Maintainer: Thomas Koch <linrunner@gmx.net>
Architecture: all
Version: 0.7-1~precise
Recommends: tlp-rdw, ethtool, linux-tools, linux-tools-common, linux-tools-generic, smartmontools
Suggests: tp-smapi-dkms, acpi-call-dkms
Depends: hdparm, iw | wireless-tools, pciutils, pm-utils, rfkill, usbutils
Conflicts: laptop-mode-tools
Filename: pool/main/t/tlp/tlp_0.7-1~precise_all.deb
Size: 58922
MD5sum: 7a723085f47aad4d4bac1e659e362d45
SHA1: c0282f2c3c487d87d4497fe5d0f26e0f32d7c7fa
SHA256: 8d31a972723a6cf15004face647a56ff7e2022badcd54b47acec1aef6a562a39

-----------------------------
Stats while on AC:

--- TLP 0.7 --------------------------------------------

+++ Configured Settings: /etc/default/tlp
TLP_ENABLE=1
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=0
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
SCHED_POWERSAVE_ON_AC=0
SCHED_POWERSAVE_ON_BAT=1
NMI_WATCHDOG=0
ENERGY_PERF_POLICY_ON_AC=performance
ENERGY_PERF_POLICY_ON_BAT=powersave
DISK_DEVICES="sda sdb"
DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"
DISK_IOSCHED="cfq deadline"
SATA_LINKPWR_ON_AC=max_performance
SATA_LINKPWR_ON_BAT=min_power
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=powersave
RADEON_POWER_PROFILE_ON_AC=high
RADEON_POWER_PROFILE_ON_BAT=low
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery
RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=auto
WIFI_PWR_ON_AC=1
WIFI_PWR_ON_BAT=5
WOL_DISABLE=N
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
BAY_POWEROFF_ON_BAT=0
BAY_DEVICE="sr0"
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
RUNTIME_PM_ALL=1
RUNTIME_PM_DRIVER_BLACKLIST="radeon nouveau"
USB_AUTOSUSPEND=1
USB_DRIVER_BLACKLIST="usbhid"
USB_BLACKLIST_WWAN=1
RESTORE_DEVICE_STATE_ON_STARTUP=0
DEVICES_TO_DISABLE_ON_LAN_CONNECT="wifi"
DEVICES_TO_ENABLE_ON_LAN_DISCONNECT="wifi"

+++ System Info
System         = ASUSTeK Computer Inc. 1.0 N53SN
BIOS           = N53SN.209
Release        = Ubuntu 12.04.5 LTS
Kernel         = 3.13.0-45-generic x86_64
/proc/cmdline  = BOOT_IMAGE=/vmlinuz-3.13.0-45-generic root=/dev/mapper/vg-rootlv_1204 ro splash quiet pci=nomsi bootchart=disable
Init system    = upstart

+++ System Status
TLP power save = enabled
power source   = ac

+++ Processor
CPU Model      = Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu4/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu4/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu4/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu5/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu5/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu5/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu6/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu6/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu6/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu7/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu7/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu7/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu7/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpufreq/boost                  = 1

x86_energy_perf_policy: program for your kernel not installed.

/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.

+++ Temperatures
CPU temp               =    43 [°C]
Fan speed              = (not available)

+++ File System
/proc/sys/vm/laptop_mode               =     0
/proc/sys/vm/dirty_writeback_centisecs =  1500
/proc/sys/vm/dirty_expire_centisecs    =  1500
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10
/proc/sys/fs/xfs/age_buffer_centisecs  =  1500
/proc/sys/fs/xfs/xfssyncd_centisecs    =  1500
/proc/sys/fs/xfs/xfsbufd_centisecs     =  3000

+++ Storage Devices
/dev/sda:
          Model     = WDC WD7500BPVT-80HXZT1                  
          Firmware  = 01.01A01
          APM Level = 254
          Status    = active/idle
          Scheduler = cfq

        SMART info:
            4 Start_Stop_Count          =    12465 
            5 Reallocated_Sector_Ct     =        0 
            9 Power_On_Hours            =     5908 [h]
          193 Load_Cycle_Count          =   166334 
          194 Temperature_Celsius       =       24    [°C]

/dev/sdb:
          Model     = M4-CT128M4SSD2                          
          Firmware  = 070H    
          APM Level = 254
          Status    = active/idle
          TRIM      = supported
          Scheduler = deadline

        SMART info:
            5 Reallocated_Sector_Ct     =        0 
            9 Power_On_Hours            =     4532 [h]
          194 Temperature_Celsius       =        0    [°C]

+++ SATA Aggressive Link Power Management
/sys/class/scsi_host/host0/link_power_management_policy  = max_performance
/sys/class/scsi_host/host1/link_power_management_policy  = max_performance
/sys/class/scsi_host/host2/link_power_management_policy  = max_performance
/sys/class/scsi_host/host3/link_power_management_policy  = max_performance
/sys/class/scsi_host/host4/link_power_management_policy  = max_performance
/sys/class/scsi_host/host5/link_power_management_policy  = max_performance

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = default (using bios preferences)

+++ Intel Graphics
/sys/module/i915/parameters/powersave        =  1 (enabled)
/sys/module/i915/parameters/i915_enable_rc6  =  1 (enabled)
/sys/module/i915/parameters/i915_enable_fbc  =  1 (enabled)
/sys/module/i915/parameters/lvds_downclock   =  1 (enabled)
/sys/module/i915/parameters/semaphores       = -1 (use per-chip default)

+++ Wireless
bluetooth = off (software)
wifi      = on
wwan      = none (no device)

hci0(btusb)         : not connected
wlan0(ath9k)        : connected, power management = off

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 0
/sys/module/snd_hda_intel/parameters/power_save_controller = N

+++ Runtime Power Management
device classes   = all
device blacklist = (not configured)
driver blacklist = radeon nouveau

/sys/bus/pci/devices/0000:00:00.0/power/control = on   (0x060000, Host bridge, no driver)
/sys/bus/pci/devices/0000:00:01.0/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:02.0/power/control = on   (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:16.0/power/control = on   (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:1a.0/power/control = on   (0x0c0320, USB controller, ehci-pci)
/sys/bus/pci/devices/0000:00:1b.0/power/control = on   (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1c.0/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.1/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.3/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.5/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1d.0/power/control = on   (0x0c0320, USB controller, ehci-pci)
/sys/bus/pci/devices/0000:00:1f.0/power/control = on   (0x060100, ISA bridge, lpc_ich)
/sys/bus/pci/devices/0000:00:1f.2/power/control = on   (0x010601, SATA controller, ahci)
/sys/bus/pci/devices/0000:00:1f.3/power/control = on   (0x0c0500, SMBus, no driver)
/sys/bus/pci/devices/0000:01:00.0/power/control = on   (0x030000, VGA compatible controller, no driver)
/sys/bus/pci/devices/0000:03:00.0/power/control = on   (0x028000, Network controller, ath9k)
/sys/bus/pci/devices/0000:04:00.0/power/control = on   (0x0c0330, USB controller, xhci_hcd)
/sys/bus/pci/devices/0000:05:00.0/power/control = on   (0x020000, Ethernet controller, r8169)

+++ USB
autosuspend        = enabled
device whitelist   = (not configured)
device blacklist   = (not configured)
driver blacklist   = usbhid
wwan blacklist     = enabled (cdc_acm cdc_wdm cdc_ether hso qcserial sierra)

Bus 001 Device 002 ID 8087:0024 control = auto, autosuspend_delay_ms =     0 -- Intel Corp. Integrated Rate Matching Hub (hub)
Bus 002 Device 002 ID 8087:0024 control = auto, autosuspend_delay_ms =     0 -- Intel Corp. Integrated Rate Matching Hub (hub)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 002 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 003 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 004 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 3.0 root hub (hub)
Bus 001 Device 009 ID 0cf3:3005 control = on,   autosuspend_delay_ms =  2000 -- Atheros Communications, Inc. AR3011 Bluetooth (btusb)
Bus 001 Device 004 ID 13d3:5122 control = auto, autosuspend_delay_ms =  2000 -- IMC Networks  (uvcvideo)

+++ Battery Status
/sys/class/power_supply/BAT0/manufacturer                   = ASUSTek
/sys/class/power_supply/BAT0/model_name                     = N61--52
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  57200 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  54142 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  54142 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Full

-----------------------------
Stats while on Battery:

--- TLP 0.7 --------------------------------------------

+++ Configured Settings: /etc/default/tlp
TLP_ENABLE=1
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=0
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
SCHED_POWERSAVE_ON_AC=0
SCHED_POWERSAVE_ON_BAT=1
NMI_WATCHDOG=0
ENERGY_PERF_POLICY_ON_AC=performance
ENERGY_PERF_POLICY_ON_BAT=powersave
DISK_DEVICES="sda sdb"
DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"
DISK_IOSCHED="cfq deadline"
SATA_LINKPWR_ON_AC=max_performance
SATA_LINKPWR_ON_BAT=min_power
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=powersave
RADEON_POWER_PROFILE_ON_AC=high
RADEON_POWER_PROFILE_ON_BAT=low
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery
RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=auto
WIFI_PWR_ON_AC=1
WIFI_PWR_ON_BAT=5
WOL_DISABLE=N
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
BAY_POWEROFF_ON_BAT=0
BAY_DEVICE="sr0"
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
RUNTIME_PM_ALL=1
RUNTIME_PM_DRIVER_BLACKLIST="radeon nouveau"
USB_AUTOSUSPEND=1
USB_DRIVER_BLACKLIST="usbhid"
USB_BLACKLIST_WWAN=1
RESTORE_DEVICE_STATE_ON_STARTUP=0
DEVICES_TO_DISABLE_ON_LAN_CONNECT="wifi"
DEVICES_TO_ENABLE_ON_LAN_DISCONNECT="wifi"

+++ System Info
System         = ASUSTeK Computer Inc. 1.0 N53SN
BIOS           = N53SN.209
Release        = Ubuntu 12.04.5 LTS
Kernel         = 3.13.0-45-generic x86_64
/proc/cmdline  = BOOT_IMAGE=/vmlinuz-3.13.0-45-generic root=/dev/mapper/vg-rootlv_1204 ro splash quiet pci=nomsi bootchart=disable
Init system    = upstart

+++ System Status
TLP power save = enabled
power source   = battery

+++ Processor
CPU Model      = Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu4/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu4/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu4/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu5/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu5/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu5/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu6/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu6/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu6/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpu7/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu7/cpufreq/scaling_governor  = performance
/sys/devices/system/cpu/cpu7/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq  =  2001000 [kHz]
/sys/devices/system/cpu/cpu7/cpufreq/scaling_available_frequencies = 2001000 2000000 1900000 1800000 1700000 1600000 1500000 1400000 1300000 1200000 1100000 1000000 900000 800000 [kHz]

/sys/devices/system/cpu/cpufreq/boost                  = 0

x86_energy_perf_policy: program for your kernel not installed.

/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.

+++ Temperatures
CPU temp               =    40 [°C]
Fan speed              = (not available)

+++ File System
/proc/sys/vm/laptop_mode               =     2
/proc/sys/vm/dirty_writeback_centisecs =  6000
/proc/sys/vm/dirty_expire_centisecs    =  6000
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10
/proc/sys/fs/xfs/age_buffer_centisecs  =  6000
/proc/sys/fs/xfs/xfssyncd_centisecs    =  6000
/proc/sys/fs/xfs/xfsbufd_centisecs     =  3000

+++ Storage Devices
/dev/sda:
          Model     = WDC WD7500BPVT-80HXZT1                  
          Firmware  = 01.01A01
          APM Level = 128
          Status    = active/idle
          Scheduler = cfq

        SMART info:
            4 Start_Stop_Count          =    12465 
            5 Reallocated_Sector_Ct     =        0 
            9 Power_On_Hours            =     5908 [h]
          193 Load_Cycle_Count          =   166334 
          194 Temperature_Celsius       =       23    [°C]

/dev/sdb:
          Model     = M4-CT128M4SSD2                          
          Firmware  = 070H    
          APM Level = 128
          Status    = active/idle
          TRIM      = supported
          Scheduler = deadline

        SMART info:
            5 Reallocated_Sector_Ct     =        0 
            9 Power_On_Hours            =     4532 [h]
          194 Temperature_Celsius       =        0    [°C]

+++ SATA Aggressive Link Power Management
/sys/class/scsi_host/host0/link_power_management_policy  = min_power
/sys/class/scsi_host/host1/link_power_management_policy  = min_power
/sys/class/scsi_host/host2/link_power_management_policy  = min_power
/sys/class/scsi_host/host3/link_power_management_policy  = min_power
/sys/class/scsi_host/host4/link_power_management_policy  = min_power
/sys/class/scsi_host/host5/link_power_management_policy  = min_power

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = default (using bios preferences)

+++ Intel Graphics
/sys/module/i915/parameters/powersave        =  1 (enabled)
/sys/module/i915/parameters/i915_enable_rc6  =  1 (enabled)
/sys/module/i915/parameters/i915_enable_fbc  =  1 (enabled)
/sys/module/i915/parameters/lvds_downclock   =  1 (enabled)
/sys/module/i915/parameters/semaphores       = -1 (use per-chip default)

+++ Wireless
bluetooth = off (software)
wifi      = on
wwan      = none (no device)

hci0(btusb)         : not connected
wlan0(ath9k)        : connected, power management = off

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 1
/sys/module/snd_hda_intel/parameters/power_save_controller = Y

+++ Runtime Power Management
device classes   = all
device blacklist = (not configured)
driver blacklist = radeon nouveau

/sys/bus/pci/devices/0000:00:00.0/power/control = auto (0x060000, Host bridge, no driver)
/sys/bus/pci/devices/0000:00:01.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:02.0/power/control = auto (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:16.0/power/control = auto (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:1a.0/power/control = auto (0x0c0320, USB controller, ehci-pci)
/sys/bus/pci/devices/0000:00:1b.0/power/control = auto (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1c.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.1/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.3/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.5/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1d.0/power/control = auto (0x0c0320, USB controller, ehci-pci)
/sys/bus/pci/devices/0000:00:1f.0/power/control = auto (0x060100, ISA bridge, lpc_ich)
/sys/bus/pci/devices/0000:00:1f.2/power/control = auto (0x010601, SATA controller, ahci)
/sys/bus/pci/devices/0000:00:1f.3/power/control = auto (0x0c0500, SMBus, no driver)
/sys/bus/pci/devices/0000:01:00.0/power/control = auto (0x030000, VGA compatible controller, no driver)
/sys/bus/pci/devices/0000:03:00.0/power/control = auto (0x028000, Network controller, ath9k)
/sys/bus/pci/devices/0000:04:00.0/power/control = auto (0x0c0330, USB controller, xhci_hcd)
/sys/bus/pci/devices/0000:05:00.0/power/control = auto (0x020000, Ethernet controller, r8169)

+++ USB
autosuspend        = enabled
device whitelist   = (not configured)
device blacklist   = (not configured)
driver blacklist   = usbhid
wwan blacklist     = enabled (cdc_acm cdc_wdm cdc_ether hso qcserial sierra)

Bus 001 Device 002 ID 8087:0024 control = auto, autosuspend_delay_ms =     0 -- Intel Corp. Integrated Rate Matching Hub (hub)
Bus 002 Device 002 ID 8087:0024 control = auto, autosuspend_delay_ms =     0 -- Intel Corp. Integrated Rate Matching Hub (hub)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 002 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 003 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 004 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 3.0 root hub (hub)
Bus 001 Device 009 ID 0cf3:3005 control = on,   autosuspend_delay_ms =  2000 -- Atheros Communications, Inc. AR3011 Bluetooth (btusb)
Bus 001 Device 004 ID 13d3:5122 control = auto, autosuspend_delay_ms =  2000 -- IMC Networks  (uvcvideo)

+++ Battery Status
/sys/class/power_supply/BAT0/manufacturer                   = ASUSTek
/sys/class/power_supply/BAT0/model_name                     = N61--52
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  57200 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  54142 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  54296 [mWh]
/sys/class/power_supply/BAT0/power_now                      =  17919 [mW]
/sys/class/power_supply/BAT0/status                         = Discharging

**Comment by linrunner** [comment]
Hi, try with this setting:

    RUNTIME_PM_ALL=0

**Comment by rmetrich** [comment]
Thanks, this works!

**Comment by linrunner** [comment]
I suspect the discrete part of your hybrid graphics (Nvidia?):

     /sys/bus/pci/devices/0000:01:00.0/power/control = auto (0x030000, VGA compatible controller, no driver)

Unfortunately it has no driver loaded, so TLP can't blacklist it automatically. Please try again with:

    RUNTIME_PM_ALL=1
    RUNTIME_PM_BLACKLIST="03:00.0"

**Comment by rmetrich** [comment]
Doesn't help (after replacing 03:00.0 by the right id 01:00.0)

**Comment by linrunner** [comment]
I see. You may a. revert to RUNTIME_PM_ALL=0 for the sake of simplicity or b. try the other PCI devices in RUNTIME_PM_BLACKLIST one by one.
