### ISSUE TITLE
Thinkpad T400 -  tp-smapi   = inactive (kernel module 'tp_smapi' load error)

### ISSUE THREAD

**Issue by japa-fi** [linrunner/TLP#132]
Hi.
Can't get the tp_smapi module to load. I have Thinkpad T400, with a battery which is not original lenovo battery (win 7 pops up a notitication that battery is not genuine thinkpad battery). I've restarted my laptop couple of times and also reinstalled the .rpm packages twice too.
Checked https://github.com/linrunner/TLP/issues/114 and here are some of the output you asked in that case.

[root@localhost ~]# modprobe -v tp_smapi
insmod /lib/modules/3.18.7-200.fc21.x86_64/extra/tp_smapi/thinkpad_ec.ko 
modprobe: ERROR: could not insert 'tp_smapi': No such device or address

[root@localhost ~]# ls -l  /lib/modules/3.18.7-200.fc21.x86_64/extra/tp_smapi/
total 104
-rw-r--r--. 1 root root 35712 Mar  7 22:32 hdaps.ko
-rw-r--r--. 1 root root 14552 Mar  7 22:32 thinkpad_ec.ko
-rw-r--r--. 1 root root 49192 Mar  7 22:32 tp_smapi.ko

[root@localhost ~]# cat /var/cache/akmods/aksmod.log
cat: /var/cache/akmods/aksmod.log: No such file or directory

[root@localhost ~]# cat /var/cache/akmods/acpi_call/.last.log
2015/03/07 22:31:42 akmods: Building RPM using the command '/bin/akmodsbuild --target x86_64 --kernels 3.18.7-200.fc21.x86_64 /usr/src/akmods/acpi_call-kmod.latest'
2015/03/07 22:31:45 akmodsbuild: * Rebuilding /usr/src/akmods/acpi_call-kmod.latest for kernel(s) 3.18.7-200.fc21.x86_64: warning: user build does not exist - using root
2015/03/07 22:31:45 akmodsbuild: warning: group build does not exist - using root
2015/03/07 22:31:45 akmodsbuild: warning: user build does not exist - using root
2015/03/07 22:31:45 akmodsbuild: warning: group build does not exist - using root
2015/03/07 22:31:45 akmodsbuild: warning: user build does not exist - using root
2015/03/07 22:31:45 akmodsbuild: warning: group build does not exist - using root
2015/03/07 22:31:45 akmodsbuild: Installing /usr/src/akmods/acpi_call-kmod.latest
2015/03/07 22:31:45 akmodsbuild: Building target platforms: x86_64
2015/03/07 22:31:45 akmodsbuild: Building for target x86_64
2015/03/07 22:31:45 akmodsbuild: Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Bi36f3
2015/03/07 22:31:45 akmodsbuild: + umask 022
2015/03/07 22:31:45 akmodsbuild: + cd /tmp/akmodsbuild.i8P0gfK9//BUILD
2015/03/07 22:31:45 akmodsbuild: + kmodtool --target x86_64 --repo rpmfusion --kmodname acpi_call-kmod --for-kernels 3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: %package       -n kmod-acpi_call-3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: Summary:          acpi_call kernel module(s) for 3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: Group:            System Environment/Kernel
2015/03/07 22:31:45 akmodsbuild: Provides:         kernel-modules-for-kernel = 3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: Provides:         acpi_call-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
2015/03/07 22:31:45 akmodsbuild: Requires:         acpi_call-kmod-common >= %{?epoch:%{epoch}:}%{version}
2015/03/07 22:31:45 akmodsbuild: Requires(post):   /usr/sbin/depmod
2015/03/07 22:31:45 akmodsbuild: Requires(postun): /usr/sbin/depmod
2015/03/07 22:31:45 akmodsbuild: Requires:         kernel-uname-r = 3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: BuildRequires:	  kernel-devel-uname-r = 3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: %post          -n kmod-acpi_call-3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: /usr/sbin/depmod -aeF /boot/System.map-3.18.7-200.fc21.x86_64 3.18.7-200.fc21.x86_64 > /dev/null || :
2015/03/07 22:31:45 akmodsbuild: %postun        -n kmod-acpi_call-3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: /usr/sbin/depmod  -aF /boot/System.map-3.18.7-200.fc21.x86_64 3.18.7-200.fc21.x86_64 &> /dev/null || :
2015/03/07 22:31:45 akmodsbuild: 
2015/03/07 22:31:45 akmodsbuild: %description  -n kmod-acpi_call-3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: This package provides the acpi_call kernel modules built for the Linux
2015/03/07 22:31:45 akmodsbuild: kernel 3.18.7-200.fc21.x86_64 for the %{_target_cpu} family of processors.
2015/03/07 22:31:45 akmodsbuild: %files        -n kmod-acpi_call-3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: %defattr(644,root,root,755)
2015/03/07 22:31:45 akmodsbuild: %dir /usr/lib/modules/3.18.7-200.fc21.x86_64/extra
2015/03/07 22:31:45 akmodsbuild: /usr/lib/modules/3.18.7-200.fc21.x86_64/extra/acpi_call/
2015/03/07 22:31:45 akmodsbuild: 
2015/03/07 22:31:45 akmodsbuild: 
2015/03/07 22:31:45 akmodsbuild: 
2015/03/07 22:31:45 akmodsbuild: %global kmodinstdir_prefix  /usr/lib/modules/
2015/03/07 22:31:45 akmodsbuild: %global kmodinstdir_postfix /extra/acpi_call/
2015/03/07 22:31:45 akmodsbuild: %global kernel_versions     3.18.7-200.fc21.x86_64___%{_usrsrc}/kernels/3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: 
2015/03/07 22:31:45 akmodsbuild: + cd /tmp/akmodsbuild.i8P0gfK9/BUILD
2015/03/07 22:31:45 akmodsbuild: + rm -rf acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + /usr/bin/mkdir -p acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + cd acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + /usr/bin/gzip -dc /tmp/akmodsbuild.i8P0gfK9/SOURCES/acpi_call-1.1.0.tar.gz
2015/03/07 22:31:45 akmodsbuild: + /usr/bin/tar -xf -
2015/03/07 22:31:45 akmodsbuild: + STATUS=0
2015/03/07 22:31:45 akmodsbuild: + '[' 0 -ne 0 ']'
2015/03/07 22:31:45 akmodsbuild: + /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
2015/03/07 22:31:45 akmodsbuild: + pushd acpi_call-1.1.0
2015/03/07 22:31:45 akmodsbuild: /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/acpi_call-1.1.0 /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + echo 'Patch #0 (acpi_call-1.1.0.fc21-x86_64.patch):'
2015/03/07 22:31:45 akmodsbuild: Patch #0 (acpi_call-1.1.0.fc21-x86_64.patch):
2015/03/07 22:31:45 akmodsbuild: + /usr/bin/cat /tmp/akmodsbuild.i8P0gfK9/SOURCES/acpi_call-1.1.0.fc21-x86_64.patch
2015/03/07 22:31:45 akmodsbuild: + /usr/bin/patch -p1 --fuzz=0
2015/03/07 22:31:45 akmodsbuild: patching file acpi_call.c
2015/03/07 22:31:45 akmodsbuild: patching file Makefile
2015/03/07 22:31:45 akmodsbuild: + popd
2015/03/07 22:31:45 akmodsbuild: /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + for ext in c h
2015/03/07 22:31:45 akmodsbuild: + find . -name '*.c' -exec chmod -x '{}' ';'
2015/03/07 22:31:45 akmodsbuild: + for ext in c h
2015/03/07 22:31:45 akmodsbuild: + find . -name '*.h' -exec chmod -x '{}' ';'
2015/03/07 22:31:45 akmodsbuild: + for kernel_version in 3.18.7-200.fc21.x86_64___/usr/src/kernels/3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + cp -a acpi_call-1.1.0 _kmod_build_3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + exit 0
2015/03/07 22:31:45 akmodsbuild: Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.ZP6oQ3
2015/03/07 22:31:45 akmodsbuild: + umask 022
2015/03/07 22:31:45 akmodsbuild: + cd /tmp/akmodsbuild.i8P0gfK9//BUILD
2015/03/07 22:31:45 akmodsbuild: + cd acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + for kernel_version in 3.18.7-200.fc21.x86_64___/usr/src/kernels/3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + /usr/bin/make -j2 -C _kmod_build_3.18.7-200.fc21.x86_64 KVER=3.18.7-200.fc21.x86_64 KBUILD=/usr/src/kernels/3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: make: Entering directory '/tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/_kmod_build_3.18.7-200.fc21.x86_64'
2015/03/07 22:31:45 akmodsbuild: /usr/bin/make -C /usr/src/kernels/3.18.7-200.fc21.x86_64 M=/tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/_kmod_build_3.18.7-200.fc21.x86_64 O=/usr/lib/modules//build O=/usr/src/kernels/3.18.7-200.fc21.x86_64 modules
2015/03/07 22:31:45 akmodsbuild: make[1]: Entering directory '/usr/src/kernels/3.18.7-200.fc21.x86_64'
2015/03/07 22:31:45 akmodsbuild: make[2]: Entering directory '/usr/src/kernels/3.18.7-200.fc21.x86_64'
2015/03/07 22:31:45 akmodsbuild: CC [M]  /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/_kmod_build_3.18.7-200.fc21.x86_64/acpi_call.o
2015/03/07 22:31:45 akmodsbuild: Building modules, stage 2.
2015/03/07 22:31:45 akmodsbuild: MODPOST 1 modules
2015/03/07 22:31:45 akmodsbuild: CC      /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/_kmod_build_3.18.7-200.fc21.x86_64/acpi_call.mod.o
2015/03/07 22:31:45 akmodsbuild: LD [M]  /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/_kmod_build_3.18.7-200.fc21.x86_64/acpi_call.ko
2015/03/07 22:31:45 akmodsbuild: make[2]: Leaving directory '/usr/src/kernels/3.18.7-200.fc21.x86_64'
2015/03/07 22:31:45 akmodsbuild: make[1]: Leaving directory '/usr/src/kernels/3.18.7-200.fc21.x86_64'
2015/03/07 22:31:45 akmodsbuild: make: Leaving directory '/tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/_kmod_build_3.18.7-200.fc21.x86_64'
2015/03/07 22:31:45 akmodsbuild: + exit 0
2015/03/07 22:31:45 akmodsbuild: Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.owzhu9
2015/03/07 22:31:45 akmodsbuild: + umask 022
2015/03/07 22:31:45 akmodsbuild: + cd /tmp/akmodsbuild.i8P0gfK9//BUILD
2015/03/07 22:31:45 akmodsbuild: + '[' /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64 '!=' / ']'
2015/03/07 22:31:45 akmodsbuild: + rm -rf /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: ++ dirname /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + mkdir -p /tmp/akmodsbuild.i8P0gfK9/BUILDROOT
2015/03/07 22:31:45 akmodsbuild: + mkdir /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + cd acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + rm -rf /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + for kernel_version in 3.18.7-200.fc21.x86_64___/usr/src/kernels/3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + mkdir -p /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64/usr/lib/modules//3.18.7-200.fc21.x86_64//extra/acpi_call/
2015/03/07 22:31:45 akmodsbuild: + pushd _kmod_build_3.18.7-200.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0/_kmod_build_3.18.7-200.fc21.x86_64 /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + install -D -m 0755 acpi_call.ko /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64/usr/lib/modules//3.18.7-200.fc21.x86_64//extra/acpi_call/
2015/03/07 22:31:45 akmodsbuild: + popd
2015/03/07 22:31:45 akmodsbuild: /tmp/akmodsbuild.i8P0gfK9/BUILD/acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/check-buildroot
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/brp-compress
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/brp-strip /usr/bin/strip
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/brp-python-hardlink
2015/03/07 22:31:45 akmodsbuild: + /usr/lib/rpm/redhat/brp-java-repack-jars
2015/03/07 22:31:45 akmodsbuild: Processing files: kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: Provides: acpi_call-kmod = 1.1.0-3.fc21 kernel-modules-for-kernel = 3.18.7-200.fc21.x86_64 kmod-acpi_call-3.18.7-200.fc21.x86_64 = 1.1.0-3.fc21 kmod-acpi_call-3.18.7-200.fc21.x86_64(x86-64) = 1.1.0-3.fc21
2015/03/07 22:31:45 akmodsbuild: Requires(interp): /bin/sh /bin/sh
2015/03/07 22:31:45 akmodsbuild: Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
2015/03/07 22:31:45 akmodsbuild: Requires(post): /bin/sh /usr/sbin/depmod
2015/03/07 22:31:45 akmodsbuild: Requires(postun): /bin/sh /usr/sbin/depmod
2015/03/07 22:31:45 akmodsbuild: Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: Wrote: /tmp/akmodsbuild.i8P0gfK9/RPMS/x86_64/kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64.rpm
2015/03/07 22:31:45 akmodsbuild: Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.xyHJTf
2015/03/07 22:31:45 akmodsbuild: + umask 022
2015/03/07 22:31:45 akmodsbuild: + cd /tmp/akmodsbuild.i8P0gfK9//BUILD
2015/03/07 22:31:45 akmodsbuild: + cd acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + rm -rf /tmp/akmodsbuild.i8P0gfK9/BUILDROOT/acpi_call-kmod-1.1.0-3.fc21.x86_64
2015/03/07 22:31:45 akmodsbuild: + exit 0
2015/03/07 22:31:45 akmodsbuild: Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.5tpOjm
2015/03/07 22:31:45 akmodsbuild: + umask 022
2015/03/07 22:31:45 akmodsbuild: + cd /tmp/akmodsbuild.i8P0gfK9//BUILD
2015/03/07 22:31:45 akmodsbuild: + rm -rf acpi_call-kmod-1.1.0
2015/03/07 22:31:45 akmodsbuild: + exit 0
2015/03/07 22:31:45 akmods: Installing newly built rpms
Loaded plugins: langpacks
Examining /tmp/akmods.iAedJlc0/results/kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64.rpm: kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64
Marking /tmp/akmods.iAedJlc0/results/kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package kmod-acpi_call-3.18.7-200.fc21.x86_64.x86_64 0:1.1.0-3.fc21 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package
    Arch   Version
               Repository                                                  Size
================================================================================
Installing:
 kmod-acpi_call-3.18.7-200.fc21.x86_64
    x86_64 1.1.0-3.fc21
               /kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64  11 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 11 k
Installed size: 11 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction (shutdown inhibited)
  Installing : kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64    1/1 
  Verifying  : kmod-acpi_call-3.18.7-200.fc21.x86_64-1.1.0-3.fc21.x86_64    1/1 

Installed:
  kmod-acpi_call-3.18.7-200.fc21.x86_64.x86_64 0:1.1.0-3.fc21                   

Complete!
2015/03/07 22:31:57 akmods: Successful.

[root@localhost ~]# uname -a
Linux localhost.localdomain 3.18.7-200.fc21.x86_64 #1 SMP Wed Feb 11 21:53:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost ~]# ls -l /usr/lib/modules/*/extra/acpi_call/acpi_call.ko
-rw-r--r--. 1 root root 11424 Mar  7 22:31 /usr/lib/modules/3.18.7-200.fc21.x86_64/extra/acpi_call/acpi_call.ko

[root@localhost ~]# modinfo /usr/lib/modules/*/extra/acpi_call/acpi_call.ko
filename:       /usr/lib/modules/3.18.7-200.fc21.x86_64/extra/acpi_call/acpi_call.ko
license:        GPL
depends:        
vermagic:       3.18.7-200.fc21.x86_64 SMP mod_unload 
[root@localhost ~]# modinfo /usr/lib/modules/*/extra/acpi_call/acpi_call.ko
filename:       /usr/lib/modules/3.18.7-200.fc21.x86_64/extra/acpi_call/acpi_call.ko
license:        GPL
depends:        
vermagic:       3.18.7-200.fc21.x86_64 SMP mod_unload 

To my limited knowledge, I can't find anything wrong with above output.
Comments appreciated.

**Comment by linrunner** [comment]
Hi.

> [root@localhost ~]# modprobe -v tp_smapi
> insmod /lib/modules/3.18.7-200.fc21.x86_64/extra/tp_smapi/thinkpad_ec.ko
> modprobe: ERROR: could not insert 'tp_smapi': No such device or address

This is not a problem with TLP nor is it a problem with the akmod-tp_smapi package provided in the TLP repo. It's just that your T400 refuses to load tp-smapi's kernel modules. I suggest you use adequate forums to resolve this issue with tp-smapi.

**Comment by japa-fi** [comment]
On 2015-03-07 23:23, linrunner notifications-at-github.com
|github/Example Allow| wrote:
> Hi.
> 
>     [root@localhost ~]# modprobe -v tp_smapi
>     insmod /lib/modules/3.18.7-200.fc21.x86_64/extra/tp_smapi/thinkpad_ec.ko
>     modprobe: ERROR: could not insert 'tp_smapi': No such device or address
> 
> This is not a problem with TLP nor is it a problem with the
> akmod-tp_smapi package provided in the TLP repo. It's just that your
> T400 refuses to load tp-smapi's kernel modules. I suggest you use
> adequate forums to resolve this issue with tp-smapi.

Thank you for you comment.
Btw. tlp works fine with my other laptop (T430, using akmod-acpi_call)
thanks for creating tpl.

Update (1 hour later):
https://github.com/evgeni/tp_smapi states:
=======================================================
Module parameters
-----------------

thinkpad_ec module:
  force_io=1 lets thinkpad_ec load on some recent ThinkPad models
  (e.g., T400 and T500) whose BIOS's ACPI DSDT reserves the ports we need.
=======================================================

Added options thinkpad_ec force_io=1' to thinkpad_ec.conf
Now I got the module loaded. Now, lets start experimenting with the
battery parameters :).
