### ISSUE TITLE
P-State Max/Min performance values not working correctly on kernel 4.0

### ISSUE THREAD

**Issue by lamiska** [linrunner/TLP#138]
Intel p-state performance setting is not working correctly under linux kernel 4.0

Here is what I have in /etc/default/tlp:

`CPU_MIN_PERF_ON_AC=50`
`CPU_MAX_PERF_ON_AC=100`
`CPU_MIN_PERF_ON_BAT=0`
`CPU_MAX_PERF_ON_BAT=30`

Here is output from tlp-stat -p on ac:

`/sys/devices/system/cpu/intel_pstate/min_perf_pct      = 100`
`/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100`

and on batt:

`/sys/devices/system/cpu/intel_pstate/min_perf_pct      = 47`
`/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 30`

Rebooting into 3.19 kernel fixes the issue for me and tlp-stat -p is showing correct values.
My tlp version is 0.7, CPU is i3-4005U, Archlinux distribution.

**Comment by linrunner** [comment]
Hi, 

this is (likely) a kernel issue with your specific hardware. I suggest you file a kernel bug. 
See https://github.com/linrunner/TLP/issues/122 too.
