### ISSUE TITLE
Fedora 22 Thinkpads modules repo

### ISSUE THREAD

**Issue by al09219** [linrunner/TLP#142]
Are there any plans for Fedora 22 Thinkpads modules repo?

**Comment by linrunner** [comment]
Yes, of course. Thanks for your hint.

**Comment by al09219** [comment]
Thanks, I'm looking forward

**Comment by aiguofer** [comment]
:) I just realized my battery was charging all the way again... went to check on it, turns out acpi_call is failing to build using fc21 akmod.

Hope we can have this soon! thanks for your work

**Comment by huangp** [comment]
+1 waiting for it

**Comment by abdulmoeedammar** [comment]
Any update or ETA?

**Comment by thomasfedb** [comment]
Really hoping to get this soon.

**Comment by linrunner** [comment]
Packages are online now (repo:tlp-release). Thanks for your patience.
