### ISSUE TITLE
thinkpad onelink dock -- udev rule request

### ISSUE THREAD

**Issue by voland66** [linrunner/TLP#144]
Hi,
I have thinkpad yoga 12 with onelink dock (basic, there is also pro).
TLP was not recognizing it properly until I added a line with
ENV{PRODUCT}=="17ef/3049/*"
to the 85-tlp-rdw.rules. Everything else is the same as other lines usb_dock lines.
I will need to check again tomorrow, but I think it now works, i.e. with this line the wifi is turned off on docking (worked before) and turned on undocking (did not work before).

If you think this is a correct line and could add it to the udev file for future releases, it would be great.

**Comment by linrunner** [comment]
Hi, 
thanks for your contribution. I had one pull request already, so the other one must be the Pro version.
