### ISSUE TITLE
Does TLP works in a virtual machine ?

### ISSUE THREAD

**Issue by forkmind** [linrunner/TLP#145]
Sorry for opening a commit for this but I haven't any other way to contact you. I often use ubuntu inside Wmware on my mac and autonomy is a great concern. Is there an utility to use this tool in a V.M. ?

**Comment by linrunner** [comment]
It is generally not effective to run a power management tool *inside* a virtual machine (guest). This has to be done in the host operating system - MacOS in your case.

**Please note: the issue tracker is intended for bug reports only. There a lots of adequate Linux forums for your questions. Thanks for you understanding.**
