### ISSUE TITLE
TLP does not switch CPU Governor when plugged in.

### ISSUE THREAD

**Issue by duschendestroyer** [linrunner/TLP#147]
Below is the output of tlp stat after plugging in the ac adapter.
tlp knows that I'm on ac power but the governor is still powersave even though the configuration states that it should switch to performance.
When I use tlp ac to switch to ac mode manually, everything works as expected.
But disconnecting the AC adapter afterwards does not change the governor either, so it stays at performance.

Distribution: Archlinux
Hardware: Thinkpad X250, intel i5 5200U

--- TLP 0.7 --------------------------------------------

+++ Configured Settings: /etc/default/tlp
TLP_ENABLE=1
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
SCHED_POWERSAVE_ON_AC=0
SCHED_POWERSAVE_ON_BAT=1
NMI_WATCHDOG=0
ENERGY_PERF_POLICY_ON_AC=performance
ENERGY_PERF_POLICY_ON_BAT=powersave
DISK_DEVICES="sda sdb"
DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"
SATA_LINKPWR_ON_AC=max_performance
SATA_LINKPWR_ON_BAT=min_power
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=powersave
RADEON_POWER_PROFILE_ON_AC=high
RADEON_POWER_PROFILE_ON_BAT=low
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery
RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=auto
WIFI_PWR_ON_AC=1
WIFI_PWR_ON_BAT=5
WOL_DISABLE=Y
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
BAY_POWEROFF_ON_BAT=0
BAY_DEVICE="sr0"
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
RUNTIME_PM_ALL=1
RUNTIME_PM_DRIVER_BLACKLIST="radeon nouveau"
USB_AUTOSUSPEND=1
USB_DRIVER_BLACKLIST="usbhid"
USB_BLACKLIST_WWAN=1
RESTORE_DEVICE_STATE_ON_STARTUP=0

+++ System Info
System         = LENOVO ThinkPad X250 20CLS06A00
BIOS           = N10ET28W (1.05 )
Kernel         = 4.0.5-1-ARCH x86_64
/proc/cmdline  = initrd=\initramfs-linux.img cryptdevice=/dev/sda6:vgroup:allow-discards resume=/dev/mapper/vgroup-swap video.use_native_backlight=1 root=/dev/mapper/vgroup-root ro
Init system    = systemd

+++ System Status
TLP power save = enabled
power source   = ac

+++ Processor
CPU Model      = Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/intel_pstate/min_perf_pct      = 18
/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100
/sys/devices/system/cpu/intel_pstate/no_turbo          = 1

x86_energy_perf_policy.cpu0                            = powersave
x86_energy_perf_policy.cpu1                            = powersave
x86_energy_perf_policy.cpu2                            = powersave
x86_energy_perf_policy.cpu3                            = powersave

/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.

+++ Temperatures
CPU temp               =    45 [°C]
/proc/acpi/ibm/fan     =  2565 [/min]

+++ File System
/proc/sys/vm/laptop_mode               =     2
/proc/sys/vm/dirty_writeback_centisecs =  6000
/proc/sys/vm/dirty_expire_centisecs    =  6000
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10
/proc/sys/fs/xfs/age_buffer_centisecs  = (not available)
/proc/sys/fs/xfs/xfssyncd_centisecs    = (not available)
/proc/sys/fs/xfs/xfsbufd_centisecs     = (not available)

+++ Storage Devices
/dev/sda:
          Model     = Samsung SSD 850 EVO 250GB               
          Firmware  = EMT01B6Q
          APM Level = none/disabled
          Status    = active/idle
          TRIM      = supported
          Scheduler = cfq

        SMART info:
            5 Reallocated_Sector_Ct     =        0 
            9 Power_On_Hours            =      856 [h]
          177 Wear_Leveling_Count       =       99 [%]
          179 Used_Rsvd_Blk_Cnt_Tot     =        0 
          190 Airflow_Temperature_Cel   =       32 [°C]
          241 Total_LBAs_Written        =    1.333 [TB]

+++ SATA Aggressive Link Power Management
/sys/class/scsi_host/host0/link_power_management_policy  = min_power
/sys/class/scsi_host/host1/link_power_management_policy  = min_power
/sys/class/scsi_host/host2/link_power_management_policy  = min_power

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = default (using bios preferences)

+++ Intel Graphics
/sys/module/i915/parameters/powersave        =  1 (enabled)
/sys/module/i915/parameters/enable_rc6       =  1 (enabled)
/sys/module/i915/parameters/enable_fbc       = -1 (use per-chip default)
/sys/module/i915/parameters/lvds_downclock   =  0 (disabled)
/sys/module/i915/parameters/semaphores       = -1 (use per-chip default)

+++ Wireless
bluetooth = on
wifi      = on
wwan      = none (no device)

hci0(btusb)         : not connected
wlp3s0(iwlwifi)     : connected, power management = on

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 1
/sys/module/snd_hda_intel/parameters/power_save_controller = Y

+++ Docks and Device Bays
/sys/devices/platform/dock.0: battery_bay   = battery present

+++ Runtime Power Management
device classes   = all
device blacklist = (not configured)
driver blacklist = radeon nouveau

/sys/bus/pci/devices/0000:00:00.0/power/control = auto (0x060000, Host bridge, no driver)
/sys/bus/pci/devices/0000:00:02.0/power/control = auto (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:03.0/power/control = auto (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:14.0/power/control = auto (0x0c0330, USB controller, xhci_hcd)
/sys/bus/pci/devices/0000:00:16.0/power/control = auto (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:19.0/power/control = auto (0x020000, Ethernet controller, e1000e)
/sys/bus/pci/devices/0000:00:1b.0/power/control = auto (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1c.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.1/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1d.0/power/control = auto (0x0c0320, USB controller, ehci-pci)
/sys/bus/pci/devices/0000:00:1f.0/power/control = auto (0x060100, ISA bridge, lpc_ich)
/sys/bus/pci/devices/0000:00:1f.2/power/control = auto (0x010601, SATA controller, ahci)
/sys/bus/pci/devices/0000:00:1f.3/power/control = auto (0x0c0500, SMBus, i801_smbus)
/sys/bus/pci/devices/0000:00:1f.6/power/control = auto (0x118000, Signal processing controller, no driver)
/sys/bus/pci/devices/0000:02:00.0/power/control = auto (0xff0000, Unassigned class [ff00], rtsx_pci)
/sys/bus/pci/devices/0000:03:00.0/power/control = auto (0x028000, Network controller, iwlwifi)

+++ USB
autosuspend        = enabled
device whitelist   = (not configured)
device blacklist   = (not configured)
driver blacklist   = usbhid
wwan blacklist     = enabled (cdc_acm cdc_wdm cdc_ether hso qcserial sierra)

Bus 001 Device 002 ID 8087:8001 control = auto, autosuspend_delay_ms =     0 -- Intel Corp.  (hub)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 003 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 3.0 root hub (hub)
Bus 002 Device 005 ID 04ca:703c control = auto, autosuspend_delay_ms =  2000 -- Lite-On Technology Corp.  (uvcvideo)
Bus 002 Device 004 ID 8087:0a2a control = auto, autosuspend_delay_ms =  2000 -- Intel Corp.  (btusb)
Bus 002 Device 003 ID 138a:0017 control = auto, autosuspend_delay_ms =  2000 -- Validity Sensors, Inc. Fingerprint Reader (no driver)
Bus 002 Device 002 ID 058f:9540 control = auto, autosuspend_delay_ms =  2000 -- Alcor Micro Corp. AU9540 Smartcard Reader (no driver)
Bus 002 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)

+++ ThinkPad Extended Battery Functions
tp-smapi   = inactive (kernel module 'tp_smapi' not installed)
tpacpi-bat = inactive (kernel module 'acpi_call' not installed)

+++ Battery Status
/sys/class/power_supply/BAT0/manufacturer                   = SANYO
/sys/class/power_supply/BAT0/model_name                     = 45N1773
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  23200 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  18270 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  14540 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Unknown

+++ Battery Status
/sys/class/power_supply/BAT1/manufacturer                   = SANYO
/sys/class/power_supply/BAT1/model_name                     = 45N1775
/sys/class/power_supply/BAT1/cycle_count                    = (not supported)
/sys/class/power_supply/BAT1/energy_full_design             =  23200 [mWh]
/sys/class/power_supply/BAT1/energy_full                    =  20540 [mWh]
/sys/class/power_supply/BAT1/energy_now                     =  11980 [mWh]
/sys/class/power_supply/BAT1/power_now                      =  26500 [mW]
/sys/class/power_supply/BAT1/status                         = Charging

+++ Suggestions
* Install tp-smapi kernel modules for ThinkPad advanced battery functions

**Comment by linrunner** [comment]
Hi, i suspect the kernel fails to write the change. Please try to change the according sysfile by hand (in a root shell)

    echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

and then show
 
    tlp-stat -p

**Comment by duschendestroyer** [comment]
this does not change the output of tlp stat.
Calling "tlp ac" does change it to performance, however.



# echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
# tlp stat -p
--- TLP 0.7 --------------------------------------------

+++ Processor
CPU Model      = Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   500000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  2700000 [kHz]

/sys/devices/system/cpu/intel_pstate/min_perf_pct      = 18
/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100
/sys/devices/system/cpu/intel_pstate/no_turbo          = 1

x86_energy_perf_policy.cpu0                            = powersave
x86_energy_perf_policy.cpu1                            = powersave
x86_energy_perf_policy.cpu2                            = powersave
x86_energy_perf_policy.cpu3                            = powersave

/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.

**Comment by linrunner** [comment]
> this does not change the output of tlp stat. 
> Calling "tlp ac" does change it to performance, however.

Strange ...    Please show the full output of 

    tlp-stat

on **battery** and back on **ac** again. I suggest you use https://gist.github.com/ for the lengthy output.

**Comment by duschendestroyer** [comment]
Here are three outputs:
1. on battery
2. after plugging in ac adapter
3. after calling tlp ac

https://gist.github.com/duschendestroyer/fb4e35fcf60988027cc6

**Comment by niki-eng** [comment]
I have the same problem on Lenovo ThinkPad E540 with kernel 4.0.0-2-amd64.

**Comment by linrunner** [comment]
The outputs show that the automatic transition from ac to bat fails. Please give me a trace for that transition --> http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#support

**Comment by linrunner** [comment]
I also need (with AC plugged in)

    grep ".*" /sys/class/power_supply/*/{type,online,present}

**Comment by duschendestroyer** [comment]
% grep ".*" /sys/class/power_supply/*/{type,online,present}                                               
/sys/class/power_supply/AC/type:Mains
/sys/class/power_supply/BAT0/type:Battery
/sys/class/power_supply/BAT1/type:Battery
/sys/class/power_supply/AC/online:1
/sys/class/power_supply/BAT0/present:1
/sys/class/power_supply/BAT1/present:1

**Comment by duschendestroyer** [comment]
Jul 06 16:32:39 uljanov tlp[22726]: power_source=bat
Jul 06 16:32:44 uljanov tlp[22791]: +++ mode=stat -t (0.7) ++++++++++++++++++++++++++++++++++++++++
Jul 06 16:32:44 uljanov tlp[22792]: PATH=/home/dude/matlab/bin/:/opt/intel/bin/:/opt/intel/composerxe/bin/intel64:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/intel/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
Jul 06 16:32:44 uljanov tlp[22793]: power_source=bat
Jul 06 16:32:45 uljanov tlp[22830]: +++ mode=auto (0.7) ++++++++++++++++++++++++++++++++++++++++
Jul 06 16:32:45 uljanov tlp[22831]: PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
Jul 06 16:32:45 uljanov tlp[22832]: power_source=ac
Jul 06 16:32:47 uljanov tlp[22865]: +++ mode=stat -t (0.7) ++++++++++++++++++++++++++++++++++++++++
Jul 06 16:32:47 uljanov tlp[22866]: PATH=/home/dude/matlab/bin/:/opt/intel/bin/:/opt/intel/composerxe/bin/intel64:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/intel/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
Jul 06 16:32:47 uljanov tlp[22867]: power_source=ac

**Comment by linrunner** [comment]
I'm not yet sure what happens. I need the full trace, i.e. configured with `TLP_DEBUG="bat disk lock nm path pm rf run sysfs udev usb" 

Please: use  **tlp-stat -t**  *not*  tlp stat -t (the latter just clutters the trace).

Because of the duplicate #149 show traces for both power state transitions:

1. AC --> BAT
2. BAT --> AC

**Comment by duschendestroyer** [comment]
https://gist.github.com/duschendestroyer/4da4169c9807869fb7a5

I started with ac plugged in and unplugged (twice).
The trace doesn't show any more info despite adding the config line above.

**Comment by linrunner** [comment]
1. Does  `tlp auto`  work?
2. What is your default shell (/bin/sh)?

**Comment by duschendestroyer** [comment]
1. yes
2. zsh

**Comment by duschendestroyer** [comment]
1. yes
2. bash (as is default in archlinux)

**Comment by linrunner** [comment]
Summary so far:
* `tlp auto` called from udev executed by bash does not work
* `tlp auto` manually executed in a zsh works

**Comment by linrunner** [comment]
Please try to remove the sub shell in the auto section [1] in **/usr/bin/tlp**: 

    auto) # set mode depending on state (called by udev rule)
        check_root
        apply_common_settings $pwrmode
        [ "$pwrmode" = "1" ] && poweroff_drivebay 0
        set_radio_device_states $pwrmode
        ;;

[1] https://github.com/linrunner/TLP/blob/master/tlp#L140

**Comment by duschendestroyer** [comment]
this works :)

**Comment by linrunner** [comment]
OK, this was the easy part. The difficult part will be to find out why the subshell fails ... :(

**Comment by BLuFeNiX** [comment]
Hi, I have run the trace. It seems to be detecting the change:

    Jul 07 19:18:32 carbide tlp[5454]: +++ mode=auto (0.7) ++++++++++++++++++++++++++++++++++++++++
    Jul 07 19:18:32 carbide tlp[5455]: PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
    Jul 07 19:18:32 carbide tlp[5456]: power_source=bat
    Jul 07 19:18:35 carbide tlp[5501]: +++ mode=auto (0.7) ++++++++++++++++++++++++++++++++++++++++
    Jul 07 19:18:35 carbide tlp[5502]: PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
    Jul 07 19:18:35 carbide tlp[5503]: power_source=ac


But it doesn't actually change the CPU settings (governor, etc.), unless I run `tlp start` or `tlp auto`

**Comment by linrunner** [comment]
Arch: 0.7-3 with Patches is in the repositories now. 
Other distros: will get the fix with 0.8 (including Debian Sid).

**Comment by Delvien** [comment]
This issue exists in Fedora 28 as well.

**Comment by linrunner** [comment]
@Delvien : if you want support, please open your own issue and show proper tlp-stat outputs.
