### ISSUE TITLE
Headphone noise when tlp is active on Thinkpad T440s

### ISSUE THREAD

**Issue by Fingel** [linrunner/TLP#152]
Hi,
Just installed TLP from the PPA. Once the laptop is running on battery power, a horrendous static noise is emitted from headphones. Playing audio temporarily stops it, but it returns in a few seconds. It is loud and completely unbearable, so I had to remove TLP.
Any ideas what might cause this?

**Comment by linrunner** [comment]
Poor sound driver or hardware. Try to change your settings:

    SOUND_POWER_SAVE_ON_BAT=0

as suggested in the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#audio).

**Comment by Fingel** [comment]
Appears do have done the trick. Thank you.
