### ISSUE TITLE
T450s: battery stopThreshold not always respected

### ISSUE THREAD

**Issue by legovini** [linrunner/TLP#153]
On my T450s I set stopThreshold at 90% for BAT1, but I found out that it is not always respected. tlp-stat correctly shows:

```
tpacpi-bat.BAT1.startThreshold                              =     40 [%]
tpacpi-bat.BAT1.stopThreshold                               =     90 [%]
```

but for example right now I have the battery charged to 100% (actually 103% of its design full capacity). Sometimes it works, sometimes it doesn't, and at the moment I don't have a way to consistently reproduce the issue. I still have to understand if putting the laptop to sleep affects this (i.e., causes it to forget the thresholds), and of re-running tlp setcharge prevents the problem, even if the thresholds reported by tlpstat are always correct. I hope to be able to collect more information.

**Comment by linrunner** [comment]
Hi, your outputs prove that TLP works as designed writing the thresholds to the embedded controller (ec). I guess this is a malfunction of either the ec firmware or the hardware. Maybe a BIOS update can help.

I suggest you seek advice in a ThinkPad related forum.
