### ISSUE TITLE
 kernel Dazed and confused

### ISSUE THREAD

**Issue by rromoli** [linrunner/TLP#154]
Hi, after installing tlp in debian8 using the repos I get this warning at startup (post hibertation):

r@mb:~$ 
Message from syslogd@mb at Jul 29 10:19:07 ...
 kernel:[112500.999059] Uhhuh. NMI received for unknown reason 3c on CPU 0.

Message from syslogd@mb at Jul 29 10:19:07 ...
 kernel:[112500.999063] Do you have a strange power saving mode enabled?

Message from syslogd@mb at Jul 29 10:19:07 ...
 kernel:[112500.999065] Dazed and confused, but trying to continue

r@mb:~$

Whot should I do?

All the best Riccardo

**Comment by dywisor** [comment]
Same issue as #104
