### ISSUE TITLE
Erratic battery behaviour

### ISSUE THREAD

**Issue by hoplaahei** [linrunner/TLP#155]
My X230 is affected by the erratic battery bug listed in the FAQ. To prevent this bug from happening I have thresholds set as:

START_CHARGE_THRESH_BAT0=67
STOP_CHARGE_THRESH_BAT0=0

But this makes my battery charge to near full when I am on AC, which I have read is not good for battery life. Are there no workarounds with tpacpi-bat to keep it at a certain charge when plugged in on AC e.g., keep it at 67%, without causing the erratic battery behaviour? 

I noticed that unplugging, and replugging my AC will keep it at a certain charge as I want, but would this still cause the bug?  

Thanks for reading.

**Comment by linrunner** [comment]
Hi, this issue tracker is for TLP bugs only. Thanks for your understanding.
