### ISSUE TITLE
Screen flickering with Radeon card (dpm, connected with Issue #90, updating FAQ)

### ISSUE THREAD

**Issue by spankratov** [linrunner/TLP#164]
When I use TLP with two Radeon card the screen flicker in battery mode. Just like in [this issue](https://github.com/linrunner/TLP/issues/90), but the different thing is that I use newer version of kernel with DPM, so in my case changing
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery

to
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=performance

solved the problem. I just think that this situation must be considered in [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#graphics). Right now there's only a solution for older version of kernel (changing RADEON_POWER_PROFILE_ON_BAT).

**Comment by linrunner** [comment]
Done. Thanks for your hint.
