### ISSUE TITLE
Fedora 23

### ISSUE THREAD

**Issue by al09219** [linrunner/TLP#165]
Fedora 23 was released, I hope that the Thinkpads modules repo will be as soon as possible. Thank you for your work.

**Comment by dmaglio** [comment]
+1

**Comment by linrunner** [comment]
Hi,

F23 packages are in the testing repo now. Please install and give feedback:

     dnf install --enablerepo tlp-updates-testing akmod-tp_smapi akmod-acpi_call kernel-devel

Note: RPMFusion repo for F23 is needed as well.

**Comment by linrunner** [comment]
The packages are in the release repo now. You don't need the above mentioned switch `--enable-repo` anymore.
