### ISSUE TITLE
opensuse 42 on samsung notebook

### ISSUE THREAD

**Issue by Zverushko** [linrunner/TLP#168]
hi! 
a have samsung 530u3b-a04ru
i read 
"Note: there is no sustained source for tp-smapi and acpi-call packages for openSUSE at the moment, please restrain from opening issues for this."

this applies only to lenovo tinkpad?

on my notebook tlp will work right?

thx!

**Comment by linrunner** [comment]
Right. tp-smapi and acpi-call are needed for ThinkPads only.
