### ISSUE TITLE
Force discharge when not on AC

### ISSUE THREAD

**Issue by davidebasilio** [linrunner/TLP#171]
This is more a feature request than an issue.

Force discharge is only supported when on AC right now.
However, it is reported to work when off AC on older thinkpads (for example, a w520, see [1]).

Do you know if newer Thinkpads (I have a t450) actually can't do that or perhaps they might have a different interface?
Do you have any connections in Lenovo that might shed light on this?
Balancing discharge across the two batteries would definitely much better than draining one of the two first and it would be easy to manage in software if the controller supported this (which apparently was true on some earlier---but not so old---models).

Thanks for any hints -

[1] https://github.com/teleshoes/tpacpi-bat/issues/64

**Comment by linrunner** [comment]
I do not plan to implement battery balancing in TLP nor do i research in this field.

I'm not aware of even the slightest hint about Lenovo supporting Linux development. Which is a shame.

Sorry.
