### ISSUE TITLE
intel_pstate: Turbo disabled by BIOS or unavailable on processor

### ISSUE THREAD

**Issue by olologin** [linrunner/TLP#179]
I have i3-2310m processor, and it doesn't supports Intel Turbo Boost, but even if i disable it in config:

    CPU_BOOST_ON_AC=0
    CPU_BOOST_ON_BAT=0

Something is trying to enable it (?) and i see this message in dmesg output.

    intel_pstate: Turbo disabled by BIOS or unavailable on processor

Can i somehow disable these attempts to enable Turbo Boost?
I don't know, maybe it's not related to TLP, but seems that i can't google solution for this.

**Comment by linrunner** [comment]
Hi, 

comment out both config lines (with '#') and TLP won't touch turbo boost at all.

**Comment by olologin** [comment]
Hmm, but both are commented out already, and i don't see these lines in tlp stat output too.

   #CPU_BOOST_ON_AC=0
   #CPU_BOOST_ON_BAT=0

**Comment by linrunner** [comment]
That's right. If you comment out a config line, it does'nt show up in tlp-stat -c.

See the boost settings code here: https://github.com/linrunner/TLP/blob/master/tlp-functions.in#L649
