### ISSUE TITLE
Max Battery threshold on TP410 not honoured

### ISSUE THREAD

**Issue by kanehekili** [linrunner/TLP#182]
Hi,
I've been running TLP for many years, right now on a TP410 Core I7 with Xubuntu 14.04.
I was surprised to see my battery level up 100% (should be 92%)- can't see any mistakes:

sudo tlp-stat -b
--- TLP 0.8 --------------------------------------------

+++ ThinkPad Extended Battery Functions
tp-smapi   = active
tpacpi-bat = inactive (kernel module 'acpi_call' not installed)

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/devices/platform/smapi/BAT0/manufacturer               = SONY
/sys/devices/platform/smapi/BAT0/model                      = 42T4795
/sys/devices/platform/smapi/BAT0/manufacture_date           = 2010-03-21
/sys/devices/platform/smapi/BAT0/first_use_date             = 2010-07-13
/sys/devices/platform/smapi/BAT0/cycle_count                =     89
/sys/devices/platform/smapi/BAT0/design_capacity            =  50540 [mWh]
/sys/devices/platform/smapi/BAT0/last_full_capacity         =  49830 [mWh]
/sys/devices/platform/smapi/BAT0/remaining_capacity         =  49830 [mWh]
/sys/devices/platform/smapi/BAT0/remaining_percent          =    100 [%]
/sys/devices/platform/smapi/BAT0/remaining_running_time_now = not_discharging [min]
/sys/devices/platform/smapi/BAT0/remaining_charging_time    = not_charging [min]
/sys/devices/platform/smapi/BAT0/power_now                  =      0 [mW]
/sys/devices/platform/smapi/BAT0/power_avg                  =      0 [mW]
/sys/devices/platform/smapi/BAT0/state                      = idle

/sys/devices/platform/smapi/BAT0/start_charge_thresh        =     85 [%]
/sys/devices/platform/smapi/BAT0/stop_charge_thresh         =     92 [%]
/sys/devices/platform/smapi/BAT0/force_discharge            =      0

Any ideas where to look?
Regards kanehekili

**Comment by linrunner** [comment]
Hi, 

the output shows that the stop threshold was written correctly. A hardware fault is the only possible explanation for your symptom. Please seek advice in a ThinkPad hardware oriented forum.
