### ISSUE TITLE
USB Hard Disk autosuspend after unmount

### ISSUE THREAD

**Issue by FadeMind** [linrunner/TLP#184]
@linrunner Hello. I using TLP for on my laptop and all is great except one thing. After unmount external HDD USB device is not suspended and working for a long time. 
OS: ArchLinux x64
DE: KDE Plasma 5
TLP setup: https://pastebin.com/bJiKTGB6

**Comment by linrunner** [comment]
Hi, 

i'm not sure what you mean by "HDD ... suspend". Could you please explain?  TLP has no means to spin down USB HDDs.

**Comment by FadeMind** [comment]
@linrunner I looking solution for spin down the external drive disk before turning it off and unplugging it.

Just Safety removing USB drive disk in short.

**Comment by linrunner** [comment]
I'm sorry, you have to look elsewhere.
