### ISSUE TITLE
[feature request] Recognize BLK-MQ I/O scheduler

### ISSUE THREAD

**Issue by FadeMind** [linrunner/TLP#187]
Please add support for recognizing `blk-mq` scheduler in `tlp-stat`.

**How to find out it is set and used?**
1. It is enabled via custom GRUB flag `scsi_mod.use_blk_mq=1` (or hard in customized kernel config)
2. Sheduller is recognized as `none` in `cat /sys/block/*/queue/scheduler` command.
3.  In `/sys/block/` tree exists `/sys/block/sda/mq/` .
For example:

    $ sudo tree /sys/block/sda/mq/
    /sys/block/sda/mq/
    └── 0
        ├── active
        ├── cpu0
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu1
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu2
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu3
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu4
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu5
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu6
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu7
        │   ├── completed
        │   ├── dispatched
        │   ├── merged
        │   └── rq_list
        ├── cpu_list
        ├── dispatched
        ├── io_poll
        ├── pending
        ├── queued
        ├── run
        └── tags
    
    9 directories, 40 files

Note:  TLP recognize current `none` status only from `cat /sys/block/*/queue/scheduler`:

    +++ Storage Devices
    /dev/sda:
              Model     =                
              Firmware  =
              APM Level = 254
              Status    = active/idle
              TRIM      = supported
              Scheduler = none

@linrunner regards.

Tomasz

**Comment by linrunner** [comment]
Done. Thanks for the suggestion.
