### ISSUE TITLE
"/usr/sbin/tlp: 1: /etc/default/tlp: ﻿#: not found"

### ISSUE THREAD

**Issue by JacksonGoode** [linrunner/TLP#191]
Not sure if I saw this before I was tinkering around with the tlp file.
Is this an error I should be concerned with?
Also when I check the stats I get:
"
/usr/sbin/tlp: 1: /etc/default/tlp: ﻿#: not found
/usr/bin/tlp-stat: 1: /etc/default/tlp: ﻿#: not found
"

**Comment by dywisor** [comment]
My *guess* is non-printing chars in your config file, you can verify this with `cat -v /etc/default/tlp`.

Example code for a similar case:
``` shell
$ printf '\007%s\n' '# comment'
# comment

$ printf '\007%s\n' '# comment' | LANG=C dash
dash: 1: #: not found

$ printf '\007%s\n' '# comment' | cat -v
^G# comment
```
