### ISSUE TITLE
A question about grsec (+PaX) and importance of  x86_energy_perf_policy 

### ISSUE THREAD

**Issue by DamienGrand** [linrunner/TLP#195]
Hi! 
I'm planning to move to grsec
However, there's a compatibility issue - one of its hardening tricks (GRKERNSEC_KMEM) is incompatible with  writing to x86_energy_perf_policy

Per my understanding, tlp can sorta work without doing that, but... are there any downsides? Should I bother disabling grsec's GRKERNSEC_KMEM if I feel like some more battery is worth slightly decreased security ?

**Comment by linrunner** [comment]
I'm afraid you have to conduct your own measurements for your particular hardware.

Btw: you're wrong about "[TLP] *writing* to x86_energy_perf_policy". TLP [calls ](https://github.com/linrunner/TLP/blob/master/tlp-functions.in#L824) the tool x86_energy_perf_policy from the [kernel tree](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/tools/power/x86/x86_energy_perf_policy). I don't take complaints for that here ;-).
