### ISSUE TITLE
AHCI Runtime PM support

### ISSUE THREAD

**Issue by ArchangeGabriel** [linrunner/TLP#196]
Hi,

Linux 4.6 is around the corner, and come with a great news for PM: https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.6-AHCI-Runtime-PM.

TLP already supports SATA Runtime PM, so I think this shouldn’t be hard.

Thanks!

**Comment by linrunner** [comment]
Hi,

in fact it is already in  the works for 0.9. Unfortunately it's causing system lockups on *every* invocation on my machine (ThinkPad T450s w/ Samsung 850 Evo, Kernel 4.6rc5). So it won't be enabled by default and will have a big EXPERIMENTAL WARNING sticker attached.

I would be grateful if you could test as soon as i commit :-).

**Comment by ArchangeGabriel** [comment]
Sure, will let you know!

**Comment by linrunner** [comment]
Please test the feature WITH CARE on a non-production system: potential system freezes/data loss!

Arch Linux: packages tlp-git and tlp-rdw-git tracking the master branch are available via AUR.

**Comment by linrunner** [comment]
Released with 0.9.
