### ISSUE TITLE
Disk spinned up when laptop switched to battery

### ISSUE THREAD

**Issue by ssergiienko** [linrunner/TLP#200]
I'm not sure this could be controlled by TLP, but when I switch to battery mode HDD has spinned up and then spinned down after configured timeout.
Why this extra spin up happening? Is this a bug of TLP configuration? Or maybe this could be somehow handled/configured by TLP?

**Comment by linrunner** [comment]
Hi, i added an explanation to the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#spinup).

**Comment by ssergiienko** [comment]
Thanks! Looks like "keep" setting can help in my case.
