### ISSUE TITLE
homepage: AOSC OS is shipping TLP

### ISSUE THREAD

**Issue by MingcongBai** [linrunner/TLP#202]
As shown here... http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html.

There is no guideline for the formatting of issues like this, but I figure that this is an informational issue... so, please ask for any information needed. Sorry about that...

**Comment by linrunner** [comment]
Thanks for the information. The issue tracker is for *bug reports* only! For news like this just drop me an email please.

**Comment by MingcongBai** [comment]
Fair enough, thanks.
2016年5月9日 22:43，"linrunner" <notifications@github.com>写道：
