### ISSUE TITLE
[enhancement] SSD disk detection

### ISSUE THREAD

**Issue by mattia-b89** [linrunner/TLP#204]
I think is a good idea to detect if disk is traditional or SSD in order to better configure default settings

**Comment by linrunner** [comment]
What settings should be different for an SSD in your opinion?

**Comment by mattia-b89** [comment]
APM is not supported in SSD

**Comment by linrunner** [comment]
Wrong. There are SSDs that support APM (e.g. Crucial M4, see the FAQ) and the rest just ignores the setting. No need to complicate matters.

**Comment by mattia-b89** [comment]
ok
