### ISSUE TITLE
[enhancement] intel CPU governor

### ISSUE THREAD

**Issue by mattia-b89** [linrunner/TLP#205]
better explain the intel_pstate section, since default is `ondemand` but intel_pstate doesn't support it!

**Comment by linrunner** [comment]
Feel free to suggest a better text or send a pull request!

**Comment by mattia-b89** [comment]
A point is to add the official kernel page:
https://www.kernel.org/doc/Documentation/cpu-freq/intel-pstate.txt

**Comment by linrunner** [comment]
* default changed --> https://github.com/linrunner/TLP/commit/531b17e53888b66c0f650ccd2377c88102556f41
* Config page changed --> http://linrunner.de/en/tlp/docs/tlp-configuration.html#scaling
* tlp-stat -p: show available scaling govs  --> https://github.com/linrunner/TLP/commit/a6121c2e0a577e4c353d1b4b2404fde6712474bf

OK for you?

> A point is to add the official kernel page:
Is already linked on the config page.
