### ISSUE TITLE
[enhancement] extra disk scheduler

### ISSUE THREAD

**Issue by mattia-b89** [linrunner/TLP#206]
I use `BFQ` scheduler, so I put "_" as variable.
I think we should add an explanation in the `/etc/default/tlp` like:
"use _ if you want to keep the kernel's default scheduler
e.g. BFQ"

**Comment by linrunner** [comment]
It's in already in the [docs](http://linrunner.de/en/tlp/docs/tlp-configuration.html#ioscheduler), so no need to blow up the config file. 

Btw: you may as well write DISK_IOSCHED="bfq" ;-)

**Comment by linrunner** [comment]
Changed my mind. No 'keep' is explained in default. bfq got a mention in the [docs](http://linrunner.de/en/tlp/docs/tlp-configuration.html#ioscheduler).
