### ISSUE TITLE
Thresholds set after logoff

### ISSUE THREAD

**Issue by JacksonGoode** [linrunner/TLP#208]
This might be a feature and I am unaware. But when I logoff, before I return to the logon screen, black screen appears with command text to set the battery thresholds. I don't know if this could be potentially hidden.

**Comment by linrunner** [comment]
Hi, 

the impression is deceptive. TLP writes these messages to the text console during system startup. I have no idea why the display manager reveals them during logoff. This is not an issue with TLP.
