### ISSUE TITLE
setcharge STOP_THRESH and START_THRESH not working properly

### ISSUE THREAD

**Issue by ssmirr** [linrunner/TLP#212]
![image](https://cloud.githubusercontent.com/assets/9158546/15624161/b4234380-244e-11e6-8469-3486183f8b78.png)

`STOP_THRESH` and `START_THRESH` don't work properly as shown in the screenshot

Tested on Thinkpad E420, Ubuntu 16.04 LTS installed using Ubuntu official repository
Please let me know if more information is needed.

**Comment by linrunner** [comment]
Your command syntax is wrong. setcharge sets both thresholds at once. Use:

    sudo tlp setcharge 70 97

**Comment by ssmirr** [comment]
My bad, misunderstood the documentation. It worked. 
Thanks for the great tool @linrunner !
