### ISSUE TITLE
ThinkPad X1 Carbon (4th gen, 2016) - Missing tp_smapi kernel module

### ISSUE THREAD

**Issue by leodido** [linrunner/TLP#224]
I have followed your instructions at http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html, installing all the needed packages.

Nevertheless I'm obtaining the following output from `tlp-stat`.

```
+++ ThinkPad Extended Battery Functions
tp-smapi   = inactive (kernel module 'tp_smapi' not installed)
tpacpi-bat = active
```

Furthermore `modprobe -v` states that it does not find the module in the kernel modules' directory.

Any hint or suggest?

```
$ uname -a
$ Linux lltpx1c4 4.6.7-300.fc24.x86_64 #1 SMP Wed Aug 17 18:48:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by linrunner** [comment]
Hi, it doesn't matter, because the X1 Carbon 4th Gen. does not support tp-smapi anyway. You may uninstall the package.

Hint: TLP 0.9 (available in the F24 testing repo) will tell you exactly this, see the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#kernmod) for details.

**Comment by leodido** [comment]
Hi @linrunner, ok. Perfect.

And thanks for your wonderful piece of software.

**Comment by linrunner** [comment]
You're welcome.
