### ISSUE TITLE
public key doesn't work

### ISSUE THREAD

**Issue by bappobox** [linrunner/TLP#235]
Hi everybody,

Thankyou very much for your project.

I have a Lenovo Thinkpad yoga 12 with Linux Mint LMDE 2. 
I followed your instructions and I added the repository to the source.list but when I try to add the public key for the repository I receive this error:
# Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.Vbcp0H9k7b --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/deb-multimedia-keyring.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver pool.sks-keyservers.net --recv-keys 641EED65CD4E8809

gpg: requesting key CD4E8809 from hkp server pool.sks-keyservers.net
gpg: no writable keyring found: eof
gpg: error reading `[stream]': general error
gpg: Total number processed: 0

Did I make something wrong? I thankyou for any help.

Bappo

**Comment by linrunner** [comment]
There seems to be a problem with your apt keyring. Please ask for help in an LMDE or Debian specific forum.
