### ISSUE TITLE
Ubuntu 16.10 Installation Guidelines

### ISSUE THREAD

**Issue by orschiro** [linrunner/TLP#236]
Dear all, 

I took a look at the [installation guidelines](http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#installation) for Ubuntu.

Basically, what I want to achieve is running TLP with default settings on Ubuntu 16.10.

Thus I installed all the required packages. But what is not clear to me from the installation guideline, does TLP start automatically upon next boot or do I have to do something else besides installing the packages?

Thankfully,

-Robert

**Comment by linrunner** [comment]
Please don't open issues for things the [docs already explain](http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#start):

> **Start**
> TLP will start automatically. To avoid having to restart the system, the first time you can start it manually by using the following command:
> `sudo tlp start `

Thanks.
