### ISSUE TITLE
Bluetooth radio cannot detect visible bluetooth devices with TLP installed

### ISSUE THREAD

**Issue by mokalovesoulmate** [linrunner/TLP#239]
In my case this is a bluetooth mouse (Microsoft Sculpt Comfort).

Kernel version: Linux ThinkPad-E450 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

PC: Lenovo Thinkpad E450

### Symptom data

1. Does the problem occur on battery or AC or both?
Both.

2. Attach the *full* output of `tlp-stat` via [Gist](https://gist.github.com/) for *all* cases of 1.
https://gist.github.com/mokalovesoulmate/793c8db8a5df127bfa297dfa10465415

### Expected behavior
Bluetooth mouse still connected despite tlp activation

### Actual behavior
Computer no longer detect or connect to any of bluetooth devices visible

### Steps to reproduce the problem
1) Fresh ubuntu install (optional)
2) Connect bluetooth mouse
3) Install tlp (additional thinkpad is optional)
4) Activate tlp
sudo tlp start

...and boom, bluetooth mouse disconnected and bluetooth wont discover visible devices.

### Temporary fix
1) Uninstall (purge) tlp and tlp-rdw:
sudo apt-get remove --purge tlp tlp-rdw

2) Reinstall linux kernel:
sudo apt-get install --reinstall linux-image-$(uname -r)

3) Reboot computer.

**Comment by linrunner** [comment]
Hi,

try the workaround from the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#input).

**Comment by mokalovesoulmate** [comment]
It works! Thanks!

Note: sometimes bluetooth settings not working because "Bluetooth is disabled" but you can turn on, off, and on again.

**Comment by SaulEfrain** [comment]
Hello, the solution might be found here: http://linrunner.de/en/tlp/docs/tlp-faq.html  ...It worked for me.

Configure TLP:
USB_BLACKLIST_BTUSB=1
