### ISSUE TITLE
Audio power saving on battery shuts down laptop

### ISSUE THREAD

**Issue by Skeukry** [linrunner/TLP#240]
In any of the following cases my laptop shuts down ungracefully:
- run `sudo tlp bat`
- unplug power source
- boot without power source

I'm using a fresh install of Ubuntu 16.04.1

I've fixed it for myself by commenting out `SOUND_POWER_SAVE_ON_BAT`, just wanted to report it, so if anyone will have the same issue, they can solve it faster than I did. :smile: 

[my tlp-stat output](https://gist.github.com/Skeukry/422fabdd7d9218cc45ae697f5d1c4637)

**Comment by linrunner** [comment]
Thanks for your report, I added it to the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#shutdownonbat).

If you *really* want to help other users you should file a kernel bug!
