### ISSUE TITLE
acpi_call not installed in kernel

### ISSUE THREAD

**Issue by madgoks** [linrunner/TLP#241]
### Symptom data

1. The problem occurs on both AC as well as battery.
2. Output of tlp-stat on battery  and AC power is attached as two separate files.

[tlp_status_batt.txt](https://github.com/linrunner/TLP/files/671707/tlp_status_batt.txt)
[tlp_status_ac.txt](https://github.com/linrunner/TLP/files/671708/tlp_status_ac.txt)

### Expected behavior
After having installed akmod-acpi_call from the testing repo for Fedora 25,pacpi_bat should not show up as inactive. 

### Actual behavior
After having installed akmod-acpi_call from the testing repo for Fedora 25, it shows up as inactive. Also if one does a modprobe, it does not show up in the kernel modules.

`modprobe -v acpi_call`
_modprobe: FATAL: Module acpi_call not found in directory /lib/modules/4.8.14-300.fc25.x86_64_

### Steps to reproduce the problem
I followed all the installation steps given on the website but couldnt resolve the issue.

**Comment by adamczyk777** [comment]
Same issue here, happens for new kernel versions all the time

**Comment by ValdikSS** [comment]
acpi_call can't be compiled automatically since akmods build it with `-Werror`, which treats all warnings as errors.
```
  CC [M]  /tmp/akmodsbuild.PnJ18ZSt/BUILD/acpi_call-kmod-1.1.0/_kmod_build_4.12.9-200.fc25.x86_64/acpi_call.o
/tmp/akmodsbuild.PnJ18ZSt/BUILD/acpi_call-kmod-1.1.0/_kmod_build_4.12.9-200.fc25.x86_64/acpi_call.c: In function 'acpi_proc_write':
/tmp/akmodsbuild.PnJ18ZSt/BUILD/acpi_call-kmod-1.1.0/_kmod_build_4.12.9-200.fc25.x86_64/acpi_call.c:278:9: error: implicit declaration of function 
     if (copy_from_user( input, buff, len )) {
         ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

@linrunner can you update acpi_call in Fedora 25 repository please?

**Comment by ValdikSS** [comment]
@linrunner you need to add the following line into acpi_call.c:
`#include <linux/uaccess.h>`

**Comment by SiliconKite** [comment]
Same problem here, any solutions ? Thanks

**Comment by peculiarity** [comment]
Why was this issue closed? I still experience the following issue with Fedora 30
