### ISSUE TITLE
Configure bayoff on AC

### ISSUE THREAD

**Issue by toonn** [linrunner/TLP#243]
This is a feature request not a bug. I apologize if this isn't the appropriate place for this but there doesn't seem to be any other official forum or channel to talk about TLP.

I rarely use the optical disk drive so there's no point in having it switch between on and off every time I connect AC power. I'd like to be able to configure the ODD to always be off.

**Comment by linrunner** [comment]
Why don't you just put 

    tlp bayoff

in your *rc.local* (or similar)?

**Comment by toonn** [comment]
I don't like spreading around configuration like this. I'll forget if I ever remove tlp or do a reinstall of the system. Why is it restricted to battery mode in TLP in the first place? It'd be nice to have all the power related config in one place, the TLP configuration.

**Comment by linrunner** [comment]
Please show me the full output of 

    tlp-stat

via [Gist](http://gist.github.com/).

**Comment by toonn** [comment]
Here you go: https://gist.github.com/toonn/6a14b616b44431c0c728898639e220f1

**Comment by linrunner** [comment]
OK. I'll consider it for the next release.

**Comment by toonn** [comment]
Thank you. TLP is great btw.

**Comment by linrunner** [comment]
Done.

**Comment by toonn** [comment]
One more thing. Commenting here because I'm not sure whether it's an actual issue.
The ultrabay powers back on after suspending (at least when plugged in), is this a bug or is there no way around this?

**Comment by linrunner** [comment]
Your question is about the development version (master branch) or 0.9?

Expected behaviour is that the off state is preserved over the suspend/resume cycle. Make shure **tlp-sleep.service** is enabled (see [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#systemdunits)). `tlp-stat -s` will issue a warning if not.

**Comment by linrunner** [comment]
Please download shiny new packages for Debian/Ubuntu [here](http://download.linrunner.de/packages/), test your feature request and report back. Thank you.

**Comment by toonn** [comment]
Ok, I changed the config which now works as intended when on battery.
Then I installed 0.9.901, not the rdw package because I did not install that previously.
Do I need to add some configuration for this to work? On battery it still works as intended but after booting on ac the ultrabay stays on and after waking from suspend the ultrabay turns on if it was off.
Note that I am on ubuntu 15.10.

**Comment by linrunner** [comment]
For power off on ac you'll need **BAY_POWEROFF_ON_AC=1** of course. Refer to https://github.com/linrunner/TLP/blob/master/default#L169

I suggest you copy the config file from /etc/default/tlp.dpkg-dist to tlp and add your desired changes.

> Note that I am on ubuntu 15.10.

Sorry, i won't provide update packages for an EOL Ubuntu release via the PPA.

**Comment by toonn** [comment]
Ok, seems to work. Ultrabay turns off after boot and switches back on, then off after waking from suspend.
Thanks for this!

I am having some trouble with the laptop shutting down without warning when running out of battery though. I don't think this is because of the new version but I was wondering whether this could be because of TLP?
I'm guessing not but I don't know what else the problem could be. Could it be the battery misreporting it's charge?

**Comment by linrunner** [comment]
> and switches back on, then off after waking from suspend.

This must happen too when you connect the power supply in suspended state, even with BAY_POWEROFF_ON_AC=**0**.

**Comment by linrunner** [comment]
Released with 1.0.
