### ISSUE TITLE
Documentation for DESTDIR in Makefile

### ISSUE THREAD

**Issue by jkdf2** [linrunner/TLP#245]
Hi! The [Developer Documentation](http://linrunner.de/en/tlp/docs/tlp-developer-documentation.html) on the website is extremely helpful.

However, I am missing one point: how to build into my current directory to test without affecting my system. I looked in the Makefile and I see there is a `$(DESTDIR)` parameter. I found that the correct way to use this is `make install-tlp DESTDIR=built/` where `built/` is the directory in which I want to output the files. Could you provide a quick mention of how to use this in the documentation? It's a very helpful feature to make note of for development.

Thanks so much 😄

**Comment by linrunner** [comment]
Your command works fine here, even when the target directory doesn't exist. I suggest you show the actual output of it.

**Comment by jkdf2** [comment]
Sorry, I mean it does work, there's just no note of it in the Documentation.

**Comment by linrunner** [comment]
No anymore.

**Comment by linrunner** [comment]
ps. i didn't mention it explicitly based on the assumption that every OSS Makefile has it ;-)

**Comment by linrunner** [comment]
ps2. For my own testing workflow i never use a plain **make install**. Instead i always build a package. If you run Debian/Ubuntu it's quite simple to obtain the current package files:

    git checkout debian/current -- debian
    git rm -r --cached debian

then create the packages with

    dpkg-buildpackage -b

For other distros get the rpm specfile or PKGBUILD or whatever.
