### ISSUE TITLE
Clarification of Powertop + TLP

### ISSUE THREAD

**Issue by jkdf2** [linrunner/TLP#247]
The FAQ states:

---------
Powertop isn't a power management tool but merely an analysis tool. Any recommended settings you apply with powertop get lost upon the next system reboot. To make powertop's settings permanent you need a tool like TLP.

TLP's default configuration contains all appropriate powertop recommendations and implements them automatically.

---------

Unfortunately this can be interpreted in two different ways:

1. Powertop can be installed and TLP will use the analysis of powertop to implement better defaults. This would imply that powertop should be installed alongside TLP for better gains.

2. TLP does the best thing for your system regardless of whether or not powertop is installed. Thus installing powertop has absolutely zero benefit other than as a monitoring tool.

I *think* the correct interpretation is 2, in which case perhaps (something like) this would be more clear:

---------
Powertop has no impact on TLP's function. Powertop isn't a power management tool but merely an analysis tool. You can use powertop to view estimates about your power usage before or after installation of TLP, but TLP determines the best defaults for your system regardless of whether or not powertop is installed. Attempting to apply powertop's auto-tuning settings on each boot will only conflict with TLP.

---------

I love helping out on /r/debian with power-related questions (where there is a **lot** of recommendation for installing both powertop + TLP) but I want to be sure that the interaction between TLP and powertop is crystal clear both to me and to anyone I might link to the FAQ entry.

**Comment by linrunner** [comment]
[Done](http://linrunner.de/en/tlp/docs/tlp-faq.html#powertop). Thanks for your text.
