### ISSUE TITLE
need help with Debian/Ubuntu packaging?

### ISSUE THREAD

**Issue by leggewie** [linrunner/TLP#253]
I just noticed on http://download.linrunner.de/packages/ that you do not supply the latest release for trusty (which is what I still use).  As Debian Maintainer of a couple of packages I was wondering if you need a hand with the packaging.

**Comment by linrunner** [comment]
Hi,

which "latest release" do you mean? ;-)

I suggest you take a look at the [devel docs](http://linrunner.de/en/tlp/docs/tlp-developer-documentation.html#deb). I just added some notes how to build the package yourself.

If you want to help with the [Debian package](https://tracker.debian.org/pkg/tlp), feel free to contact Raphael, the maintainer.

**Comment by leggewie** [comment]
It's kind of funny to ask a question and close the ticket at the same time, don't you think?

Do you want an answer?

**Comment by linrunner** [comment]
Closing didn't stop you asking questions either. So go ahead with your answer.

Besides: i do funny things all the time – TLP being among them.
