### ISSUE TITLE
tp-smapi build fails on Ubuntu Xenial kernel 4.8.0-39-generic

### ISSUE THREAD

**Issue by longwuyuan** [linrunner/TLP#257]
### Symptom data

1. Does the problem occur on battery or AC or both? both
2. Attach the *full* output of `tlp-stat` via [Gist](https://gist.github.com/) for *all* cases of 1.

https://gist.github.com/longwuyuan/9650ed00029ebb7994be95369376345d

### Expected behavior

tp-smapi should build successfully
### Actual behavior

tp-smapi build fails
### Steps to reproduce the problem

step1 =  Install ubuntu 16.04.2
step2 = run the command "apt-get update"
step3 = run he command  "apt-get full-upgrade"
step4 =  reboot
step5 = run the command "uname -a" to check the kernel is 4.8.0.39-generic
step6 = install tlp by running the command "apt-get install tlp tlp-rdw tp-smapi-dkms acpi-call-dkms"
step7 = Check if the result is as seen below in /var/lib/dkms/tp-smapi/0.41/build/make.log;

DKMS make.log for tp-smapi-0.41 for kernel 4.8.0-39-generic (x86_64)
Mon Mar  6 07:58:40 CST 2017
make: Entering directory '/usr/src/linux-headers-4.8.0-39-generic'
  LD      /var/lib/dkms/tp-smapi/0.41/build/built-in.o
  CC [M]  /var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.o
In file included from ./include/linux/module.h:18:0,
                 from /var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c:33:
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c: In function ‘__check_force_io’:
./include/linux/moduleparam.h:344:67: error: return from incompatible pointer type [-Werror=incompatible-pointer-types]
  static inline type __always_unused *__check_##name(void) { return(p); }
                                                                   ^
./include/linux/moduleparam.h:396:35: note: in expansion of macro ‘__param_check’
 #define param_check_bool(name, p) __param_check(name, p, bool)
                                   ^
./include/linux/moduleparam.h:146:2: note: in expansion of macro ‘param_check_bool’
  param_check_##type(name, &(value));       \
  ^
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c:100:1: note: in expansion of macro ‘module_param_named’
 module_param_named(force_io, force_io, bool, 0600);
 ^
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c: In function ‘check_dmi_for_ec’:
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c:469:1: warning: the frame size of 1728 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
cc1: some warnings being treated as errors
scripts/Makefile.build:295: recipe for target '/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.o' failed
make[1]: *** [/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.o] Error 1
Makefile:1491: recipe for target '_module_/var/lib/dkms/tp-smapi/0.41/build' failed
make: *** [_module_/var/lib/dkms/tp-smapi/0.41/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.8.0-39-generic'

**Comment by linrunner** [comment]
Hi,

please read the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#tp-smapi-inst) or have a look at [previous issues](https://github.com/linrunner/TLP/issues?q=is%3Aissue+is%3Aclosed) before filing new issues. Thanks.

I recommend using the PPA, which – besides **tlp** 0.9 – provides **tp-smapi-dkms** 0.42-1 for your convenience.
