### ISSUE TITLE
tp_smapi lower threshold broken on XX20 series laptops

### ISSUE THREAD

**Issue by smclt30p** [linrunner/TLP#263]
The Renesas H8S firmware on the XX20 series ThinkPads uses different instructions to set and store battery lower charge threshold info. See: https://github.com/evgeni/tp_smapi/blob/master/README#L183-L184

**Comment by linrunner** [comment]
Hi,

install acpi-call(-dkms) and TLP auto-magically uses it to write charge thresholds.

See the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#kernmod) too.

**Comment by smclt30p** [comment]
That's neat. Is there any documentation on the ThinkPad ACPI interface for other implementations than TLP?

**Comment by linrunner** [comment]
I'm not aware of documentation of the ACPI interface itself. If you find one, don't forget to let me know.

If you just want to use battery features without TLP, see [tpacpi-bat](https://github.com/teleshoes/tpacpi-bat) (comes with TLP).
