### ISSUE TITLE
Make USB blacklist configurable by power source

### ISSUE THREAD

**Issue by tlvince** [linrunner/TLP#264]
Adding `*_ON_[AC|BAT]` conditions to `USB_BLACKLIST_*` would be nice to have. One use case would be to disable phone charging whilst on battery, but have it enabled on AC.

**Comment by linrunner** [comment]
Reconsidered and rejected.

**Comment by Konfekt** [comment]
TLP is installed by default in some distros (such as Gecko Linux).
Blacklisting phones would leave fewer unknowing users wondering why their phones are not charging.
Disabling charging when the laptop is on battery seems reasonable, but also while the laptop is connected to a power source less so.
