### ISSUE TITLE
wrong (?) reported battery capacity

### ISSUE THREAD

**Issue by herrdeh** [linrunner/TLP#269]
Not so much an issue report, more a request for help...
[Here's tlp-stat](https://gist.github.com/herrdeh/dab6d9dfb645b23df7b07a067d01985c)

My HP Elite Book 8440p is running on debian 8.6, GNOME. I bought a new battery, the manufacturer says it's capacity is 5200mAh. At the moment battery life is something like 75 min - not too bad, but hopefully the device can achieve more.

When now doing a tlp-stat -b, the result for the battery capacity first was something like 2200mAh. I tried to recalibrate the battery by letting the battery run empty. When the laptop reached 1% battery load left, it would turn off the screen, but not power down completely, so I did a hard poweroff after a while.

Nevertheless, after that procedure, the reported capacity rise to apx 2400 mAh, in the meanwhile (after several repeats) I'm at 2840 mAh, and it feels as if the battery life slightly improved.

Is there a quicker and more elegant way to teach the battery electronics it's actual capacity - than doing this "hard poweroff" repeatedly?

Cheers,
Wolf

**Comment by linrunner** [comment]
Sorry, this is far beyond the scope of TLP's issue tracker. 

I suggest you seek advice in a hardware oriented internet forum.
