### ISSUE TITLE
Process '/usr/bin/tlp auto' failed with exit code 4.

### ISSUE THREAD

**Issue by Bundy01** [linrunner/TLP#276]
Hi,

I 've this message in log. Do you have a solution.

Thanks :)

**Comment by linrunner** [comment]
This is not a bug. Exit code 4 means that more than one instance of tlp was invoked in parallel – which can happen during system startup or when the power source changes. Just ignore the message.

**Comment by Bundy01** [comment]
Ok,
Thanks

**Comment by Bundy01** [comment]
Sorry, 
one last question. 2.765 s tlp.service at boot time. Is this normal with a  Crucial MX200 SSD msata ?

**Comment by linrunner** [comment]
Text in [configuration](http://linrunner.de/en/tlp/docs/tlp-configuration.html#kernel) changed to "A value of 1 is relevant for kernel debugging **and the watchdog daemon**."
