### ISSUE TITLE
Booting from USB

### ISSUE THREAD

**Issue by bhack** [linrunner/TLP#279]
What is the effect of having USB autosuspend when you are booting from an usb disk?

**Comment by linrunner** [comment]
I'm sorry, but the issue tracker is for reporting bugs only. Please ask your question in an adequate Linux forum or Q&A site.

**Comment by bhack** [comment]
I mean if it makes sense to try to discover this for put it in the default blacklist like was done with keyboard and mouse

**Comment by linrunner** [comment]
No.
