### ISSUE TITLE
tlp-start makes battery worse?

### ISSUE THREAD

**Issue by SumNeuron** [linrunner/TLP#284]
I am running Ubuntu 16.04 LTS (GNOME flavor) and at the time of install had 73% battery with ~2 hours of battery life (I am using a Dell XPS 15 which has a very large 97 Wh battery). After installing TLP according to the install page - my battery indicator showed almost 6 hours! It was amazing. Then I ran `sudo tlp start` and I was down to 1.5 hours of battery. What happened?

### Symptom data

1. Does the problem occur on battery or AC or both?
2. Attach the *full* output of `tlp-stat` via https://gist.github.com/ for *all* cases of 1.

--- TLP 1.0 --------------------------------------------

+++ Battery Status
/sys/class/power_supply/BAT0/manufacturer                   = SMP
/sys/class/power_supply/BAT0/model_name                     = DELL GPM0365
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/charge_full_design             =   8509 [mAh]
/sys/class/power_supply/BAT0/charge_full                    =   7929 [mAh]
/sys/class/power_supply/BAT0/charge_now                     =   5901 [mAh]
/sys/class/power_supply/BAT0/current_now                    =   3967 [mA]
/sys/class/power_supply/BAT0/status                         = Charging

Charge                                                      =   74.4 [%]
Capacity                                                    =   93.2 [%]

**Comment by linrunner** [comment]
Hi, 

please provide the full output of

    tlp-stat

via https://gist.github.com/ (as stated in the issue template above). The part you consider relevant is not enough for an assessment.
