### ISSUE TITLE
akmod-acpi_call not available for Fedora 26

### ISSUE THREAD

**Issue by Roxxor91** [linrunner/TLP#286]
Hello!
Thank you for providing packages for Fedora! I see you already created the Fedora 26 repo over 2 weeks ago, but there are no packages. What is blocking akmod-acpi_call for Fedora 26?
I tried to build it myself, but failed to do it.
Thank you :)

**Comment by linrunner** [comment]
The maintainer provides new packages in "tlp-updates-testing". See the [instructions](http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#fedora).

**Comment by Roxxor91** [comment]
Oh. I am sorry that I missed that!
Installed it, rebooted and works!
Thank you!
