### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by HanaO00** [linrunner/TLP#293]
Hello, i see : 

ThinkPads only

For advanced battery functions, i.e. charge thresholds and recalibration, install the following package(s): 
tp_smapi – tp-smapi is needed for battery charge thresholds, recalibration and specific status output of tlp-stat
acpi_call – acpi-call is needed for battery charge thresholds and recalibration on Sandy Bridge and newer models (X220/T420, X230/T430 et al.)

So i need onlt tp_smapi, or only acpi_call, or the two ?

**Comment by linrunner** [comment]
Please check the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#kernmod) before opening issues and bear in mind that the issue tracker is **for bug reports only**. Visit a ThinkPad or Linux related forum for support questions. Thank you!
