### ISSUE TITLE
Flickering Display - Solved

### ISSUE THREAD

**Issue by BrendonIrwan** [linrunner/TLP#295]
### Symptom data

1. Does the problem occur on battery or AC or both? _Battery_
2. Attach the *full* output of `tlp-stat` via https://gist.github.com/ for *all* cases of 1.
[output](https://gist.github.com/BrendonIrwan/f926c4e190678acd811439a5e57e04e3)

### Expected behavior
Screen not to flicker...

### Actual behavior
Screen flickers at an inconsistent rate, though not that sporadic.

### Steps to reproduce the problem
RADEON configs does not solve the issue (no Radeon hardware installed here). Set:
`PCIE_ASPM_ON_BAT=performance`

Remarks: might want to add this to FAQ if similar problem occurs elsewhere. Also note the development build of my distro.

**Comment by linrunner** [comment]
Hi, thanks for your hint. I'll add a hint to the FAQ. 

Btw: why did you think a setting for AMD Radeon will help for Nvidia Optimus? ;-)

**Comment by BrendonIrwan** [comment]
At first I didn't know that the tweak was for Radeon hardware. But at least I tried and reported the result
=D

**Comment by BrendonIrwan** [comment]
This problem disappears in the release version of Ubuntu 17.10 with BIOS updates. Reverted setting:
`PCIE_ASPM_ON_BAT=powersave`

**Comment by linrunner** [comment]
FAQ changed.
