### ISSUE TITLE
deleting tlp-rdw

### ISSUE THREAD

**Issue by Zawadidone** [linrunner/TLP#299]
I deleted tlp-rdw and all the other packages but the tlp-rdw widget still shows up in my topbar

**Comment by linrunner** [comment]
Hi, I'm sorry but TLP doesn't contain a GUI or widgets. Maybe check the tutorial again, where you obtained that widget?

**Comment by Zawadidone** [comment]
Okay thanks for the reaction.I got it when in downloaded tlp-rdw. Here is a picture 
![screenshot from 2017-09-19 09-08-00](https://user-images.githubusercontent.com/21525407/30579776-59592bf4-9d1a-11e7-8e54-f7ae30143266.png)

**Comment by linrunner** [comment]
As stated above: this is not part of TLP and won't be supported here. Good luck.

**Comment by Zawadidone** [comment]
But can you help me ? It related to it please!
