### ISSUE TITLE
Battery charging to 100%, even after Threshold is set.

### ISSUE THREAD

**Issue by liam56514** [linrunner/TLP#300]
Hi,

I have some issues with the Threshold on a Lenovo T550. The issue is that the battery will charge to 100% even after the Threshold is set to 40 90 on both batteries. I have installed tpacpi-bat over tp-smapi but still can't get it to work. Restarting my laptop does not work, I have also discharged the battery and this still did not work.

tlp-stat - b below.

Thank you.

--- TLP 1.0 --------------------------------------------

+++ ThinkPad Battery Features
tp-smapi   = inactive (unsupported hardware)
tpacpi-bat = active

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/class/power_supply/BAT0/manufacturer                   = SANYO
/sys/class/power_supply/BAT0/model_name                     = 45N1741
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  44430 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  41170 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  38250 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Unknown (threshold effective)

tpacpi-bat.BAT0.startThreshold                              =     40 [%]
tpacpi-bat.BAT0.stopThreshold                               =     90 [%]
tpacpi-bat.BAT0.forceDischarge                              =      0

Charge                                                      =   92.9 [%]
Capacity                                                    =   92.7 [%]

+++ ThinkPad Battery Status: BAT1 (Ultrabay / Slice / Replaceable)
/sys/class/power_supply/BAT1/manufacturer                   = LGC
/sys/class/power_supply/BAT1/model_name                     = 45N1127
/sys/class/power_supply/BAT1/cycle_count                    = (not supported)
/sys/class/power_supply/BAT1/energy_full_design             =  23480 [mWh]
/sys/class/power_supply/BAT1/energy_full                    =  20990 [mWh]
/sys/class/power_supply/BAT1/energy_now                     =  20580 [mWh]
/sys/class/power_supply/BAT1/power_now                      =      0 [mW]
/sys/class/power_supply/BAT1/status                         = Unknown (threshold effective)

tpacpi-bat.BAT1.startThreshold                              =     40 [%]
tpacpi-bat.BAT1.stopThreshold                               =     90 [%]
tpacpi-bat.BAT1.forceDischarge                              =      0

Charge                                                      =   98.0 [%]
Capacity                                                    =   89.4 [%]

+++ Charge total                                            =   94.6 [%]

**Comment by linrunner** [comment]
Hi, your outputs prove that the thresholds are properly written to the hardware:

> tpacpi-bat = active
> tpacpi-bat.BAT0.startThreshold = 40 [%]
> tpacpi-bat.BAT0.stopThreshold = 90 [%]

So the problem is caused by your hardware.

I suggest you seek advice in Thinkpad oriented internet forum.
