### ISSUE TITLE
Bluetooth enabled automatically on versions >0.8

### ISSUE THREAD

**Issue by gitarra** [linrunner/TLP#303]
I have reproduced this issue with two laptops. A Thinkpad T61 with Xubuntu 16.04 and an X230 with Ubuntu 17.10.

I have bluetooth set to disabled but after installing TLP 1.0 bluetooth gets enabled automatically after a reboot or suspend.

On Xubuntu 16.04 I didn't have this issue with version 0.8, it only appeared after I upgraded to 1.0 through your PPA.

On Ubuntu 17.10 I didn't have this issue until I installed TLP 1.0 from your PPA.

**Comment by gitarra** [comment]
Correction: On Ubuntu 17.10 bluetooth gets enabled only after a reboot. On Xubuntu 16.04 also after suspend.

**Comment by linrunner** [comment]
Please show the full output of

    tlp-stat

via https://gist.github.com/ 

16.04: 
* After boot
* Before suspend (with manually disabled bluetooth) and after resume

17.10:
* After boot

**Comment by gitarra** [comment]
I was wrong, bluetooth is only enabled after a reboot on both systems, sorry about the noise.

Here are the outputs:

16.04: https://gist.github.com/gitarra/bebb066b701401c45b997a0320e28495

17.10: https://gist.github.com/gitarra/5114a61676acb7f3b9ef48741e4c31b8

**Comment by linrunner** [comment]
Both of your active configurations do not contain the required line

   DEVICES_TO_DISABLE_ON_STARTUP="bluetooth" 

Maybe you didn't keep your original config file when upgrading the package to the PPA version.

**Comment by gitarra** [comment]
I am using the default configuration on both systems. I have not done any modifications.

**Comment by gitarra** [comment]
Is TLP supposed to enable bluetooth on every boot by default?

Ubuntu without TLP remembers the bluetooth state and keeps it disabled so I do not expect it to be enabled on boot.

Xubuntus blueman applet also has a setting to disable bluetooth on startup which worked fine until upgrading from 0.8 in the official repos to 1.0 in your PPA.

**Comment by linrunner** [comment]
Default configuration leaves radio states – including bluetooth – untouched in any version of TLP. No change between 0.8 and 1.0.

**Comment by linrunner** [comment]
> Ubuntu without TLP remembers the bluetooth state and keeps it disabled so I do not expect it to be enabled on boot.
Package tlp disables Ubuntu's state remembering by masking systemd-rfkill.service. But this wasn't changed between 0.8 and 1.0. The default with TLP installed has always been (from version 0.2) that bluetooth is not touched by TLP but enabled by the kernel upon system start.

**Comment by gitarra** [comment]
Interesting. Doesn't that mean TLP overrides OS settings and effectively enables bluetooth by default? Unless one manually edits the TLP config.

I didn't have this issue with Xubuntu 16.04 when I used 0.8 from the official Ubuntu repo's. I had bluetooth "auto power on" disabled from blueman applet and bluetooth was correctly disabled on boot. That stopped working only after I upgraded to 1.0 from your PPA.

So to understand correctly:

In any case, one must manually edit the tlp config and add that line to disable bluetooth on startup, as otherwise TLP overrides the users OS settings.

**Comment by linrunner** [comment]
Just the opposite: "the OS" does the following upon system start
* Kernel enables bluetooth 
* Some userspace tools (blueman) enable or disable bluetooth

TLP with default config does not touch (= not override) bluetooth state set by "the OS". You have to edit config for TLP to change (disable) bluetooth state. Same behaviour applies to any version of TLP (including wifi, wwan).

**Comment by gitarra** [comment]
It would be nice if it was stated in the documentation that one must manually disable bluetooth in the config after installing TLP.

As a user I do not expect bluetooth to be enabled by default after installing TLP, as Ubuntu already has bluetooth disabled by default, and TLP is supposed to save battery.

I guess this can be closed.
