### ISSUE TITLE
[Solved] Disable Bluetooth on System boot

### ISSUE THREAD

**Issue by ralpheeee88** [linrunner/TLP#309]
### Symptom data
am trying to disable Bluetooth on system boot. I always have to manually switch it off `systemctl stop bluetooth.services`.

[http://ix.io/CM6](url)

1. Does the problem occur on battery or AC or both?
have only tested on AC power
2. Attach the *full* output of `tlp-stat` via https://gist.github.com/ for *all* cases of 1.

**Comment by linrunner** [comment]
Hi,

support is not possible without the required outputs. Your link doesn't work. Use https://gist.github.com/ please.

**Comment by ralpheeee88** [comment]
thxs for your help!
https://gist.github.com/ralpheeee88/31cb2fe8ae853f208028fb7efb938e7e

**Comment by linrunner** [comment]
I'm still missing the tlp-stat ouput.

**Comment by ralpheeee88** [comment]
@linrunner am really sorry...i have amended the file

not sure if i should ask here or in a new case regarding the suggestions / warnings

**Comment by linrunner** [comment]
You configured TLP correctly to disable bluetooth upon boot. So probably your desktop environment's bluetooth applet – or some other part of Arch Linux – re-enables  BT after TLP disabled it. I suggest you ask for advice in the Arch Linux forum.

Suggestions/warnings: the issue tracker is for bug reports against TLP only, it is _not_ intended as a support forum or to give general advice.  

Please check the docs ([installation instructions](http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#arch), [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#warnings)). You may ask in the Arch Linux forum as well.
