### ISSUE TITLE
What does TLP stand for?

### ISSUE THREAD

**Issue by meme-lord** [linrunner/TLP#318]
It's not in any documentation, description or anything I could find.
I've seen the other issue: https://github.com/linrunner/TLP/issues/291
But it's really bothering me.
If it doesn't stand for something can you at least leave this issue open until you or someone else makes up one that's acceptable.

**Comment by linrunner** [comment]
Question was answered already. Stop abusing the issue tracker.

**Comment by dariota** [comment]
I think one of your comments on this or #291 must not be showing up for me - I don't see any answer to the actual question.
