### ISSUE TITLE
TLP nightmare after I installed without knowing about it

### ISSUE THREAD

**Issue by PeterWalker14** [linrunner/TLP#328]
I am new to Ubuntu. I installed alongside Windows 10 and installed TLP by following the official website guide. But, I tried a few commands shown in that linrunner site, such as

sudo tlp status
sudo tlp bat

without knowing exactly what they do... Now my laptop battery stops charging at 97% and functions only on AC power (laptop gets off if I unplug the charger). I need those adapter cables to turn on the laptop and to do work on it.

To overcome this I uninstalled TLP, but nothing happens then to check I uninstalled and reinstalled Ubuntu, but I still the problem exist.

What should I do

**Comment by linrunner** [comment]
Good morning,

replace your battery. From your symptoms – charging stopped prematurely, functions on AC only – I guess it just died. This is a hardware issue and not related to TLP.

Please seek advice in a hardware oriented forum, the issue tracker is about bugs in TLP only. Thanks for you understanding.
