### ISSUE TITLE
Not able to set charge thresholds in T470 fedora 27

### ISSUE THREAD

**Issue by AkshayIyer12** [linrunner/TLP#329]
### Symptom data

1. Does the problem occur on battery or AC or both? both
2. Attach the *full* output of `tlp-stat` via https://gist.github.com/ for *all* cases of 1.
https://gist.github.com/AkshayIyer12/420db34f59b5798a52f89fd4909f6d3b

It says ```Error: ThinkPad battery features not available.```

**Comment by linrunner** [comment]
The necessary kernel module cannot be loaded:

> tpacpi-bat = inactive (kernel module 'acpi_call' load error)

Try to load the module by hand and check the error messages. Power off and reboot. Check again.

Eventually uninstall and reinstall **akmod-acpi_call**, check the messages and the build log.

**Comment by theLastOfCats** [comment]
I think problem is in Linux kernel, especially in kernel modules. There are no `akmod-acpi_call` kernel module for Linux v4.15.10 and newer
