### ISSUE TITLE
Laptop charges to 98..99% only

### ISSUE THREAD

**Issue by tndgu** [linrunner/TLP#336]
### Symptom data

I never reach the %100. Only If I don't use it. Rather than it stays at %100, it roams around %99 or %98 which means the laptop only uses the batter for energy and cable is charging. How can I setup tlp so it will use the charger after %100 rather than damaging my batter? Thanks guys.

**Comment by linrunner** [comment]
In fact you can't. This is a hardware issue, some batteries show this weird behaviour.

Please ask in a hardware oriented internet forum. TLP's issue tracker is for bug reports only, not for general advice. Thanks for your understanding.
