### ISSUE TITLE
Integrate modern PHC undervolting alternative

### ISSUE THREAD

**Issue by tbart** [linrunner/TLP#337]
PHC works nicely for older CPUs. However, "Core i" processors need a different approach.

Using https://github.com/xdever/linux-intel-undervolt-tool I am able to reduce vcore by 100mV which is a lot as it's only at 600mV without undervolting. That gives my 300MHz more of sustained CPU frequency under load (as thermal throttling kicks in) or saves a little power (as P=U²/R this should be around 30% in my case!)

Maybe this undervolting scheme can be included in TLP as the successor to PHC, or at least be mentioned somewhere (in the man page/help/config comments).

Thanks for providing this great tool!

**Comment by linrunner** [comment]
I do not plan to integrate third party undervolting tools.
