### ISSUE TITLE
TLP OpenSuse 12.3 support

### ISSUE THREAD

**Issue by aelgali** [linrunner/TLP#34]
It seems like there is no repository for tlp in opensuse 12.3.

**Comment by linrunner** [comment]
TLP is in openSUSE Tumbleweed now. Package will proceed into regular releases hopefully.

**Comment by linrunner** [comment]
TLP 0.8 has arrived in OpenSUSE 42. Packages for older releases are available via [Build Service](https://build.opensuse.org/package/show/hardware/tlp).
