### ISSUE TITLE
Please restore the battery parameter

### ISSUE THREAD

**Issue by gudata** [linrunner/TLP#346]
### Symptom data

1. Does the problem occur on battery or AC or both? only when I want to switch to battery mode
2. Attach the *full* output of `tlp-stat` via https://gist.github.com/ for *all* cases of 1.

https://gist.github.com/gudata/2e770318692acb74b6f96f576e531d6c

### Expected behavior
To be able to switch to battery mode when I type 

```
tlp battery
```

### Actual behavior

```
tlp battery
Error: unknown command "battery".
Usage: tlp start|true|bat|false|ac|usb|bayoff|discharge|setcharge|fullcharge|recalibrate|stat|diskid
```

### Steps to reproduce the problem
```
tlp battery
```

**Comment by linrunner** [comment]
I'm sorry, but there has never been a parameter `battery`.
