### ISSUE TITLE
is TLP still stuck when want to shutdown our Laptop

### ISSUE THREAD

**Issue by aharoldk** [linrunner/TLP#348]
hello,
i ever use TLP but i uninstall it because its stuck when shutdown laptop.
is TLP still stuck when want to shutdown our Laptop?

**Comment by linrunner** [comment]
Hi,

there's a hint in the [FAQ](http://linrunner.de/en/tlp/docs/tlp-faq.html#system). If it doesn't help please use the [troubleshooting guide](http://linrunner.de/en/tlp/docs/tlp-troubleshooting.html).

**Comment by aharoldk** [comment]
okey, i will try it

thx

**Comment by linrunner** [comment]
Please report when your problem is solved.
