### ISSUE TITLE
Surprisingly long boot time

### ISSUE THREAD

**Issue by sylph1o** [linrunner/TLP#352]
First of all, thanks for this great piece of software. That's one of my no-brainer program that is part of every laptop installation. The following issue is not a critical one, I will simply be thankful for any time you can spare me.

### Symptom data

I find my boot time has become significantly longer, even though I could not say when this changed. Running `systemd-analyze blame` reveals that `tlp.service` is the longest to boot by very far. Although it is not a serious inconvenience, I wonder whether something is wrong (maybe failing).

Here are the outputs of `tlp-stat` and `systemd-analyze blame`: https://gist.github.com/sylph1o/d972ded4c7b6e221254f6f9e813a91b2

Some additional details on my setup:
- Lenovo ThinkPad T460 (Intel i7-6600U);
- Arch Linux (kernel 4.16.13-2-ARCH);
- GDM with Gnome 3.28.2;
- LUKS on LVM.

### Expected behavior

I would expect tlp.service to boot in two or three secondes at most.
My searches have evinced many outputs of `systemd-analyze blame` featuring `tlp.service`, each of which was below 2s. I think I recall it booted in less than a second when I first installed it.

### Actual behavior

`tlp.service` boots in more than 16s, roughly 90 % of my userspace boot time.

### Steps to reproduce the problem

It happens at every boot, whether I am on AC or battery. I set `USB_AUTOSUSPEND=0` after reading #35, but it made no difference.

Any help would be greatly appreciated.

**Comment by linrunner** [comment]
tlp.service is started after the desktop, so it's not really relevant in your case.

I suggest to use the [troubleshooting guide](https://linrunner.de/en/tlp/docs/tlp-troubleshooting.html) to identify the offending setting or device.

**Comment by sylph1o** [comment]
You are right, as a simple test proved: disabling tlp has no effect on the boot time. I should have done that test before creating an issue. It seems that `systemd-analyze blame` was not the right diagnostic tool.

Thank you for your help. We can close the issue.
