### ISSUE TITLE
Describe behavior of default parameters in config

### ISSUE THREAD

**Issue by SammysHP** [linrunner/TLP#353]
Many configuration options in `/etc/default/tlp` are commented out by default. For most options there is no description of the default behavior of commented out options. Some of them use a fallback, so they actually change the system state (e.g. `RUNTIME_PM_DRIVER_BLACKLIST`). Other options simply do nothing and keep the current system value (e.g. `CPU_MIN_PERF_ON_AC`).

Each option should contain a short *default:* line which describes the behavior if the option is commented out.

**Comment by linrunner** [comment]
Done. Please review.

**Comment by SammysHP** [comment]
Looks fine to me.

**Comment by linrunner** [comment]
Thanks.

**Comment by linrunner** [comment]
Released with TLP 1.2.
