### ISSUE TITLE
tlp block shutdown and reboot on ubuntu 18.04

### ISSUE THREAD

**Issue by alexisaeff** [linrunner/TLP#354]
After installing tlp cannot reboot and shutdown.
System freeze on "starting reboot".
![photo_2018-07-13_18-18-28](https://user-images.githubusercontent.com/20814592/42699818-8b721c46-86ca-11e8-8d97-d757ff889958.jpg)

**Comment by linrunner** [comment]
[Necessary outputs](https://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#support) are missing. 

You may try to isolate the offending setting with the help of the [troubleshooting guide](https://linrunner.de/en/tlp/docs/tlp-troubleshooting.html).

**Comment by linrunner** [comment]
I forgot to mention the [FAQ section](https://linrunner.de/en/tlp/docs/tlp-faq.html#system).
