### ISSUE TITLE
Elogind compatibility [remove pm-utils refs]

### ISSUE THREAD

**Issue by divoxx** [linrunner/TLP#363]
I apologize in advance if this is not the correct channel for this kind of discussion.

On systems using `elogind` (without systemd), `pm-utils` is not used and AFAIK can actually cause conflicts. Would it be possible to run `tlp` without either `pm-utils` and `systemd`? Does `elogind` provide replacement features for `pm-utils` in the context of TLP?

Thanks

**Comment by linrunner** [comment]
Hi,

short answer: 

TLP's dependencies are defined in the package for your distribution, you should ask there.

Long answer: 

pm-utils is deprecated for years and no current distribution should require it. TLP doesn't require it.

TLP needs udevd for detecting events like change of power source and an init system such as sysvrc, openrc or systemd to handle startup/shutdown and suspend/resume stuff. See [dev docs](https://linrunner.de/en/tlp/docs/tlp-developer-documentation.html#architecture) for details. Again: your distribution's package maintainer does the plumbing work here.

elogind is a user session manager and TLP does not interact with it.

I take your question as a hint to remove all pm-utils refs from TLP and the documentation.

**Comment by divoxx** [comment]
Ok, that make more sense. 

Does TLP require specific configuration to work with openrc + udev or does it get automatically detected?

**Comment by linrunner** [comment]
Please look into the dev docs.
