### ISSUE TITLE
Provide build for Fedora 29

### ISSUE THREAD

**Issue by rbu** [linrunner/TLP#370]
The F29 repository at http://repo.linrunner.de/fedora/tlp/repos/releases/29/ (and the accompanying testing repositories) are empty. Would it be possible to provide RPMs?

Additionally, I was looking for the F28 SRPMS and failed to find them (last SRPMs seem to be for F27 at http://repo.linrunner.de/fedora/tlp/repos/releases/27/sources/SRPMS/).

**Comment by linrunner** [comment]
Hi, the maintainer told me everything is available now (for F29). Please check again.

**Comment by rbu** [comment]
Indeed, thanks to you and the maintainer.
