### ISSUE TITLE
Add Ubuntu 18.10 Cosmic to PPA

### ISSUE THREAD

**Issue by github-t** [linrunner/TLP#371]
When doing a sudo apt update I get the following error:

E: The repository 'http://ppa.launchpad.net/linrunner/tlp/ubuntu cosmic Release' does not have a Release file.

Assuming that TLP is supported on Cosmic, please add this to the PPA.

**Comment by diaper151** [comment]
Same problem right here, please add this to the PPA. Thanks~

**Comment by linrunner** [comment]
Hi, 

the newest version of TLP (1.1) is already in the Ubuntu Cosmic repo (universe). 

What else would you like to achieve with the PPA?

**Comment by diaper151** [comment]
@github-t  Just do sudo apt-get install tlp. Thanks @linrunner

**Comment by linrunner** [comment]
I have now created an empty release file, so that nobody will stumble over it anymore.
