### ISSUE TITLE
Power Governor management and downvolting

### ISSUE THREAD

**Issue by Limbo3** [linrunner/TLP#373]
Hey guys.

This is probably a feature request, 

In two words, I've found [this utility ](https://software.intel.com/en-us/articles/intel-power-governor) which can manage power consumption (RAPL) with MSR. It was made for server platforms, but adding CPI ID in rapl.c allows me to launch it on my laptop and it woks. 

Another cool feature is [downvolting](https://github.com/georgewhewell/undervolt), it also use MSRs

It would be awesome if you could add such functionality in TLP.

**Comment by linrunner** [comment]
CPU_MAX_PERF_ON_AC/BAT limits power consumption quite effectively. I see no benefit for laptop users from the utility you suggested.

Downvolting: a separate tool is just fine for the few users demanding this.
