### ISSUE TITLE
tpacpi-bat > inactive > unsupported hardware

### ISSUE THREAD

**Issue by maxLinux1960** [linrunner/TLP#374]
Title: tpacpi-bat > inactive > unsopported hardware

I have Thinkpad X201 3680, with Ubuntu 18.04 - 64 bit.

with command:

sudo tlp-stat -b

I receive:

**TPACPI-BAT = INACTIVE (UNSUPPORTED HARDWARE)**
............
--- TLP 1.1 --------------------------------------------

+++ ThinkPad Battery Features
tp-smapi   = active
tpacpi-bat = inactive (unsupported hardware)

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/devices/platform/smapi/BAT0/manufacturer               = SANYO
/sys/devices/platform/smapi/BAT0/model                      = 42T4694
/sys/devices/platform/smapi/BAT0/manufacture_date           = 2011-01-29
/sys/devices/platform/smapi/BAT0/first_use_date             = 2011-04-13
/sys/devices/platform/smapi/BAT0/cycle_count                =    422
/sys/devices/platform/smapi/BAT0/temperature                =     28 [Â°C]
/sys/devices/platform/smapi/BAT0/design_capacity            =  86580 [mWh]
/sys/devices/platform/smapi/BAT0/last_full_capacity         =  22990 [mWh]
/sys/devices/platform/smapi/BAT0/remaining_capacity         =  21510 [mWh]
/sys/devices/platform/smapi/BAT0/remaining_percent          =     94 [%]
/sys/devices/platform/smapi/BAT0/remaining_running_time_now = not_discharging [min]
/sys/devices/platform/smapi/BAT0/remaining_charging_time    =     10 [min]
/sys/devices/platform/smapi/BAT0/power_now                  =   5390 [mW]
/sys/devices/platform/smapi/BAT0/power_avg                  =   5352 [mW]
/sys/devices/platform/smapi/BAT0/state                      = charging

/sys/devices/platform/smapi/BAT0/start_charge_thresh        =     96 [%]
/sys/devices/platform/smapi/BAT0/stop_charge_thresh         =    100 [%]
/sys/devices/platform/smapi/BAT0/force_discharge            =      0

Charge                                                      =   93.6 [%]
Capacity                                                    =   26.6 [%]

===============

I don't understand my HW is not supported by TLP software.

Thanks

**Comment by linrunner** [comment]
You may safely ignore that message. It's about the method TLP uses to access your ThinkPad's battery features. You hardware is fully supported by the tp-smapi method, no need for tpacpi-bat. See the [FAQ](https://linrunner.de/en/tlp/docs/tlp-faq.html#battery) about the subject.

**Note:** the issue tracker is for bug reports only. For mere support questions please ask for advice in a Linux or ThinkPad oriented forum. Thanks for your understanding.
