### ISSUE TITLE
Feature Request: Add support to disable wireless device if not connected for some time

### ISSUE THREAD

**Issue by jdorel** [linrunner/TLP#377]
Would it be possible to disable a wireless device if it has seen no connections for more than X minutes ?

**Comment by linrunner** [comment]
Hi, 

I don't have the slightest idea how to implement this. Any suggestions from your side? A serious obstacle is how to seamlessly re-enable the device when a connection is requested. 

Actually wireless power management is quite good at reducing power consumption during periods without communication. I don't see any improvement here from your feature.
