### ISSUE TITLE
Feature Request: Add script trigger when on battery mode

### ISSUE THREAD

**Issue by jJit0** [linrunner/TLP#378]
This feature is very useful when tlp is working on battery mode.

Can you a script that triggers when I unplug mu AC, for example: when I unplug my AC adapter, the script and/or command "powertop --auto-tune"  triggers automatically

This feature already exists in laptop-mode-tools, maybe it needs to be added to TLP

**Comment by linrunner** [comment]
I won't implement hooks for arbitrary user scripts for support reasons.

Your example shows why: `powertop --autotune` will overwrite all settings TLP just applied for the new power source. It's complete nonsense to use TLP and `powertop  --autotune` together. 

Have a look a the [FAQ](https://linrunner.de/en/tlp/docs/tlp-faq.html#powertop) please.
