### ISSUE TITLE
[TLP 1.2 Beta] Call for testers

### ISSUE THREAD

**Issue by bogdanr** [linrunner/TLP#380]
It would be nice to tag TLP 1.2 because distros often know when to update a piece of software based on the version.

**Comment by linrunner** [comment]
It's not ready yet. Thanks for your patience.

**Comment by bubbleguuum** [comment]
Anything particular that is blocking to release 1.2 ? It's been one year 1.1 has been released now and distros will no pick anything else than an official release.

**Comment by linrunner** [comment]
Good morning guys, 

you've asked, so it's about time for you to help finish the release.

Fresh beta packages are available [here](https://download.linrunner.de/packages/) (or use the master branch). Please refer to the [changelog](https://github.com/linrunner/TLP/blob/master/changelog) und [dev docs](https://linrunner.de/en/tlp/docs/tlp-developer-documentation.html) too.

I'm expecting your outputs of

    sudo tlp-stat

on **battery and AC** (via https://gist.github.com/ please). Go ahead!

**Comment by bubbleguuum** [comment]
Thanks, will test and report.

**Comment by linrunner** [comment]
You're welcome to recruit more testers from your environment.

**Comment by bubbleguuum** [comment]
Here's some very initial results testing on my ThinkPad P72 running openSUSE Tumbleweed, kernel 4.20.10, using stock tlp config, both tlp.service and tlp-sleep.service started.

TLP installed from master using make install with proper parameter for openSUSE (looked at current RPM package .spec to make sure I had these correct).

- 'tlp-rdw on|off' works 
- 'tlp setcharge' (natacpi) works. Battery was 77% and range was 75-80. Changing it to
80-90 made the battery start charging
- 'tlp-stat -d' lists NVMe drive as expected
- suspend-to-RAM works 100% fine (it did previously)

tlp-stat output on AC: https://gist.github.com/bubbleguuum/c8f9198a834dc6a8d07a63b8bbadf3d8
tlp-stat output on BAT: https://gist.github.com/bubbleguuum/206c363b308dfccad83005d4c3edb9f7

**Comment by linrunner** [comment]
@bubbleguuum :  great, thanks. If you have the possibility to provide RPMs, I would be happy to make them available.

**Comment by bubbleguuum** [comment]
I will see but no promise as I'm not super familiar with rpm building and it's not entirely trivial.

What about making a post on /r/archlinux for a call to beta testers ? I'm certain a lot of folks there would be happy to test!

**Comment by linrunner** [comment]
No objection, but I don't have the technical expertise nor the time do support in many forums. You're aware of someone who could handle this for /r/archlinux?

**Comment by bubbleguuum** [comment]
I can (with your permission) make a post on /r/archlinux about the beta test, directing users to this issue.

**Comment by linrunner** [comment]
OK, let's try that.

**Comment by njoyard** [comment]
Test results on Arch on a Thinkpad x270, with possibly some config remaining from 1.1 (gist contains 2 files, output from AC and from BAT): https://gist.github.com/njoyard/622fddca13d417e62865a2db740cec21

**Comment by linrunner** [comment]
[Thread on Reddit /r/archlinux](https://www.reddit.com/r/archlinux/comments/avtsvw/tlp_12_linux_advanced_power_management_is_in_beta/)

**Comment by pablostebler** [comment]
Results on my Latitude E7470 on Arch Linux: [AC](https://gist.github.com/pablostebler/3deae32c33fba2ab2ddde1ca57c6a846), [battery](https://gist.github.com/pablostebler/95e60cd6cb4c426b80adb4cc1a4d1643).

**Comment by zauster** [comment]
> Fresh beta packages are available [here](https://download.linrunner.de/packages/) (or use the master branch). Please refer to the [changelog](https://github.com/linrunner/TLP/blob/master/changelog) und [dev docs](https://linrunner.de/en/tlp/docs/tlp-developer-documentation.html) too.
> 

The Arch AUR packages seem to be a few years out-of-date, last updated in 2016...

**Comment by linrunner** [comment]
@zauster: right, but: the referenced AUR packages install the master branch.

**Comment by zauster** [comment]
Yeah, I realized when reading the PKGBUILDs... 
Here are my results: [AC](https://gist.github.com/zauster/a09f6900b9b029e0c6b6891a36a51d3e), [Battery](https://gist.github.com/zauster/50a9e7bfea98b115d707a007d6ce5234)

**Comment by linrunner** [comment]
Thanks @all for your feedback.

@zauster : enabling tlp.service and tlp-sleep.service is [mandatory](https://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html#arch). Really.

**Comment by KJoke70** [comment]
[AC](https://gist.github.com/KJoke70/5d52a9f584542e3f1828793f417eeee0#file-ac), [Battery](https://gist.github.com/KJoke70/5d52a9f584542e3f1828793f417eeee0#file-bat).

**Comment by linrunner** [comment]
Fedora packages are [available](https://download.linrunner.de/packages/) now.

**Comment by ykgmfq** [comment]
Beta 4:
```
+++ Recommendations
* Install acpi-call kernel module for ThinkPad battery features\n
```
Is this recommendation useful when natacpi is active? Also the printed linebreak
```
> tlp stat
Error: 'tlp stat' no longer supported, use 'tlp-stat' instead.
> tlp
Usage: tlp start|true|bat|false|ac|usb|bayoff|discharge|setcharge|fullcharge|recalibrate|stat|diskid
```
Stat should not be listed if deprecated

**Comment by linrunner** [comment]
@ykgmfq :
tpacpi-bat/acpi_call is still needed for forced discharge, natacpi implements only thresholds so far.

> Stat should not be listed if deprecated
Fixed. Thanks.

**Comment by ykgmfq** [comment]
https://gist.github.com/ykgmfq/61441199245f8e1fc00f684a6b817883
https://gist.github.com/ykgmfq/ec85f659106541b418cd69aee94785d3

> tpacpi-bat/acpi_call is still needed for forced discharge, natacpi implements only thresholds so far.

Would love to see that in the recommendation. I think quite a lot of people are fine with only the thresholds – like me – and would be spared messing with extra kernel modules.

Off-topic: If the battery config were in a seperate file, say `/etc/default/tlp-bat`, the package manager could give me the new `/etc/default/tlp` without conflict resolution since the battery thesholds are the only things I change.

**Comment by linrunner** [comment]
@ykgmfq :
> Would love to see that in the recommendation.

Makes sense. Done.

The single config file is a fundamental feature of TLP. You may always keep your file:

* TLP is always kept backward compatible with older configs
* apt/dpkg prompt you about it
* see [FAQ](https://linrunner.de/en/tlp/docs/tlp-faq.html)

**Comment by linrunner** [comment]
**@all** : uploaded version 1.1.909. 

Bugfixes:
* Wrong charge thresholds for BAT0 fixed

Please retest.

**Comment by zauster** [comment]
[AC](https://gist.github.com/zauster/fc4635fc9efa7add34a4272f0aa5d19e), [Battery](https://gist.github.com/zauster/ffb30c967fd12909adbe40621cd03537)

**Comment by KJoke70** [comment]
[AC](https://gist.github.com/KJoke70/97d9ec78443ed3e658f4e66d7d3087df#file-ac), [Battery](https://gist.github.com/KJoke70/97d9ec78443ed3e658f4e66d7d3087df#file-bat). 

Since there's support for nvme drives now, is [btrfs+tlp](https://github.com/linrunner/TLP/issues/128) safe to use on nvme drives?

**Comment by linrunner** [comment]
@KJoke70 : issue #84 says it's some Crucial SSD exposing the problems. It's not clear to me if it is solved for that hardware..

**Comment by KJoke70** [comment]
> ps. Issue #84 is ALPM-related and NVMe disks don't use SATA links and ALPM.

So I *shouldn't* encounter the same problem but I guess I'll find out. Either way, thanks!

**Comment by linrunner** [comment]
Thanks for your help guys, very much appreciated.

TLP 1.2 was released this morning.

**Comment by linrunner** [comment]
Hi @all: you're welcome to [test 1.2.2 beta](https://github.com/linrunner/TLP/issues/408) too.

**Comment by linrunner** [comment]
1.3 Beta phase has started. Please help: https://github.com/linrunner/TLP/issues/449

**Comment by linrunner** [comment]
1.4 Beta 2 is [out](https://linrunner.de/tlp/news.html#news-top-1). Enjoy!

**Comment by linrunner** [comment]
TLP 1.5 Beta 1 is out. Testers welcome -> https://github.com/linrunner/TLP/issues/609

**Comment by linrunner** [comment]
Hi @ALL : TLP 1.6 Beta 1 is out. Testers wanted -> https://github.com/linrunner/TLP/issues/700
