### ISSUE TITLE
Audio issues

### ISSUE THREAD

**Issue by macbeto** [linrunner/TLP#381]
Hi,
Does anybody knows how to handle tlp with audio in battery mode.
When the laptop is connected to the power the audio is ok, but after a while in battery mode the laptop remains without audio. When it gets again the 100% of battery connected to the power the laptop recovers the audio.
I have selected regarding the audio settings:
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=0
SOUND_POWER_SAVE_CONTROLLER=N
With these I try to remove the control to TLP for audio purposes, but even with that configuration on battery mode I have no audio.
Thanks

**Comment by linrunner** [comment]
Hi, check out the [trouble shooting guide](https://linrunner.de/en/tlp/docs/tlp-troubleshooting.html).
