### ISSUE TITLE
[LG laptops] "battery care limit" support

### ISSUE THREAD

**Issue by jsalatas** [linrunner/TLP#383]
LG gram laptops support the [Battery care limit](https://github.com/torvalds/linux/blob/master/Documentation/laptops/lg-laptop.rst#battery-care-limit) which seems to provide similar functionality to that of tp-smapi. 

It would be nice for TLP to support that.

Thanks to @Sparsa for bringing it to my attention.

**Comment by jsalatas** [comment]
> wouldn't a tiny separate tool be more effective?

Sure! I'm fine either way!

**Comment by Sparsa** [comment]
https://www.kernel.org/doc/html/latest/admin-guide/laptops/lg-laptop.html 
Hi, as you are now considering the support for other laptops please also take this into the account.
Yes I will be available for testing:D

**Comment by linrunner** [comment]
> This value is reset to 100 when the kernel boots.

Not a problem for TLP because it is checking/restoring thresholds on boot anyway. But I wonder how it works. Shouldn't the limit be stored in the hardware (EC)? 

What happens: 

- after shutdown when powered off
- after power on with no operating system running
- after a suspend/resume (ACPI S3)

**Comment by Sparsa** [comment]
> > This value is reset to 100 when the kernel boots.
> 
> Not a problem for TLP because it is checking/restoring thresholds on boot anyway. But I wonder how it works. Shouldn't the limit be stored (i.e. persistent) in the hardware (EC)?
I doubt but I have no idea tbh.
> What happens after
> 
>     * shutdown when powered off

>     * power on with no operating system running
>     * suspend/resume (ACPI S3)
I will try to charge laptop during shutdown and see if it charges beyond limit
But, I believe this limit is set by the kernel so when the os is not running for example when powered off and running with no OS, the limit does not work. But resume/suspend works ( I can confirm this!)

**Comment by linrunner** [comment]
@Sparsa : so [here you go](https://gist.github.com/linrunner/fee8feeb079efc03001d9f3671146298). I look forward to your test results!

My questions about the behavior of the hardware are mainly curiosity in view of the later support.

**Comment by Sparsa** [comment]
> @Sparsa : so [here you go](https://gist.github.com/linrunner/fee8feeb079efc03001d9f3671146298). I look forward to your test results!
> 
> My questions about the behavior of the hardware are mainly curiosity in view of the later support.

Okay I tested on my laptop the points you were asking,
1) Even after shutting down the battery threshold was active. I put it on charge after shutting down with the limit on, and it charged till 80.
2) The limit also holds true when it is in suspend mode.(lid closed without shutting down)

**Comment by linrunner** [comment]
I also need the outputs from the testcases [here](https://gist.github.com/linrunner/fee8feeb079efc03001d9f3671146298). You may skip 2 as you already proved that the threshold works. Thanks.

**Comment by linrunner** [comment]
[TLP 1.4 is released](https://linrunner.de/tlp/news.html#tlp-1-4-released). Have fun and keep testing please!
