### ISSUE TITLE
TLP not switching governor on AC/BAT

### ISSUE THREAD

**Issue by munim** [linrunner/TLP#384]
Hi,

I am using Manjaro with Kernel 4.19 on a Lenovo T480. I have noticed that CPU governor isn't changing on AC and always remaining on powersave.

Please see the configuration and tlp-stat on the gist link below

https://gist.github.com/munim/cfacc26e3b3c7d02cb4a2c5b62d4aae2

Regards

**Comment by jsalatas** [comment]
You need to change the following lines in your configuration
```
#CPU_SCALING_GOVERNOR_ON_AC=powersave
#CPU_SCALING_GOVERNOR_ON_BAT=powersave
```
to
```
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave
```
