### ISSUE TITLE
battery charging thresholds issue (Thinkpad X1 Yoga) Arch

### ISSUE THREAD

**Issue by Gamer-one** [linrunner/TLP#387]
### Symptom data

1. Does the problem occur on battery or AC or both?
- Under Both Modes, but i am defaulting to BAT any ways.
2. Attach the *full* output of `tlp-stat` via https://gist.github.com/ for *all* cases of 1.
--- TLP 1.1 --------------------------------------------

+++ Configured Settings: /etc/default/tlp
TLP_ENABLE=1
TLP_DEFAULT_MODE=BAT
TLP_PERSISTENT_DEFAULT=0
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60
CPU_HWP_ON_AC=balance_power
CPU_HWP_ON_BAT=balance_power
SCHED_POWERSAVE_ON_AC=1
SCHED_POWERSAVE_ON_BAT=1
NMI_WATCHDOG=0
ENERGY_PERF_POLICY_ON_AC=power
ENERGY_PERF_POLICY_ON_BAT=power
DISK_DEVICES="sdb"
DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"
SATA_LINKPWR_ON_AC="med_power_with_dipm min_power"
SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"
AHCI_RUNTIME_PM_TIMEOUT=15
PCIE_ASPM_ON_AC=powersave
PCIE_ASPM_ON_BAT=powersave
RADEON_POWER_PROFILE_ON_AC=low
RADEON_POWER_PROFILE_ON_BAT=low
RADEON_DPM_STATE_ON_AC=battery
RADEON_DPM_STATE_ON_BAT=battery
RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=auto
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=off
WOL_DISABLE=Y
SOUND_POWER_SAVE_ON_AC=1
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
BAY_POWEROFF_ON_AC=0
BAY_POWEROFF_ON_BAT=0
BAY_DEVICE="sr0"
RUNTIME_PM_ON_AC=auto
RUNTIME_PM_ON_BAT=auto
USB_AUTOSUSPEND=1
USB_BLACKLIST="3070"
USB_BLACKLIST_BTUSB=0
USB_BLACKLIST_PHONE=0
USB_BLACKLIST_PRINTER=0
USB_BLACKLIST_WWAN=0
RESTORE_DEVICE_STATE_ON_STARTUP=0
START_CHARGE_THRESH_BAT0=96
STOP_CHARGE_THRESH_BAT0=100

+++ System Info
System         = LENOVO ThinkPad X1 Yoga 1st 20FRS11R04
BIOS           = N1FET65W (1.39 )
Kernel         = 4.19.19-1-lts #1 SMP Thu Jan 31 17:56:49 CET 2019 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-linux-lts root=UUID=6bbedf14-9059-4c0a-afa8-e688d2c51203 rw quiet
Init system    = systemd 
Boot mode      = UEFI

+++ TLP Status
State          = enabled
Last run       = 22:52:17,    338 sec(s) ago
Mode           = battery
Power source   = battery

+++ Processor
CPU model      = Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference = balance_power
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/energy_performance_preference = balance_power
/sys/devices/system/cpu/cpu1/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/energy_performance_preference = balance_power
/sys/devices/system/cpu/cpu2/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/energy_performance_preference = balance_power
/sys/devices/system/cpu/cpu3/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/intel_pstate/min_perf_pct      =  11 [%]
/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
/sys/devices/system/cpu/intel_pstate/no_turbo          =   0
/sys/devices/system/cpu/intel_pstate/turbo_pct         =  84 [%]
/sys/devices/system/cpu/intel_pstate/num_pstates       =  31

x86_energy_perf_policy: program not installed.

/sys/module/workqueue/parameters/power_efficient       = Y
/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.

+++ Temperatures
CPU temp               =    26 [°C]
/proc/acpi/ibm/fan     =     0 [/min]

+++ File System
/proc/sys/vm/laptop_mode               =     2
/proc/sys/vm/dirty_writeback_centisecs =  6000
/proc/sys/vm/dirty_expire_centisecs    =  6000
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10

+++ Storage Devices

+++ AHCI Link Power Management (ALPM)
/sys/class/scsi_host/host0/link_power_management_policy  = med_power_with_dipm
/sys/class/scsi_host/host1/link_power_management_policy  = med_power_with_dipm

+++ AHCI Host Controller Runtime Power Management
/sys/bus/pci/devices/0000:00:17.0/ata1/power/control = on
/sys/bus/pci/devices/0000:00:17.0/ata2/power/control = on

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = default (using bios preferences)

+++ Intel Graphics
/sys/module/i915/parameters/enable_dc        = -1 (use per-chip default)
/sys/module/i915/parameters/enable_fbc       =  1 (enabled)
/sys/module/i915/parameters/enable_psr       =  0 (disabled)
/sys/module/i915/parameters/modeset          = -1 (use per-chip default)

+++ Wireless
bluetooth = none (no device)
wifi      = on
wwan      = none (no device)

wlp4s0(iwlwifi)               : wifi, connected, power management = off

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 1
/sys/module/snd_hda_intel/parameters/power_save_controller = Y

+++ Runtime Power Management
Device blacklist = (not configured)
Driver blacklist = amdgpu nouveau nvidia radeon (default)

/sys/bus/pci/devices/0000:00:00.0/power/control = auto (0x060000, Host bridge, skl_uncore)
/sys/bus/pci/devices/0000:00:02.0/power/control = auto (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:08.0/power/control = auto (0x088000, System peripheral, no driver)
/sys/bus/pci/devices/0000:00:13.0/power/control = auto (0x000000, Non-VGA unclassified device, intel_ish_ipc)
/sys/bus/pci/devices/0000:00:14.0/power/control = auto (0x0c0330, USB controller, xhci_hcd)
/sys/bus/pci/devices/0000:00:14.2/power/control = auto (0x118000, Signal processing controller, intel_pch_thermal)
/sys/bus/pci/devices/0000:00:16.0/power/control = auto (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:17.0/power/control = auto (0x010601, SATA controller, ahci)
/sys/bus/pci/devices/0000:00:1c.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.2/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1f.0/power/control = auto (0x060100, ISA bridge, no driver)
/sys/bus/pci/devices/0000:00:1f.2/power/control = auto (0x058000, Memory controller, no driver)
/sys/bus/pci/devices/0000:00:1f.3/power/control = auto (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1f.4/power/control = auto (0x0c0500, SMBus, i801_smbus)
/sys/bus/pci/devices/0000:04:00.0/power/control = auto (0x028000, Network controller, iwlwifi)

+++ USB
Autosuspend         = enabled
Device whitelist    = (not configured)
Device blacklist    = 3070
Bluetooth blacklist = disabled
Phone blacklist     = disabled
WWAN blacklist      = disabled

Bus 002 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 3.0 root hub (hub)
Bus 001 Device 002 ID 056a:503f control = on,   autosuspend_delay_ms =  2000 -- Wacom Co., Ltd  (usbhid)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)

+++ ThinkPad Battery Features
tp-smapi   = inactive (unsupported hardware)
tpacpi-bat = inactive (kernel module 'acpi_call' not installed)

+++ Battery Status
/sys/class/power_supply/BAT0/manufacturer                   = SMP
/sys/class/power_supply/BAT0/model_name                     = 00HW029
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  52060 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  48130 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  10970 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   5290 [mW]
/sys/class/power_supply/BAT0/status                         = Discharging

Charge                                                      =   22.8 [%]
Capacity                                                    =   92.5 [%]

+++ Suggestions
* Install acpi-call kernel module for ThinkPad battery features
* Install smartmontools for disk drive health info

### Expected behavior

after installing tpacpi_call the battery thresholds under /etc/default/tlp has to be relatively easy to edit and restarting the tlp to take effect.
just as a side note: the thresholds used to work flawlessly under Ubuntu.

### Actual behavior
setting up these thresholds under /etc/default/tlp has no effects what so ever.
rather what am doing is using tpacpi-bat so set the thresholds manually using ST and SP.

### Steps to reproduce the problem
i have no idea whether all X1s Yoga out there are effected or not , as i'v never came across any similar issue on google.

**Comment by linrunner** [comment]
I doubt you can set the thresholds with tpacpi-bat by hand, because the acpi-call module for your running kernel is missing

      * Install acpi-call kernel module for ThinkPad battery features

I suggest you ask for advice in the Arch Linux forum how to properly install acpi-call.

Notes:

* TLP doesn't need the tpacpi-bat package because it's already included e.g. **/usr/share/tlp/tpacpi-bat** 
* You may uninstall the tp-smapi package

**Comment by Gamer-one** [comment]
thank alot @linrunner for the note, but as you can see am running an lts arch kernel soo tpacpi_call-lts is installed instead of tpacpi_call.
and to further clarify, i've already tested the the rolling arch linux kernel with tpacpi_call installed and got the same behaviour. 
hence am quite sure that it's a bug, what am looking for is wether it is a tlp or arch related issue.

**Comment by linrunner** [comment]
TLP doesn't care for (kernel) packages but checks with modinfo if the module is present for the running kernel. Please show

    modinfo acpi_call

**Comment by Gamer-one** [comment]
here are the output of the `modinfo` acpi_call` command 
==========================================================
`filename:       /lib/modules/4.19.19-1-lts/extramodules/acpi_call.ko.gz
license:        GPL
srcversion:     889C3798D1A53159163DB82
depends:        
retpoline:      Y
name:           acpi_call
vermagic:       4.19.18-1-lts SMP mod_unload modversions 
`
=============================================================
acpi_call seems to be present; i reinstalled tlp and acpi_call from scratch and tpacpi-bat is back in /usr/share/tlp however this time the tlp config file show:
`tpacpi-bat = active`
for what ever reason this time around it has been able to launch the kernel module; i guess it was an false alert then.
thanks again for your help @linrunner much appreciated.

**Comment by linrunner** [comment]
ps. Thanks for your feedback.
