### ISSUE TITLE
Recalibrate

### ISSUE THREAD

**Issue by HanaO00** [linrunner/TLP#390]
Hello,

I used tlp recalibrate, but the batterie goes from 26 to 5 directly

**Comment by linrunner** [comment]
Please read the [[howto]()](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md) before opening issues.

> What not to report
> * Hardware issues e.g. worn out or malfunctioning batteries
> Please use adequate Linux forums for help and support questions.
