### ISSUE TITLE
Add undervolting for Intel Sandy Bridge and newer CPUs (Core I arcitecture with P-states)

### ISSUE THREAD

**Issue by Limbo3** [linrunner/TLP#399]
Hello

**Is your feature request related to a problem? Please describe.**
It's not useful to manage voltage and power limits in two different programs and I would like to see those settings in one place.

**Describe the solution you'd like**
I would like to see a section in config file which will manage undervolting parameters (CPU, Intel GPU, CPU Cache, System Agent, Analog I/O, Digital I/O) for appropriate power profiles (AC or BATT)
For example:
INTEL_UVOLT_CPU_AC=-25
INTEL_UVOLT_CPU_BAT=-105
INTEL_UVOLT_iGPU_AC=
INTEL_UVOLT_iGPU_BAT=
...
etc.

**Describe alternatives you've considered**
1. native msr tools to set appropriate values by this [guide](https://github.com/mihic/linux-intel-undervolt).
Nothing special, just "wrmsr" from Intel [tools](https://01.org/msr-tools)
2. script on [Python](https://github.com/georgewhewell/undervolt) which was made by guide above
3. compiled software written on [C](https://github.com/kitsunyan/intel-undervolt)  by the same guide

**Additional context**
TLP already have PCH settings. Voltage on modern CPUs can also be managed and why not to add this feature. I'm sure that it won't be hard to make additional section, convert digits to binary and write results in MSR.

**Comment by linrunner** [comment]
Hi, the FAQ states:
> Features excluded from TLP intentionally
> - Undervolting for Intel Core i CPUs: there's plenty of third party tools
