### ISSUE TITLE
[T480s] charge_stop_threshold can not be set to 100

### ISSUE THREAD

**Issue by lawa42** [linrunner/TLP#401]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)

**Describe the bug**

The charge stop threshold can\t be set to 100 percent. Neither via setcharge nor full charge

**Expected behavior**

full charge should set the stop threshold to 100%

**To Reproduce**

1. Does the problem occur on battery or AC or both?

AC

2. Actions to reproduce the behaviour

Thinkpad T480s

tlp setcharge 96 100
or
tlp fullcharge

The start threshold will set either way but it is impossible to get the stop to 100

https://gist.github.com/lawa42/4a34ed08bcef8f195474c999761c91b1

**Comment by linrunner** [comment]
Please edit your post and provide the required info.

**Comment by lawa42** [comment]
This is on arch linux:
Linux it72 5.0.5-arch1-1-ARCH #1 SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux
community/acpi_call-dkms 1.1.0-202

**Comment by linrunner** [comment]
Known firmware issue (my own X1C6 is affected) --> see [FAQ](https://linrunner.de/en/tlp/docs/tlp-faq.html#stop-threshold-sticks) for a workaround..

**Comment by linrunner** [comment]
@lawa42 : on the X1C6 this is fixed with BIOS 1.37. Did you recheck with the recently published 1.31 for your T480s?

**Comment by lawa42** [comment]
After updating also the EC to 1.13 on the 480s it now works.

Thanks
