### ISSUE TITLE
Disable audio savings on default config

### ISSUE THREAD

**Issue by nokonoko** [linrunner/TLP#414]
I've noticed that having audio savings on might break your sound if you're unlucky, this happens even on a fresh Ubuntu 18.04 install.

I'm guessing something happens and the device wont wake up, why not have it off by default? Keeping the audio on can't draw that much power imo.

**Comment by linrunner** [comment]
Hi,

almost every TLP setting may cause issues on some laptops. If I follow your argument, that would mean disabling all. So: no.
