### ISSUE TITLE
FAQ dual battry firmware

### ISSUE THREAD

**Issue by bhack** [linrunner/TLP#418]
Can you better explain in the FAQ what is the suggested configuration for this note? 
> Note: newer ThinkPad models may not need charge thresholds due to dualmode battery firmware – refer to Lenovo Forums and Lenovo Support.

Does this means that doesn't make sense to set dual batteries thresholds in the config?

**Comment by linrunner** [comment]
Sorry, i won't decide that in the FAQ. I suggest you ask in the Lenovo forums.

**Comment by bhack** [comment]
@smclt30p Any hint?

**Comment by smclt30p** [comment]
Out of the loop for a long time, but my linux driver addresses batteries individually.
No idea about the new addressing.
________________________________
