### ISSUE TITLE
Errors in tlp-stat output in battery section

### ISSUE THREAD

**Issue by inksnnov** [linrunner/TLP#430]
--- TLP 1.2.2 --------------------------------------------

+++ Configured Settings: /etc/default/tlp
TLP_ENABLE=1
TLP_DEFAULT_MODE=AC
TLP_PERSISTENT_DEFAULT=0
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60
CPU_HWP_ON_AC=balance_performance
CPU_HWP_ON_BAT=balance_power
SCHED_POWERSAVE_ON_AC=0
SCHED_POWERSAVE_ON_BAT=1
NMI_WATCHDOG=0
ENERGY_PERF_POLICY_ON_AC=performance
ENERGY_PERF_POLICY_ON_BAT=power
DISK_DEVICES="nvme0n1 sda"
DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"
SATA_LINKPWR_ON_AC="med_power_with_dipm max_performance"
SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"
AHCI_RUNTIME_PM_TIMEOUT=15
RADEON_POWER_PROFILE_ON_AC=default
RADEON_POWER_PROFILE_ON_BAT=default
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery
RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=auto
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on
WOL_DISABLE=Y
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
BAY_POWEROFF_ON_AC=0
BAY_POWEROFF_ON_BAT=0
BAY_DEVICE="sr0"
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
USB_AUTOSUSPEND=1
USB_BLACKLIST_BTUSB=0
USB_BLACKLIST_PHONE=0
USB_BLACKLIST_PRINTER=1
USB_BLACKLIST_WWAN=0
RESTORE_DEVICE_STATE_ON_STARTUP=0
NATACPI_ENABLE=1
TPACPI_ENABLE=0
TPSMAPI_ENABLE=0

+++ System Info
System         = LENOVO ThinkPad L380 20M5001YRT
BIOS           = R0RET39W (1.22 )
Release        = Ubuntu 18.04.3 LTS
Kernel         = 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-5.0.0-25-generic root=UUID=f73754ee-1e18-4db8-afbe-6d6562796968 ro quiet splash vt.handoff=1
Init system    = systemd v237
Boot mode      = UEFI

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 22:30:51,     24 sec(s) ago
Mode           = AC
Power source   = AC

+++ Processor
CPU model      = Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu1/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu2/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu3/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu4/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu4/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu4/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu4/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu4/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu5/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu5/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu5/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu5/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu5/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu6/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu6/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu6/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu6/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu6/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu7/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu7/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu7/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu7/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu7/cpufreq/energy_performance_preference = balance_performance
/sys/devices/system/cpu/cpu7/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/intel_pstate/min_perf_pct      =  11 [%]
/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
/sys/devices/system/cpu/intel_pstate/no_turbo          =   0
/sys/devices/system/cpu/intel_pstate/turbo_pct         =  59 [%]
/sys/devices/system/cpu/intel_pstate/num_pstates       =  31

x86_energy_perf_policy: program not installed.

/sys/module/workqueue/parameters/power_efficient       = Y
/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.

+++ Temperatures
/proc/acpi/ibm/thermal = 50 39 43 0 0 0 44 41 [°C]
/proc/acpi/ibm/fan     =     0 [/min]

+++ File System
/proc/sys/vm/laptop_mode               =     0
/proc/sys/vm/dirty_writeback_centisecs =  1500
/proc/sys/vm/dirty_expire_centisecs    =  1500
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10

+++ Storage Devices
Devices = nvme0n1 sda

/dev/nvme0n1:
  Type      = NVMe
  Model     = INTEL SSDPEKKF256G8L                    
  Firmware  = L08P    
  Scheduler = [none] mq-deadline (multi queue)

  Runtime PM: control = auto, autosuspend_delay_ms = (not available)

/dev/sda: not present.

+++ AHCI Link Power Management (ALPM)
No AHCI-enabled host controller detected.

+++ Intel Graphics
/sys/module/i915/parameters/enable_dc        = -1 (use per-chip default)
/sys/module/i915/parameters/enable_fbc       =  1 (enabled)
/sys/module/i915/parameters/enable_psr       = -1 (use per-chip default)
/sys/module/i915/parameters/modeset          = -1 (use per-chip default)

/sys/class/drm/card2/gt_min_freq_mhz         =   300 [MHz]
/sys/class/drm/card2/gt_max_freq_mhz         =  1100 [MHz]
/sys/class/drm/card2/gt_boost_freq_mhz       =  1100 [MHz]
/sys/kernel/debug/dri/2/i915_ring_freq_table: 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000 1050 1100 [MHz] 

+++ Wireless
bluetooth = on
wifi      = on
wwan      = none (no device)

hci0(btusb)                   : bluetooth, connected
wlp2s0(iwlwifi)               : wifi, connected, power management = off

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 0
/sys/module/snd_hda_intel/parameters/power_save_controller = N

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = default (using bios preferences)

+++ Runtime Power Management
Device blacklist = (not configured)
Driver blacklist = amdgpu mei_me nouveau nvidia pcieport radeon (default)

/sys/bus/pci/devices/0000:00:00.0/power/control = on   (0x060000, Host bridge, skl_uncore)
/sys/bus/pci/devices/0000:00:02.0/power/control = on   (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:04.0/power/control = on   (0x118000, Signal processing controller, proc_thermal)
/sys/bus/pci/devices/0000:00:14.0/power/control = on   (0x0c0330, USB controller, xhci_hcd)
/sys/bus/pci/devices/0000:00:14.2/power/control = on   (0x118000, Signal processing controller, intel_pch_thermal)
/sys/bus/pci/devices/0000:00:15.0/power/control = on   (0x118000, Signal processing controller, intel-lpss)
/sys/bus/pci/devices/0000:00:15.1/power/control = on   (0x118000, Signal processing controller, intel-lpss)
/sys/bus/pci/devices/0000:00:16.0/power/control = auto (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:1c.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.2/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.4/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1d.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1f.0/power/control = on   (0x060100, ISA bridge, no driver)
/sys/bus/pci/devices/0000:00:1f.2/power/control = on   (0x058000, Memory controller, no driver)
/sys/bus/pci/devices/0000:00:1f.3/power/control = on   (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1f.4/power/control = on   (0x0c0500, SMBus, no driver)
/sys/bus/pci/devices/0000:02:00.0/power/control = on   (0x028000, Network controller, iwlwifi)
/sys/bus/pci/devices/0000:03:00.0/power/control = on   (0x010802, Non-Volatile memory controller, nvme)
/sys/bus/pci/devices/0000:04:00.0/power/control = on   (0xff0000, Unassigned class [ff00], rtsx_pci)

+++ USB
Autosuspend         = enabled
Device whitelist    = (not configured)
Device blacklist    = (not configured)
Bluetooth blacklist = disabled
Phone blacklist     = disabled
WWAN blacklist      = disabled

Bus 002 Device 005 ID 17ef:a357 control = auto, autosuspend_delay_ms =    0 -- Lenovo  (hub)
Bus 002 Device 004 ID 17ef:a359 control = auto, autosuspend_delay_ms = 2000 -- Lenovo  (cdc_ether)
Bus 002 Device 003 ID 17e9:6015 control = auto, autosuspend_delay_ms = 2000 -- DisplayLink  (usbfs, snd-usb-audio)
Bus 002 Device 002 ID 17ef:a356 control = auto, autosuspend_delay_ms =    0 -- Lenovo  (hub)
Bus 002 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 3.0 root hub (hub)
Bus 001 Device 003 ID 8087:0a2b control = auto, autosuspend_delay_ms = 2000 -- Intel Corp.  (btusb)
Bus 001 Device 006 ID 17ef:a354 control = on,   autosuspend_delay_ms = 2000 -- Lenovo  (usbhid)
Bus 001 Device 005 ID 1a40:0101 control = auto, autosuspend_delay_ms =    0 -- Terminus Technology Inc. Hub (hub)
Bus 001 Device 004 ID 17ef:1029 control = auto, autosuspend_delay_ms =    0 -- Lenovo  (hub)
Bus 001 Device 002 ID 17ef:1028 control = auto, autosuspend_delay_ms =    0 -- Lenovo  (hub)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 2.0 root hub (hub)

+++ Battery Features: Charge Thresholds and Recalibrate
natacpi    = active (data, thresholds)
tpacpi-bat = inactive (disabled by configuration)
tp-smapi   = inactive (ThinkPad not supported)

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/class/power_supply/BAT0/manufacturer                   = LGC
/sys/class/power_supply/BAT0/model_name                     = 01AV481
/sys/class/power_supply/BAT0/cycle_count                    =     71
/sys/class/power_supply/BAT0/energy_full_design             =  45000 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  44940 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  37700 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Unknown (threshold effective)

/sys/class/power_supply/BAT0/charge_start_threshold         =     80 [%]
/sys/class/power_supply/BAT0/charge_stop_threshold          =     85 [%]

Charge                                                      =   83.9 [%]
Capacity                                                    =   99.9 [%]

+++ ThinkPad Battery Status: hid-00:1f:20:e4:e8:df-battery
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/manufacturer = (not available)
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/model_name = Bluetooth Mouse M557
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/cycle_count = (not supported)
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/status = Discharging

/usr/bin/tlp-stat: 349: [: -eq: unexpected operator
                                                            =      0 [%]
/usr/bin/tlp-stat: 349: [: -eq: unexpected operator
                                                            =      0 [%]

+++ Charge total                                            =   83.9 [%]

+++ Recommendations
* Install smartmontools for disk drive health info

**Comment by linrunner** [comment]
Hi, thanks for your report. Be so kind as to give me the files in that directory:

    grep '.*' /sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/*

**Comment by inksnnov** [comment]
Hi
grep '.*' /sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/*
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/capacity:35
grep: /sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/device: Это каталог
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/model_name:Bluetooth Mouse M557
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/online:1
grep: /sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/power: Это каталог
grep: /sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/powers: Это каталог
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/present:1
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/scope:Device
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/status:Discharging
grep: /sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/subsystem: Это каталог
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/type:Battery
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/uevent:POWER_SUPPLY_NAME=hid-00:1f:20:e4:e8:df-battery
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/uevent:POWER_SUPPLY_PRESENT=1
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/uevent:POWER_SUPPLY_ONLINE=1
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/uevent:POWER_SUPPLY_CAPACITY=35
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/uevent:POWER_SUPPLY_MODEL_NAME=Bluetooth Mouse M557
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/uevent:POWER_SUPPLY_STATUS=Discharging
/sys/class/power_supply/hid-00:1f:20:e4:e8:df-battery/uevent:POWER_SUPPLY_SCOPE=Device

**Comment by linrunner** [comment]
Thanks, fixed.

Would you please test and report? You may download packages [here](https://download.linrunner.de/packages/).

**Comment by linrunner** [comment]
Please re-test with 1.3.0-beta.3 and report.
Instructions: https://github.com/linrunner/TLP/issues/449
