### ISSUE TITLE
blacklist specific device support

### ISSUE THREAD

**Issue by agm28011997** [linrunner/TLP#433]
I mean a file apart from TLP.conf  that should be only updated/edited through the system package(and upstream), because TLP.conf is usually edited by yourself and not updated with the tlp program itselfs, and we have config files very old( there is no direct problem on this).
the file has to contain the feature that can not be enabled by default in the device(with an id of the specific device for not enabling this) .

for example:
 you have in your TLP.conf a tweak called:

RUNTIME_PM_ON_BAT=auto

this will put PM in  all pci( except some other personal blackilsts in tlp.conf)
You have a wireless card that is known to have problems with PM, with TLPdefault (now) enabled you have a not working wireless card, you have to uninstal TLP or edit .conf file, with the feature enabled and default TLP you are going to have a wireless without PM but the rest of the devices having PM and the wireless working good with no worries.

With the feature I am requesting, you are going to have only PM on the devices that are not in the blacklist of the TLP blacklist file.
You have PM on almost all pci devices but not in the wireless ones.
This option can be reverted with:
 USE_DEFAULT_TLP_BLACKLIST=0, 

but the default and recommended one should be :
USE_DEFAULT_TLP_BLACKLIST=1

This list can be updated through issues that people can open in TLP or distribution packages with devices that are not working with PM feature or USB autosuspend ones. we blacklist them in the file, the file get updated, and the problem is "fixed". In the moment that people report a device working well with PM we can UN-blacklist them again. I think it is a good feature and easy to " make" but I am not a developper.(if there is much difficult sorry XD)
If you don't understand my idea feel free to ask everything you want, I have bad english expression and usually the people don't understand me.

EDIT: nothing of this is invasive and can be disabled if you want with the tlp.conf, but this behaviour will be better, less agresive and making a deafult TLP better

**Comment by linrunner** [comment]
Hi, thanks for your suggestion.

I don't want to maintain device specific blacklists in TLP. Main reason is that there is far too little usable, precise input from the users and neither for inclusion in the list nor for the exclusion. A specific device will be there forever.

I prefer to have this addressed at the source e.g. kernel level – either autosuspend fixed or blacklisted. 

I think TLP's current approach to blacklist whole device classes like USB input, phones, printers, scanners, wwan and some switch parameters is sufficient – and causes less headaches for me to maintain.

**Comment by agm28011997** [comment]
I think is not possible to have in kernel side blacklists to something TLP is forcing, for example TLP forces autosuspend and PM in pci in almost all devices, the kernel didn't enable it by default, your program does it, Why has the kernel to refuses to enable something you are forcing in an specific device?, but I understand your decission in not adding something is going to need much time of yours. Anyways, your program is the base for power management in linux VERY GOOD JOB AND THANK YOU SO MUCH :)

**Comment by linrunner** [comment]
I meant a "hard" blacklist which prevents enabling pm from user space. But basically, you'd just move the dilemma ...

Thanks for your feedback.
