### ISSUE TITLE
F31: tp_smapi, acpi_call not in repo

### ISSUE THREAD

**Issue by teknyk** [linrunner/TLP#439]
**Describe the bug**
Following the instructions on the TLP installation returns a 404 error when trying to add the Fedora repos for the optional ThinkPad packages: 

<pre>[teknyk@tekpad ~]$ sudo  dnf install http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc$(rpm -E %fedora).noarch.rpm 
Last metadata expiration check: 0:40:49 ago on Wed 23 Oct 2019 09:26:45 PM EET.
[MIRROR] tlp-release.fc31.noarch.rpm: Status code: 404 for http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
[MIRROR] tlp-release.fc31.noarch.rpm: Status code: 404 for http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
[MIRROR] tlp-release.fc31.noarch.rpm: Status code: 404 for http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
[MIRROR] tlp-release.fc31.noarch.rpm: Status code: 404 for http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
[FAILED] tlp-release.fc31.noarch.rpm: Status code: 404 for http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
Status code: 404 for http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
[teknyk@tekpad ~]$ 
</pre>

**Expected behavior**

Repos should have been installed correctly and then run  <pre> dnf install akmod-tp_smapi akmod-acpi_call kernel-devel </pre> to install the packages.

**To Reproduce**

Run <pre> dnf install http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc$(rpm -E %fedora).noarch.rpm </pre> on any Fedora installation.

**Additional context**

I've tried to installing the packages and repos manually from http://repo.linrunner.de/fedora/tlp/repos/releases/and would get a "Failed to download metadata" error when running dnf

**Comment by linrunner** [comment]
Packages have available since 31.10.2019.
