### ISSUE TITLE
Restore keyboard backlight state on reboot or A/C plug

### ISSUE THREAD

**Issue by cryobry** [linrunner/TLP#447]
**Is your feature request related to a problem? Please describe.**

Whenever my Thinkpad T480s reboots or is unplugged/plugged in, the keyboard backlight is turned on. I would like a feature in TLP to restore the backlight state to its last state before reboot/plugged. I could probably do this with udev but I already have TLP running and it seems like a simple configuration setting in tlp.conf would be much simpler.

**Comment by linrunner** [comment]
Out of scope.
