### ISSUE TITLE
throttled vs TLP

### ISSUE THREAD

**Issue by joakim-tjernlund** [linrunner/TLP#455]
Trying to deduce if TLP replaces throttled or if they can be used at the same time?

**Comment by linrunner** [comment]
This is not a Q&A forum. Thanks for your understanding.

**Comment by joakim-tjernlund** [comment]
Where is one ?
I figure I have to ask TLP devs this, there is no info in google

**Comment by nariox** [comment]
TLP does not replace throttled, but you might need to modify a config to avoid conflicts
https://linrunner.de/en/tlp/docs/tlp-faq.html
