### ISSUE TITLE
Headphonejack plugin automute don't works on TLP 1.3

### ISSUE THREAD

**Issue by plumlis** [linrunner/TLP#458]
When TLP 1.3 enabled. I plugged in headphone jack on my laptop. 
But system won't mute speaker and switch to headphone output.

**To Reproduce**

1. Enable TLP 1.3
2. Set SOUND_POWER_SAVE_CONTROLLER=Y 
3, sudo tlp start
4. Try to plug in headphonejack
5, System won't mute speaker and switch to headphonejack
6. Then Set  SOUND_POWER_SAVE_CONTROLLER=N  
7, sudo tlp start
8. automute and headphonejack switch now works well on Battery mode but still bad on AC mode.

Here is my tlp-stat

--- TLP 1.3.0-beta.4 --------------------------------------------

+++ Configured Settings:
/etc/tlp.conf L0015: TLP_ENABLE="1"
/etc/tlp.conf L0025: TLP_PERSISTENT_DEFAULT="0"
/etc/tlp.conf L0030: DISK_IDLE_SECS_ON_AC="0"
/etc/tlp.conf L0031: DISK_IDLE_SECS_ON_BAT="2"
/etc/tlp.conf L0035: MAX_LOST_WORK_SECS_ON_AC="15"
/etc/tlp.conf L0036: MAX_LOST_WORK_SECS_ON_BAT="60"
/etc/tlp.conf L0117: CPU_ENERGY_PERF_POLICY_ON_AC="balance_performance"
/etc/tlp.conf L0118: CPU_ENERGY_PERF_POLICY_ON_BAT="balance-power"
/etc/tlp.conf L0097: SCHED_POWERSAVE_ON_AC="0"
/etc/tlp.conf L0098: SCHED_POWERSAVE_ON_BAT="1"
/etc/tlp.conf L0103: NMI_WATCHDOG="0"
/etc/tlp.conf L0124: DISK_DEVICES="nvme0n1 sda"
/etc/tlp.conf L0131: DISK_APM_LEVEL_ON_AC="254 254"
/etc/tlp.conf L0132: DISK_APM_LEVEL_ON_BAT="128 128"
/etc/tlp.conf L0159: DISK_IOSCHED="bfq bfq"
/etc/tlp.conf L0166: SATA_LINKPWR_ON_AC="med_power_with_dipm max_performance"
/etc/tlp.conf L0167: SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"
/etc/tlp.conf L0184: AHCI_RUNTIME_PM_TIMEOUT="15"
/etc/tlp.conf L0190: PCIE_ASPM_ON_AC="default"
/etc/tlp.conf L0191: PCIE_ASPM_ON_BAT="powersave"
defaults.conf L0024: RADEON_POWER_PROFILE_ON_AC="default"
defaults.conf L0025: RADEON_POWER_PROFILE_ON_BAT="default"
defaults.conf L0026: RADEON_DPM_PERF_LEVEL_ON_AC="auto"
defaults.conf L0027: RADEON_DPM_PERF_LEVEL_ON_BAT="auto"
/etc/tlp.conf L0223: WIFI_PWR_ON_AC="off"
/etc/tlp.conf L0224: WIFI_PWR_ON_BAT="on"
/etc/tlp.conf L0228: WOL_DISABLE="Y"
/etc/tlp.conf L0233: SOUND_POWER_SAVE_ON_AC="0"
/etc/tlp.conf L0234: SOUND_POWER_SAVE_ON_BAT="1"
/etc/tlp.conf L0239: SOUND_POWER_SAVE_CONTROLLER="N"
/etc/tlp.conf L0246: BAY_POWEROFF_ON_AC="0"
/etc/tlp.conf L0247: BAY_POWEROFF_ON_BAT="0"
/etc/tlp.conf L0250: BAY_DEVICE="sr0"
/etc/tlp.conf L0254: RUNTIME_PM_ON_AC="on"
/etc/tlp.conf L0255: RUNTIME_PM_ON_BAT="auto"
defaults.conf L0039: RUNTIME_PM_DRIVER_BLACKLIST="amdgpu mei_me nouveau nvidia pcieport radeon"
/etc/tlp.conf L0272: USB_AUTOSUSPEND="1"
/etc/tlp.conf L0283: USB_BLACKLIST_BTUSB="0"
/etc/tlp.conf L0288: USB_BLACKLIST_PHONE="0"
/etc/tlp.conf L0293: USB_BLACKLIST_PRINTER="1"
/etc/tlp.conf L0298: USB_BLACKLIST_WWAN="0"
defaults.conf L0045: USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN="0"
/etc/tlp.conf L0315: RESTORE_DEVICE_STATE_ON_STARTUP="0"
defaults.conf L0047: RESTORE_THRESHOLDS_ON_BAT="0"
/etc/tlp.conf L0368: NATACPI_ENABLE="1"
/etc/tlp.conf L0369: TPACPI_ENABLE="1"
/etc/tlp.conf L0370: TPSMAPI_ENABLE="1"
/etc/tlp.conf L0020: TLP_DEFAULT_MODE="BAT"
/etc/tlp.conf L0055: CPU_SCALING_GOVERNOR_ON_AC="powersave"
/etc/tlp.conf L0056: CPU_SCALING_GOVERNOR_ON_BAT="powersave"
/etc/tlp.conf L0072: CPU_HWP_ON_AC="performance"
/etc/tlp.conf L0073: CPU_HWP_ON_BAT="default"
/etc/tlp.conf L0091: CPU_BOOST_ON_AC="1"
/etc/tlp.conf L0092: CPU_BOOST_ON_BAT="0"
/etc/tlp.conf L0178: AHCI_RUNTIME_PM_ON_AC="on"
/etc/tlp.conf L0179: AHCI_RUNTIME_PM_ON_BAT="on"
/etc/tlp.conf L0355: START_CHARGE_THRESH_BAT0="90"
/etc/tlp.conf L0356: STOP_CHARGE_THRESH_BAT0="95"

+++ System Info
System         = LENOVO ThinkPad X1 Carbon 5th 20HRCTO1WW
BIOS           = N1MET59W (1.44 )
Release        = "Fedora release 31 (Thirty One)"
Kernel         = 5.4.14-200.fc31.x86_64 #1 SMP Thu Jan 23 13:06:12 UTC 2020 x86_64
/proc/cmdline  = BOOT_IMAGE=(hd0,gpt3)/boot/vmlinuz-5.4.14-200.fc31.x86_64 root=UUID=c50ae847-6e9f-4219-846a-2cc8ccd61c71 ro resume=UUID=8c762134-e464-4fa1-b9ef-e13435231d56 rhgb quiet
Init system    = systemd 
Boot mode      = UEFI
SELinux status = disabled

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 08时38分44秒,   1242 sec(s) ago
Mode           = battery
Power source   = battery

+++ Processor
CPU model      = Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  2800000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference = balance_power [HWP.EPP]
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  2800000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/energy_performance_preference = balance_power [HWP.EPP]
/sys/devices/system/cpu/cpu1/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  2800000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/energy_performance_preference = balance_power [HWP.EPP]
/sys/devices/system/cpu/cpu2/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  2800000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/energy_performance_preference = balance_power [HWP.EPP]
/sys/devices/system/cpu/cpu3/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/intel_pstate/min_perf_pct      =  10 [%]
/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
/sys/devices/system/cpu/intel_pstate/no_turbo          =   1
/sys/devices/system/cpu/intel_pstate/turbo_pct         =  31 [%]
/sys/devices/system/cpu/intel_pstate/num_pstates       =  36

/sys/module/workqueue/parameters/power_efficient       = N
/proc/sys/kernel/nmi_watchdog                          = 0

+++ Temperatures
/proc/acpi/ibm/thermal = 37 -128 0 0 0 0 0 0 [°C]
/proc/acpi/ibm/fan     =     0 [/min]

+++ File System
/proc/sys/vm/laptop_mode               =     2
/proc/sys/vm/dirty_writeback_centisecs =  6000
/proc/sys/vm/dirty_expire_centisecs    =  6000
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10

+++ Storage Devices
Devices = nvme0n1 sda

/dev/nvme0n1:
  Type      = NVMe
  Model     = Samsung SSD 960 EVO 1TB                 
  Firmware  = 3B7QCXE7
  Scheduler = mq-deadline kyber [bfq] none (multi queue)

  Runtime PM: control = auto, autosuspend_delay_ms = (not available)

  SMART info:
    Critical Warning:                   0x00
    Temperature:                        29 Celsius
    Available Spare:                    100%
    Available Spare Threshold:          10%
    Percentage Used:                    1%
    Data Units Written:                 39,453,257 [20.2 TB]
    Power Cycles:                       4,637
    Power On Hours:                     1,607
    Unsafe Shutdowns:                   417
    Media and Data Integrity Errors:    0

/dev/sda: not present.

+++ AHCI Link Power Management (ALPM)
No AHCI-enabled host controller detected.

+++ Intel Graphics
/sys/module/i915/parameters/enable_dc        =  2 (disabled + deep)
/sys/module/i915/parameters/enable_fbc       =  1 (enabled)
/sys/module/i915/parameters/enable_psr       =  1 (enabled)
/sys/module/i915/parameters/modeset          = -1 (use per-chip default)

/sys/class/drm/card0/gt_min_freq_mhz         =   300 [MHz]
/sys/class/drm/card0/gt_max_freq_mhz         =  1150 [MHz]
/sys/class/drm/card0/gt_boost_freq_mhz       =  1150 [MHz]
/sys/kernel/debug/dri/0/i915_ring_freq_table: 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000 1050 1100 1150 [MHz] 

+++ Wireless
bluetooth = on
wifi      = on
wwan      = on

hci0(btusb)                   : bluetooth, not connected
wlp4s0(iwlwifi)               : wifi, connected, power management = on
wwp0s20f0u6i12(cdc_mbim)      : wwan, not connected

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 1
/sys/module/snd_hda_intel/parameters/power_save_controller = N

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = [default] performance powersave powersupersave (using BIOS preferences)

+++ Runtime Power Management
Device blacklist = (not configured)
Driver blacklist = amdgpu mei_me nouveau nvidia pcieport radeon

/sys/bus/pci/devices/0000:00:00.0/power/control = auto (0x060000, Host bridge, skl_uncore)
/sys/bus/pci/devices/0000:00:02.0/power/control = auto (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:08.0/power/control = auto (0x088000, System peripheral, no driver)
/sys/bus/pci/devices/0000:00:14.0/power/control = auto (0x0c0330, USB controller, xhci_hcd)
/sys/bus/pci/devices/0000:00:14.2/power/control = auto (0x118000, Signal processing controller, intel_pch_thermal)
/sys/bus/pci/devices/0000:00:16.0/power/control = auto (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:1c.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.2/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.4/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1d.0/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1f.0/power/control = auto (0x060100, ISA bridge, no driver)
/sys/bus/pci/devices/0000:00:1f.2/power/control = auto (0x058000, Memory controller, no driver)
/sys/bus/pci/devices/0000:00:1f.3/power/control = auto (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1f.4/power/control = auto (0x0c0500, SMBus, i801_smbus)
/sys/bus/pci/devices/0000:00:1f.6/power/control = auto (0x020000, Ethernet controller, e1000e)
/sys/bus/pci/devices/0000:02:00.0/power/control = auto (0xff0000, Unassigned class [ff00], rtsx_pci)
/sys/bus/pci/devices/0000:04:00.0/power/control = auto (0x028000, Network controller, iwlwifi)
/sys/bus/pci/devices/0000:05:00.0/power/control = auto (0x010802, Non-Volatile memory controller, nvme)

+++ USB
Autosuspend         = enabled
Device whitelist    = (not configured)
Device blacklist    = (not configured)
Bluetooth blacklist = disabled
Phone blacklist     = disabled
WWAN blacklist      = disabled

Bus 002 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 3.0 root hub (hub)
Bus 001 Device 006 ID 138a:0097 control = auto, autosuspend_delay_ms = 2000 -- Validity Sensors, Inc.  (no driver)
Bus 001 Device 005 ID 04f2:b5ce control = auto, autosuspend_delay_ms = 2000 -- Chicony Electronics Co., Ltd Integrated Camera (uvcvideo)
Bus 001 Device 004 ID 8087:0a2b control = auto, autosuspend_delay_ms = 2000 -- Intel Corp.  (btusb)
Bus 001 Device 003 ID 1199:9079 control = auto, autosuspend_delay_ms = 2000 -- Sierra Wireless, Inc. Sierra Wireless EM7455 Qualcomm Snapdragon X7 LTE-A (cdc_mbim)
Bus 001 Device 002 ID 04f2:b5cf control = auto, autosuspend_delay_ms = 2000 -- Chicony Electronics Co., Ltd Integrated IR Camera (uvcvideo)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 2.0 root hub (hub)

+++ Battery Features: Charge Thresholds and Recalibrate
natacpi    = active (data, thresholds)
tpacpi-bat = inactive (kernel module 'acpi_call' load error)
tp-smapi   = inactive (ThinkPad not supported)

+++ ThinkPad Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = SMP
/sys/class/power_supply/BAT0/model_name                     = 01AV430
/sys/class/power_supply/BAT0/cycle_count                    =    139
/sys/class/power_supply/BAT0/energy_full_design             =  57020 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  52660 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  46350 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   7453 [mW]
/sys/class/power_supply/BAT0/status                         = Discharging

/sys/class/power_supply/BAT0/charge_start_threshold         =     90 [%]
/sys/class/power_supply/BAT0/charge_stop_threshold          =     95 [%]

Charge                                                      =   88.0 [%]
Capacity                                                    =   92.4 [%]

------------------------------------------

I tried to change  SOUND_POWER_SAVE_ON_AC and SOUND_POWER_SAVE_ON_BAT but no luck.

**Comment by linrunner** [comment]
This is obviously a kernel issue, please file your bug report there.

Nothing wrong with TLP here and you already found a workaround ( SOUND_POWER_SAVE_CONTROLLER=N).
