### ISSUE TITLE
tlp doesn't start

### ISSUE THREAD

**Issue by pltrz** [linrunner/TLP#459]
reproduced this installing via package manager (alpine) or installing manually from github (1.3.0 tag)

trying to run tlp manually:

```
# tlp init start
/usr/sbin/tlp: line 403: /usr/share/tlp/tlp-readconfs: not found
```

this doesn't make sense: `/usr/share/tlp/tlp-readconfs` does indeed exist.

**Comment by dywisor** [comment]
Please post the output of

1. ```uname -r```

2. ```find /usr/share/tlp -ls | sort```

3. ```/usr/share/tlp/tpacpi-bat --help```  (= trying to run any other script in that directory)

**Comment by nero** [comment]
[Downstream issue](https://gitlab.alpinelinux.org/alpine/aports/issues/11181)

**Comment by linrunner** [comment]
Something seems wrong with the package. tlp-readconfs is new, but Perl scripts are not new to TLP. Please sort this with the Alpine maintainer.

**Comment by pltrz** [comment]
Yes, it failed due to perl not being installed. The packager for tlp in Alpine also mentioned they are no longer interested in maintaining this package, so I will update the package in Alpine and add the perl dependency.

**Comment by linrunner** [comment]
Thanks for your feedback. Please close here when it's done.

**Comment by linrunner** [comment]
Solved downstream.
