### ISSUE TITLE
No command to show version

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linrunner/TLP#462]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)

**Describe the bug**

`tlp --version` and variants throw an error.

**Expected behavior**

The version number should be displayed.

**To Reproduce**

`tlp --version`

**Additional context**

tlp version . . er . . 1.2.2.1. :)
EDIT: and version 1.3 (for which version, thank you).

**Comment by linrunner** [comment]
Every output of tlp-stat shows the TLP version at the top, which is perfectly adequate.

**Comment by LinuxOnTheDesktop** [comment]
Well, that is not standard and hence it will not occur to everybody (not to mention the fact that there was a recent change of that very command). Why flout a useful, very widely adhered to, easy to adhere to, convention?

**Comment by LinuxOnTheDesktop** [comment]
Just now, in trying to determine which of my computers I was testing the tlp beta on, I ran into this problem again.

I note/add:

- not everyone will know to - or think to - use `tlp-stat`;
- `tlp-stat` needs root;
- if one is after only the version number then, without a grep, one has to let the output finish and then scroll to the top of it.

Why not just implement this 'quality of life' enhancement, viz., `tlp --version`? I add, finally: there's something on the 'net somewhere about someone who was fairly new to Linux, wanted to know the version of some software, thought 'well, `--version` works on other programs . . ', ran it on the program in question, and was chuffed with Linux when the command worked.

**Comment by linrunner** [comment]
I made a note for the backlog of 1.7.

**Comment by linrunner** [comment]
Done.

**Comment by linrunner** [comment]
Hi @LinuxOnTheDesktop : TLP 1.7 Beta 1 is out with the corresponding change. Please verify -> https://github.com/linrunner/TLP/issues/760

**Comment by linrunner** [comment]
The beta test is complete, and [TLP 1.7.0](https://github.com/linrunner/TLP/releases/tag/1.7.0) is now available. Have fun!

A huge thank you to all of our wonderful contributors, testers, and bug reporters! :+1:
