### ISSUE TITLE
sudo tlp fullcharge stops at 79.5%

### ISSUE THREAD

**Issue by P4nd4233** [linrunner/TLP#465]
**Bug Description**
BAT1 reaches 79.5% after tlp fullcharge or tlp chargeonce.
The thresholds are set to 96/100, **BUT** when BAT1 Charge reaches 79.5%, this happens to /sys/class/power_supply/BAT1/power_now                      =      0 [mW]
So the Battery stops charging...

(full tlp-stat output here https://gist.github.com/P4nd4233/e56ad6a75a0be1e811e1e67150d1f5a0)

(/etc/tlp.conf https://gist.github.com/P4nd4233/e56ad6a75a0be1e811e1e67150d1f5a0)

This is after i updated to _tlp 1.3.0 (Linux Mint 19.3 Xfce, ThinkPad T440s)_
**Expected behavior**
Charge my battery to 100%...
**To Reproduce**

1. Does the problem occur on battery or AC or both?
On AC
2. Actions to reproduce the behaviour
 Run tlp fullcharge or tlp chargeonce
3. Shell commands entered and their output
sudo tlp-stat

4. **Full output of `tlp-stat` for *all*
   matching cases of 1.**
https://gist.github.com/P4nd4233/950f50a55a6520930ea7262998cfdda8

**Additional context**
In the last version everything was OK.

**Comment by linrunner** [comment]
Hi, 

works "as designed" by Lenovo. I added this to the [FAQ](https://linrunner.de/en/tlp/docs/tlp-faq.html#charging-stops-at-80). Thanks for your hint.
