### ISSUE TITLE
Change display frequency when on battery

### ISSUE THREAD

**Issue by userofryzen** [linrunner/TLP#467]
It is very simple, a tlp.conf section to configure changes in resolution and/or frequency mode of the screen when the laptop is running on ac or Bat. 
Lower frequencys are supposed to improve the power consumption. At least if you don't have variable refresh rate  at all.
I have to do some investigation about this, but for the moment I have no laptop to try.
If you want, you can run sudo powertop with the default frequency rates of your PC and comparing with for example the lowest frequency that you can put in the laptop. Please, post your differences.

PD: here you have some benchs with a mobile phone because I have no other examples.
https://www.androidauthority.com/oneplus-7-pro-battery-life-90hz-display-985616/

**Comment by linrunner** [comment]
You have a very uncommon notion of simple: half a dozen graphics chip drivers multiplied by two display servers (X11, wayland) multiplied by several display managers multiplied by a dozen desktop environments multiplied by several different compositors. Not yet considered are 1.000.000 different displays, external monitors and so on ... 

Short answer: forget it.
