### ISSUE TITLE
[Feature Request] Support for Lenovo Legion "Rapid Charge"

### ISSUE THREAD

**Issue by CCF100** [linrunner/TLP#470]
I have a Lenovo Legion y540, and it supports this feature called "Rapid charge" where it has the power IC pull more power from the power supply to charge the battery faster, but it doesn't work in Linux... Is there anyway for TLP to add support fo this?

**Comment by linrunner** [comment]
Hi, 

TLP would need a kernel interface for this. I don't know any, so the answer is currently no.
