### ISSUE TITLE
Remove TP thresholds completly

### ISSUE THREAD

**Issue by Dongerrs** [linrunner/TLP#473]
**Is your feature request related to a problem? Please describe.**
Have a T440P with a 57++ battery that showed only 25% of Design Charge after a Full Charge. Recalibrated it a few times and it has increased the Full Charge to nearly 40% of design charge. When completing a Full Charge, the battery appears to be able to 'overcharge' itself ie goes above 100% (fully charged) but then stops charging due to threshold and resets back to around 39% of design charge

**Describe the solution you'd like**
Is there a way to remove/disable the thresholds completely from EC, so the battery can full charge to where it is 'fully' charged?

**Comment by linrunner** [comment]
No. This is a battery defect or a EC problem.

Please note that the issue tracker is not for hardware support --> https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md
