### ISSUE TITLE
AHCI Port is shown as Bad in 'Powertop'

### ISSUE THREAD

**Issue by liny01-nbsa** [linrunner/TLP#474]
- [X] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)

**Describe the bug**

ataX port device is not in PM mode that's recommended in powertop.

**Expected behavior**

With some configuration, in both BAT or AC mode the device is put into PM mode.

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Both BAT and AC mode has the issue.
2. Boot laptop, and run `sudo powertop`
3. Below there's output of powertop tab.
4. And further down are the link to my tlp-stat outputs in gists.

**Additional context**

This is what shown in my powertop:

```
PowerTOP v2.11    Overview   Idle stats   Frequency stats   Device stats   Tunables   WakeUp                           
>> echo 'auto' > '/sys/bus/pci/devices/0000:00:17.0/ata2/power/control';

>> Good          Runtime PM for port ata2 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset 
   Bad           Runtime PM for port ata4 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset
   Bad           Runtime PM for port ata5 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset
   Bad           Runtime PM for port ata1 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset
   Bad           Runtime PM for port ata3 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset

```

And here is related tlp-stat output:

 - [tlp-stat AC Mode](https://gist.github.com/liny01-nbsa/4e910a71bb51fcb447f0556651b3e4c9)
 - [tlp-stat BAT Mode](https://gist.github.com/liny01-nbsa/a49f7ecce857a1569a23c66cf6ae3180)

Is there anything I can do to fix those ataX port configuration in TLP ?

Thanks!

**Comment by liny01-nbsa** [comment]
Hi, @linrunner, I have attached more information, thanks!

**Comment by liny01-nbsa** [comment]
It seems my tlp configuration wasn't rouching ataX devices at all.

**Comment by linrunner** [comment]
Your NVMe disk doesn't have `autosuspend_delay_ms`, see output:

> Runtime PM: control = auto, **autosuspend_delay_ms = (not available)**

In this case TLP doesn't touch the AHCI hosts to prevent possible system lockups causing data loss. Before you ask: there is no way to override this in TLP.

https://github.com/linrunner/TLP/blob/1.3.1/func.d/15-tlp-func-disk#L351

**Comment by liny01-nbsa** [comment]
@linrunner, thanks for your comment. I don't completely understand, my SSD is a nvme, those ataX port are on a different controller, and in my case I have no devices connected to it. Do you think it might make sense only when block device connected to ach ports has the issue you described, it would then make sense to apply the skip logic?

Thanks!

**Comment by linrunner** [comment]
You're right, of course. After i wrote NVMe, i got the same thought.

For the assignment host – device i could not find an implementation at that time. I'll reconsider this for 1.4

**Comment by linrunner** [comment]
ps. Did you actually measure the difference when you write "auto" to the ahci host sysfiles by hand?

Perform the measurement when *all* applications are closed and wait for > 5 minutes, otherwise you will not get a clean result.

**Comment by liny01-nbsa** [comment]
Hi, @linrunner, please see the results below:

 - [ataX ports on](https://gist.github.com/liny01-nbsa/4e910a71bb51fcb447f0556651b3e4c9)
 - [ataX ports auto](https://gist.github.com/liny01-nbsa/a49f7ecce857a1569a23c66cf6ae3180)

For then it's on, it's quite difficult for me to capture the full screen, when I selected the full screen, the usage would jump to 15.6W+ or even 16.3W+; So in the screen I captured, is the value I see that waited for 5 mins, with other other applications open, only the following apps:

 - DWM, my window manager,
 - picom, the compositor
 - gnome-termial, and powertop

Thanks!

**Comment by linrunner** [comment]
I didn't ask for powertop or "fullscreen", just for the difference in W.

I think your biggest problem/consumer is the 2nd graphics chip, you should look for a way to shut down the amdgpu (but please do not ask me).

**Comment by liny01-nbsa** [comment]
My bad. Based on my observation, I think if the difference is visible, it would be less than 1W. more like 0.3W ~ 0.5W, However, it seems, the system would work at the low pc state longer.

And yes, I'm aware of my 2nd graphics card issue. As I still use it from time to time by DRI_PRIME, so I won't be able to completed turn it off. I think I might need to do more research on that.

Thanks, @linrunner .

**Comment by liny01-nbsa** [comment]
And I did some quick google search, here are the results, hope it could be of use to you:

    ls -ld /sys/block/sd*/device

,

    cat /proc/scsi/scsi

,

    hdparm -i /dev/sdb

, or

    udevadm info -n /dev/sda -a

**Comment by linrunner** [comment]
I have now solved your real problem, see commit.

Please test.

**Comment by liny01-nbsa** [comment]
Thank you, @linrunner, I will do some testing this week.

**Comment by liny01-nbsa** [comment]
I have tested commit 322d9f7 from master. It works like a charm. Thanks, @linrunner.

**Comment by linrunner** [comment]
I added some more "vitamines", see commits. Could you please test once more with the latest master branch? Output of `tlp-stat -s -d` would be welcome.

**Comment by liny01-nbsa** [comment]
Tested 52d0c7c. Works great too. And the output of [`tlp-stat -s -d`](https://pastebin.lsyoyom.xyz/?56a828714fe1863b#5UA8GZh4rFbmw9a3pviKw7Kbd5t7MaAYFKnibRCnaeY4)
