### ISSUE TITLE
How to disable and revert to system defaults?

### ISSUE THREAD

**Issue by ghost** [linrunner/TLP#48]
Something has gone wrong with my setup. I've removed the threshold values from `/etc/default/tlp` and according to `tlp stat`:

```
tpacpi-bat.BAT0.startThreshold                              =     96 [%]
tpacpi-bat.BAT0.stopThreshold                               =    100 [%]
```

Yet I'm plugged in and my battery has been stuck at 77% forever. How do I completely remove all of TLP's thresholds and use the system's factory defaults? Or do I just have to specify 96/100 values in `/etc/default/tlp`?

**Comment by JulianVai** [comment]
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  57200 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  17600 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  17600 [mWh]
i just have this question is muy battery dead according to this?

**Comment by Tset-Noitamotua** [comment]
I landed here from a Google search cause I experience a similar issue. Machine stuck on charging at 79% for hours now. This seems to be the threshold value which I set with TLP on a previously installed OS.

![image](https://user-images.githubusercontent.com/5635462/67150455-e071c480-f2b7-11e9-8109-ec25c1ce77fd.png)

The strange part is that I experience this although I have done a fresh installation of Ubuntu 19.10 (Eoan) on my machine (Thinkpad X1 Carbon 6th Gen) and do not have installed TLP here at all.

@linrunner is this worth a separate issue or should I just try to disable the battery temporarily via BIOS to reset it?

**Comment by Tset-Noitamotua** [comment]
UPDATE: disabling the battery in BIOS solved my issue.

## How to temporarily disable battery in BIOS
1. unplug power cable
2. reboot into BIOS setup
3. in "power settings" disable battery. Machine will power down automatically.
4. wait a few seconds then plug in power cable

Now the battery continues to charge beyond 79%
![image](https://user-images.githubusercontent.com/5635462/67151600-9b09c300-f2c8-11e9-92df-f628ae0325af.png)
