### ISSUE TITLE
Fedora 31: tlp Lacks r/w SELinux Context Label on /run

### ISSUE THREAD

**Issue by kuirolo** [linrunner/TLP#486]
I filed a bug with Redhat in case this is more of an SELinux issue.
I had this issue with a fresh install of tlp, so I think it should be easy to reproduce.

I believe the problem is `tlp` and `cat` don't have the right SELinux context to read from and write to `/run/tlp/last_pwr`.

OS:          Fedora 31
SELinux:  default policy, enforcing

**Steps**:
```
$ sudo dnf install tlp
$ sudo tlp start
```
Unplug or plug in laptop laptop
SELinux sends notification for `cat` reading from and `tlp` writing to `last_pwr`

**Context**:
SELinux Troubleshoot makes this recommendation:

> You should report this as a bug.
> You can generate a local policy module to allow this access.
> Allow this access for now by executing:
> ```
> # ausearch -c 'cat' --raw | audit2allow -M my-cat
> # semodule -X 300 -i my-cat.pp
> ```

You can get more info about notification using `-w` or `--why` option for `audit2allow`:
```
$ sudo ausearch -c 'cat' --raw | audit2allow -w
type=AVC msg=audit(1587078124.197:793): avc:  denied  { read } for
pid=161912 comm="cat" name="last_pwr" dev="tmpfs"
ino=893514 scontext=system_u:system_r:tlp_t:s0
tcontext=unconfined_u:object_r:var_run_t:s0
tclass=file permissive=0

        Was caused by:
                Missing type enforcement (TE) allow rule.

                You can use audit2allow to generate a loadable module to allow this access.
...
```
Following resulting inode number leads to /run/tlp/last_pwr:
```
$ sudo find / -inum 893514
/run/tlp/last_pwr
```

**Comment by linrunner** [comment]
Sorry, i won't handle Fedora SELinux policy issues upstream. 

Also refer to https://github.com/linrunner/TLP/issues/434
