### ISSUE TITLE
tlp recalibrate: /usr/sbin/tlp: 2666: printf: %]: invalid directive

### ISSUE THREAD

**Issue by linewrap** [linrunner/TLP#500]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs (see below)

ThinkPad X220 Tablet running ubuntu 18.04LTE+KDE/Plasma on kernel 4-15-0-106-generic.
TLP is confused whether battery is discharging or not. #tlp-stat -b reports battery as Discharging, and so does KDE/Plasma.

Typically, tlp displays capacity/percent left/time left

Steps to reproduce the unexpected behavior:
No particular steps -- I can't get it to work despite reboots or using different battery.

1. Does the problem occur on battery or AC or both? 
AC + recalibrate mode

2. Actions to reproduce the behaviour
run # tlp recalibrate

3. Shell commands entered and their output
sudo tlp recalibrate

Currently discharging battery BAT0:
voltage            =  11565 [mV]
remaining capacity =      0 [mWh]
/usr/sbin/tlp: 2666: printf: %]: invalid directive
remaining percent  = not available [remaining time     = not discharging [min]
state              = Discharging
force discharge    = 1
Press Ctrl+C to cancel.

4. **Full output of `tlp-stat` via https://gist.github.com/ for *all*
   matching cases of 1.**

--- TLP 1.1 --------------------------------------------

+++ Configured Settings: /etc/default/tlp
TLP_ENABLE=1
TLP_DEFAULT_MODE=AC
TLP_PERSISTENT_DEFAULT=0
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60
CPU_HWP_ON_AC=balance_performance
CPU_HWP_ON_BAT=balance_power
SCHED_POWERSAVE_ON_AC=0
SCHED_POWERSAVE_ON_BAT=1
NMI_WATCHDOG=0
ENERGY_PERF_POLICY_ON_AC=performance
ENERGY_PERF_POLICY_ON_BAT=power
DISK_DEVICES="sda sdb"
DISK_APM_LEVEL_ON_AC="254 254"
DISK_APM_LEVEL_ON_BAT="128 128"
SATA_LINKPWR_ON_AC="med_power_with_dipm max_performance"
SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"
AHCI_RUNTIME_PM_TIMEOUT=15
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=powersave
RADEON_POWER_PROFILE_ON_AC=high
RADEON_POWER_PROFILE_ON_BAT=low
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery
RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=auto
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on
WOL_DISABLE=Y
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
BAY_POWEROFF_ON_AC=0
BAY_POWEROFF_ON_BAT=0
BAY_DEVICE="sr0"
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto
USB_AUTOSUSPEND=1
USB_BLACKLIST_BTUSB=0
USB_BLACKLIST_PHONE=0
USB_BLACKLIST_PRINTER=1
USB_BLACKLIST_WWAN=1
RESTORE_DEVICE_STATE_ON_STARTUP=0

+++ System Info
System         = LENOVO ThinkPad X220 Tablet 42962WU
BIOS           = 8DET46WW (1.16 )
Release        = Ubuntu 18.04.4 LTS
Kernel         = 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
/proc/cmdline  = BOOT_IMAGE=/vmlinuz-4.15.0-106-generic root=/dev/mapper/xubuntu--vg-root ro quiet
Init system    = systemd v237
Boot mode      = BIOS (CSM, Legacy)

+++ TLP Status
State          = enabled
Last run       = 12:28:14 PM,    264 sec(s) ago
Mode           = AC
Power source   = AC

+++ Processor
CPU model      = Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  3200000 [kHz]

/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  3200000 [kHz]

/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  3200000 [kHz]

/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   800000 [kHz]
/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  3200000 [kHz]

/sys/devices/system/cpu/intel_pstate/min_perf_pct      =  25 [%]
/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
/sys/devices/system/cpu/intel_pstate/no_turbo          =   0
/sys/devices/system/cpu/intel_pstate/turbo_pct         =  29 [%]
/sys/devices/system/cpu/intel_pstate/num_pstates       =  25

x86_energy_perf_policy.cpu0                            = performance 
x86_energy_perf_policy.cpu1                            = performance 
x86_energy_perf_policy.cpu2                            = performance 
x86_energy_perf_policy.cpu3                            = performance 

/sys/module/workqueue/parameters/power_efficient       = Y
/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.

+++ Temperatures
CPU temp               =    50 [°C]
/proc/acpi/ibm/fan     =  1880 [/min]

+++ File System
/proc/sys/vm/laptop_mode               =     0
/proc/sys/vm/dirty_writeback_centisecs =  1500
/proc/sys/vm/dirty_expire_centisecs    =  1500
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10

+++ Storage Devices
/dev/sda:
  Model     = SPCC Solid State Disk                   
  Firmware  = SBFM61.3
  APM Level = none/disabled
  Status    = active/idle
  TRIM      = supported
  Scheduler = cfq

  Runtime PM: control = on, autosuspend_delay =   -1

  SMART info:
      9 Power_On_Hours            =     3117 [h]
     12 Power_Cycle_Count         =      323 
    194 Temperature_Celsius       =       33 (Min/Max 33/33)  [°C]
    231 Temperature_Celsius       =       99    [°C]
    241 Total_LBAs_Written        =    0.000 [TB]

+++ AHCI Link Power Management (ALPM)
/sys/class/scsi_host/host0/link_power_management_policy  = med_power_with_dipm
/sys/class/scsi_host/host1/link_power_management_policy  = med_power_with_dipm
/sys/class/scsi_host/host2/link_power_management_policy  = med_power_with_dipm
/sys/class/scsi_host/host3/link_power_management_policy  = med_power_with_dipm
/sys/class/scsi_host/host4/link_power_management_policy  = med_power_with_dipm
/sys/class/scsi_host/host5/link_power_management_policy  = med_power_with_dipm

+++ AHCI Host Controller Runtime Power Management
/sys/bus/pci/devices/0000:00:1f.2/ata1/power/control = on
/sys/bus/pci/devices/0000:00:1f.2/ata2/power/control = on
/sys/bus/pci/devices/0000:00:1f.2/ata3/power/control = on
/sys/bus/pci/devices/0000:00:1f.2/ata4/power/control = on
/sys/bus/pci/devices/0000:00:1f.2/ata5/power/control = on
/sys/bus/pci/devices/0000:00:1f.2/ata6/power/control = on

+++ Docks and Device Bays
/sys/devices/platform/dock.0: battery_bay   = no battery 
/sys/devices/platform/dock.1: ata_bay       = no drive (or powered off)
/sys/devices/platform/dock.2: dock_station  = undocked

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = default (using bios preferences)

+++ Intel Graphics
/sys/module/i915/parameters/enable_rc6       =  1 (enabled)
/sys/module/i915/parameters/enable_dc        = -1 (use per-chip default)
/sys/module/i915/parameters/enable_fbc       =  0 (disabled)
/sys/module/i915/parameters/enable_psr       = -1 (use per-chip default)
/sys/module/i915/parameters/modeset          = -1 (use per-chip default)
/sys/module/i915/parameters/semaphores       =  1 (enabled)

+++ Wireless
bluetooth = none (no device)
wifi      = on
wwan      = none (no device)

wlp3s0(iwlwifi)               : wifi, connected, power management = off

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 0
/sys/module/snd_hda_intel/parameters/power_save_controller = N

+++ Runtime Power Management
Device blacklist = (not configured)
Driver blacklist = amdgpu nouveau nvidia radeon (default)

/sys/bus/pci/devices/0000:00:00.0/power/control = on   (0x060000, Host bridge, no driver)
/sys/bus/pci/devices/0000:00:02.0/power/control = on   (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:16.0/power/control = on   (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:19.0/power/control = on   (0x020000, Ethernet controller, e1000e)
/sys/bus/pci/devices/0000:00:1a.0/power/control = on   (0x0c0320, USB controller, ehci-pci)
/sys/bus/pci/devices/0000:00:1b.0/power/control = on   (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1c.0/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.1/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.3/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.4/power/control = on   (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1d.0/power/control = on   (0x0c0320, USB controller, ehci-pci)
/sys/bus/pci/devices/0000:00:1f.0/power/control = on   (0x060100, ISA bridge, lpc_ich)
/sys/bus/pci/devices/0000:00:1f.2/power/control = on   (0x010601, SATA controller, ahci)
/sys/bus/pci/devices/0000:00:1f.3/power/control = on   (0x0c0500, SMBus, no driver)
/sys/bus/pci/devices/0000:03:00.0/power/control = on   (0x028000, Network controller, iwlwifi)
/sys/bus/pci/devices/0000:0d:00.0/power/control = on   (0x088001, System peripheral, sdhci-pci)

+++ USB
Autosuspend         = enabled
Device whitelist    = (not configured)
Device blacklist    = (not configured)
Bluetooth blacklist = disabled
Phone blacklist     = disabled
WWAN blacklist      = enabled

Bus 002 Device 003 ID 056a:00e6 control = on,   autosuspend_delay_ms =  2000 -- Wacom Co., Ltd  (usbhid)
Bus 002 Device 002 ID 8087:0024 control = auto, autosuspend_delay_ms =     0 -- Intel Corp. Integrated Rate Matching Hub (hub)
Bus 002 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)
Bus 001 Device 003 ID 04f2:b217 control = auto, autosuspend_delay_ms =  2000 -- Chicony Electronics Co., Ltd Lenovo Integrated Camera (0.3MP) (uvcvideo)
Bus 001 Device 002 ID 8087:0024 control = auto, autosuspend_delay_ms =     0 -- Intel Corp. Integrated Rate Matching Hub (hub)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =     0 -- Linux Foundation 2.0 root hub (hub)

+++ ThinkPad Battery Features
tp-smapi   = inactive (kernel module 'tp_smapi' not installed)
tpacpi-bat = active

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/class/power_supply/BAT0/manufacturer                   = SANYO
/sys/class/power_supply/BAT0/model_name                     = 45N1177
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/charge_full_design             =   5800 [mAh]
/sys/class/power_supply/BAT0/charge_full                    =   5670 [mAh]
/sys/class/power_supply/BAT0/charge_now                     =   4398 [mAh]
/sys/class/power_supply/BAT0/current_now                    =    827 [mA]
/sys/class/power_supply/BAT0/status                         = Discharging

tpacpi-bat.BAT0.startThreshold                              =     96 [%]
tpacpi-bat.BAT0.stopThreshold                               =    100 [%]
tpacpi-bat.BAT0.forceDischarge                              =      1

Charge                                                      =   77.6 [%]
Capacity                                                    =   97.8 [%]

**Comment by linrunner** [comment]
Please install the package **tp-smapi-dkms** and try again.

**Comment by linewrap** [comment]
Installation of tp-smapi-dkms worked, thank you. I was under the impression that tp-smapi only worked on older thinkpads, not the X220.

**Comment by linrunner** [comment]
I'm a bit irritated because i can't reproduce the problem on my X220. 

Could you do me a favour?

1. Install version 1.3.1 from the PPA: https://linrunner.de/tlp/installation/ubuntu.html
2. Uninstall **tp-smapi-dkms**
3. Reboot
4. Retry `tlp recalibrate`

**Comment by linewrap** [comment]
OK so I removed the module but first restarted with TLP 1.1 -- it DID report with no errors.
I added your PPA with 1.3.1 --> rebooted -- it DID report with no errors.
Then I closed the lid of the laptop and logged back in. The error returned and now it does NOT report (1.3.1). Again, this is X220 Tablet, your acpi call may be different.

**Comment by linewrap** [comment]
OK, I ran an apt update. apt was previously reporting (my impression) that I was using version 1.3.1 but I ran the update anyway and now I'm certain it's 1.3.1
I rebooted, logged back in, TLP worked, no errors. 
Rebooted again closed lid, logged back in, all normal, TLP 1.3.1 works, reports percentages.
Bottom line: 1.3.1 appears to be working WITHOUT tp-smapi-dkms installed.

**Comment by linrunner** [comment]
>  Again, this is X220 Tablet, your acpi call may be different.

Nope. The ACPI calls are identical for all models, even the kernel implementation (natacpi) uses the same. Besides, the status output while discharging reads just the sysfs files shown there; only enabling force_discharge needs ACPI calls (via tpacpi-bat in your case).

> The error returned and now it _does NOT report_ (1.3.1).

I confess I don't get the meaning of that. 

But anyway I'm fine with your bottom line.

Bottom line: there's no point to fix this for 1.1.

**Comment by linewrap** [comment]
Thanks for looking at this.
My apologies for not being entirely clear, I'm not a native EN speaker and
definitely a computer layman.

FYI: one more thing I wanted to add: I had to revert to TLP 1.1 (the
packaged version on my 18.04) because the time when I had it installed
overlaps with the time when my X220T stylus stopped working. Stylus didn't
work after reboots.
It worked the day before I installed TLP 1.3.1 and only started working
again upon uninstalling TLP 1.3.1 (and its dependencies, presumably). It
probably matters to very few people.
Thanks again.

**Comment by linrunner** [comment]
> I'm not a native EN speaker

Neither am I ;-)

> It worked the day before I installed TLP 1.3.1 and only started working again upon uninstalling TLP 1.3.1 (and its dependencies, presumably).

Remaining at 1.1 is not a sustainable strategy. If I remember correctly the X220T's Wacom Multitouch is a USB device.

I suggest you try to isolate the cause with the help of the [Troubleshooting Guide](https://linrunner.de/tlp/support/troubleshooting.html). Feel free to open another issue for this.
