### ISSUE TITLE
tlp topup/storage/levelup/markup/remark

### ISSUE THREAD

**Issue by atagunov** [linrunner/TLP#509]
**Is your feature request related to a problem? Please describe.**

Have seen on Thinkpad X220 both with original and after-market battery:
https://linrunner.de/tlp/faq/battery.html#faq-erratic-battery-behavior

**Describe the solution you'd like**

https://forums.lenovo.com/t5/Windows-10/Power-Manager-for-Windows-10/m-p/2129075#M794

> 2015-07-28, 12:27 PM
> There is not any Power Manager for Windows 10
>The battery firmware itself will recognize the scenario where the battery is ALWAYS fully charged 100% (over a period of many weeks) and adjust the full charge capacity downwards in a way to maintain maximum battery healt

is one possible explanation. However I have been able to find virtually no other confirmation on the internet that Lenovo batteries detect "always plugged in" condition on their own and act accordingly.

Instead there are multiple statements saying that "battery conservation mode" can be enabled manually. [Example](https://support.lenovo.com/us/en/solutions/ht103159). In fact the 2015 statement that there is no "power manager for Windows 10" appears no longer correct either.

I actually have come to believe another theory behind my issue. Wikipedia [says](https://en.wikipedia.org/wiki/State_of_charge) that remaining charge in a battery can be estimated either on the basis of voltage or on the basis of integrating the current or on the basis of some combination of the two (this is my reading at least). E.g. the controller is probably measuring how many amp-hours have gone in and out - via a sense resistor - and using that as one of the inputs to the algorithm estimating the remaining battery charge level. It seems the controller might be able to gauge when battery is fully charged on the basis of voltage. But it may be that as battery is depleted and partially recharged it may be measuring Amp-hours going in and out. And it may be that the controller eventually gets confused without a solid reference point. E.g. the controller thinks the battery is at 60% of full charge when actually it's at 30% only.

It's true that if this theory was correct it would be a problem under Windows as well. But we don't know for sure the problem does not exist under Windows. In fact the most common reason people don't like after-market batteries is behaviour like this..

I believe we could try the following work-around for the issue:

- `tlp fullcharge BAT0`
- `tlp discharge BAT0` until we reach `STOP_CHARGE_THRESH_BAT0`

The hope is that once charged fully the battery controller will reset itself to a correct state. From that point it should arrive at a fairly correct charge by only discharging the battery. Well it will only arrive at a correct point if the user has been careful enough to do a recalibration fairly recently or if such recalibration happened naturally through full discharge followed by a full charge.

It is true that I could implement this as a script and gain experience before suggesting so boldly as a head-line feature.. I may do this. Yet I felt an urge to suggest this.

I have even tried to come up with a good name for this command. If implemented it would complement the `fullcharge`, `discharge`, `calibrate` family. The options I could think of are: `topup/storage/levelup/markup/remark/recharge/refresh`. `storage` is suggested because this is the action you may wish to take before putting the battery into a long-time storage.

* Your use case(s)

I would like to run this command manually or on schedule once in a while to ensure that my battery is charged to a predictable level. My Thinkpads are used plugged-in most of the time. But occasionally I take them out "into the field". I don't care for them to be 100% charged. But I would like to have `STOP_CHARGE_THRESH_BAT0` of charge in them at least, not half of that.

I would also like to be able to quickly and reliably charge my spare batteries to a fixed amount, maybe to 60% of their capacity before putting them it into a long-time storage.

* What you want to happen

I would like to see an alternative/experimental solution for https://linrunner.de/tlp/faq/battery.html#faq-erratic-battery-behavior

**Describe alternatives you've considered**

Implement this as a script, gain experience and then pursue as a `tlp` improvement :)

**Comment by linrunner** [comment]
Sorry. I have absolutely no intention to implement any more workarounds for Lenovo's (or any other manufacturer's) quirky battery firmware. I've decided long ago that my time is too precious for that. 

Thanks for your understanding.

**Comment by atagunov** [comment]
I don't believe it's fair to say this is a quirk though. Any battery controller that is asked to charge the battery precisely to 60% without being allowed to reach 100% or 0% first has got a tough job to do. We may be having this issue with Lenovo only precisely because these are the only controllers where we can set thresholds.

I do understand lack of time though and I may proceed to have more experimental data before communicating any further on the subject.

**Comment by atagunov** [comment]
Looking at it from a different perspective, `TLP` now has commands to go to `0%` and to `100%` and it can facilitate going from `0%` to `X%` via `STOP..` threshold. But there is no command for `TLP` to natively go down from `100%` to `X%`. The toolkit seems a bit incomplete

**Comment by linrunner** [comment]
> But there is no command for `TLP` to natively go down from `100%` to `X%`

There's a gross misconception in your use case: the battery does not wear out by remaining at 100%, but while _being charged_ to 100%. What you propose would be just artificial wear by discharging the battery while on AC. Better to discharge it by mobile use.

Good luck.

**Comment by atagunov** [comment]
> the battery does not wear out by remaining at 100%, but while _being charged_ to 100%

There are claims Li-Ion live longest around 3.6-3.8V per cell: [link](https://batteryuniversity.com/learn/article/how_to_store_batteries), [link](https://forums.whirlpool.net.au/thread/91qvpn89#r52091825), [link](https://www.techspot.com/community/topics/minimize-battery-wear.196805/post-1348709). Trusting them is a diff question :)

> Storing at 4.2v/cell (fully charged) will increase degradation. Keeping it below ~3.0v/cell (discharged) will degrade it

How about this? `TLP` has commands to

- charge to `100%`
- discharge to `0%`

Wouldn't a 3rd one

- make charge exactly `X%`

make sense? It would charge or discharge as required
