### ISSUE TITLE
Governor by default appears to be performance 

### ISSUE THREAD

**Issue by tobiasBora** [linrunner/TLP#510]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs (see below)

**Describe the bug**

When I run `tlp-stat`, I can see that the governor of the CPU is performance, while I'd expect it to be powersave by default. I don't know if it appears on all systems or only on NixOs, but a bug report was made here https://github.com/NixOS/nixpkgs/issues/46048 and people suggested that it could be a problem coming from tlp. If it's not, then I'll report the bug to NixOS instead. 

**Expected behavior**

I'd expect the cpu to be by default in powersave mode (at least on battery).

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Install NixOs
2. enable tlp by using `services.tlp.enable = true;`, which uses default configuration
3. Go on battery and check the output of:

```
sudo tlp-stat | grep governor
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = performance
```

4. **Full output of `tlp-stat` : https://gist.github.com/tobiasBora/7df51cee217075f4c50f294d60fc84f6

**Comment by linrunner** [comment]
Hi,

you seem to use the [TLP default configuration](https://github.com/linrunner/TLP/blob/1.2.2/default), where CPU_SCALING_GOVERNOR_ON_AC/BAT is unconfigured (leading #) and also says (above the parameters in question):

> Default: none

With that TLP won't change the CPU governor and what you see is the kernel default I guess. So TLP just works as designed. The answer in the NixOS issue is, shall we say, misleading.

If you want to change the governor to powersave you have to change your configuration by removing the leading #'s:

    CPU_SCALING_GOVERNOR_ON_AC=powersave  
    CPU_SCALING_GOVERNOR_ON_BAT=powersave
