### ISSUE TITLE
TLP uses non-standard sysfs attributes to control battery charge thresholds

### ISSUE THREAD

**Issue by pobrn** [linrunner/TLP#513]
**Describe the bug**

[This commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=813cab8f3994250e136819ae48fbd1c95d980466) specifies that the preferred names of the sysfs attributes that control charging thresholds are `charge_control_{start, end}_threshold`.

TLP uses `charge_{start, stop}_threshold`. (Or at least `tlp-stat -b` does not display anything about charge limits when the standard attributes exist.) These two attributes are not documented anywhere, and only used in the `thinkpad_acpi` kernel driver.

**Expected behavior**

TLP uses `/sys/class/power_suppy/*/charge_control_{start, end}_threshold`.

___

I have just seen this has been a topic of discussion in #321, so TLP is planning to switch to the newer names in future, correct?

**Comment by linrunner** [comment]
I have put the topic on hold until the corresponding patches for thinkpad_acpi are applied.

**Comment by pobrn** [comment]
[Merged.](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=09a0bd07764359650d41dbcb723f81321e523217)

**Comment by linrunner** [comment]
Nice :)

**Comment by linrunner** [comment]
Now implemented with the upcoming plugin architecture --> TLP 1.4.

https://github.com/linrunner/TLP/commit/ea6769e25b4420f53f48fb565a2fdaf69afc0912
