### ISSUE TITLE
Battery neither charging nor discharging when between Thresholds

### ISSUE THREAD

**Issue by aRkedos** [linrunner/TLP#517]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs (see below)

**Describe the bug**

I have got a brand new Thinkpad T14 with AMD APU. I discovered this really neat tool configured it to my liking. 

However when I set battery thresholds (e.g. 40 start, 80 stop) and the battery is exactly in between the start and stop treshold (e.g. in this case 65) and AC is plugged in the battery seems to be neither charging nor discharging. `tlp stat -b` shows the battery status as unknown. 

**Expected behavior**

Battery discharging when above start threshold until start threshold is reached. Although I will not rule out that my expectation is physically impossible. If that is the case then sorry for opening an issue. And I am fully aware that the problem could be totally unrelated to TLP.

**Additional context**

`--- TLP 1.3.1 --------------------------------------------

+++ Battery Features: Charge Thresholds and Recalibrate
natacpi    = active (data, thresholds)
tpacpi-bat = active (recalibrate)
tp-smapi   = inactive (ThinkPad not supported)

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/class/power_supply/BAT0/manufacturer                   = LGC
/sys/class/power_supply/BAT0/model_name                     = 5B10W139
/sys/class/power_supply/BAT0/cycle_count                    =      6
/sys/class/power_supply/BAT0/energy_full_design             =  50500 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  50500 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  34460 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Unknown

/sys/class/power_supply/BAT0/charge_start_threshold         =     40 [%]
/sys/class/power_supply/BAT0/charge_stop_threshold          =     80 [%]
tpacpi-bat.BAT0.forceDischarge                              =      0

Charge                                                      =   68.2 [%]
Capacity                                                    =  100.0 [%]`--- TLP 1.3.1 --------------------------------------------

+++ System Info
System         = LENOVO ThinkPad T14 Gen 1 20UDCTO1WW
BIOS           = R1BET36W(1.05 )
Release        = "Manjaro Linux"
Kernel         = 5.7.9-1-MANJARO #1 SMP PREEMPT Thu Jul 16 08:20:05 UTC 2020 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-5.7-x86_64 root=UUID=653563c4-3afd-47db-991d-6a5506eff910 rw quiet cryptdevice=UUID=4d0a5917-8537-45b5-adb4-14ad5cdcf3ef:luks-4d0a5917-8537-45b5-adb4-14ad5cdcf3ef root=/dev/mapper/luks-4d0a5917-8537-45b5-adb4-14ad5cdcf3ef apparmor=1 security=apparmor udev.log_priority=3
Init system    = systemd 
Boot mode      = UEFI

+++ TLP Status
State          = enabled
RDW state      = not installed
Last run       = 10:06:37,    430 sec(s) ago
Mode           = battery (manual)
Power source   = AC

Notice: systemd-rfkill.service is not masked -- invoke "systemctl mask systemd-rfkill.service" to correct this!
Notice: systemd-rfkill.socket is not masked -- invoke "systemctl mask systemd-rfkill.socket" to correct this!

**Comment by linrunner** [comment]
Hi,

in fact your expectation is wrong. Refer to the [FAQ](https://linrunner.de/tlp/faq/battery.html#why-does-the-battery-not-start-to-discharge-when-the-stop-threshold-is-reached-during-charging) please.
