### ISSUE TITLE
Setting INTEL_GPU min frequency fails on AC (re-plugging)

### ISSUE THREAD

**Issue by kmARC** [linrunner/TLP#522]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs (see below)

**Describe the bug**

When plugging in the power cord, `max` & `boost` values are correctly set, however `min` is not.

```
Aug 20 21:38:58 naga tlp[15723]: check_intel_gpu.present: parm=/sys/module/i915/parameters; drm=/sys/class/drm/card0; dbg=/sys/kernel/debug/dri/0
Aug 20 21:38:58 naga tlp[15723]: set_intel_gpu_min_max_boost_freq(0).min: 900; rc=1
Aug 20 21:38:58 naga tlp[15723]: set_intel_gpu_min_max_boost_freq(0).max: 1150; rc=0
Aug 20 21:38:58 naga tlp[15723]: set_intel_gpu_min_max_boost_freq(0).boost: 1150; rc=0
```

**Expected behavior**

`min` is also set correctly

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Check config:  
    ```
    $ grep INTEL_GPU_MIN /etc/tlp.conf
    INTEL_GPU_MIN_FREQ_ON_AC=900
    INTEL_GPU_MIN_FREQ_ON_BAT=300
    ```
2. Check freq while on AC
    ```
    $ sudo tlp-stat -g | grep min
    /sys/class/drm/card0/gt_min_freq_mhz         =   900 [MHz]
    ```
2. Switch to BAT
2. Check freq
    ```
    $ sudo tlp-stat -g | grep min
    /sys/class/drm/card0/gt_min_freq_mhz         =   300 [MHz]
    ```
3. Switch to AC
4. Check freq
    ```
    $ sudo tlp-stat -g | grep min
    /sys/class/drm/card0/gt_min_freq_mhz         =   300 [MHz]
    ```

[tlp-stat.txt](https://github.com/linrunner/TLP/files/5105170/tlp-stat.txt)

**Additional context**

Restarting tlp.service will properly set the values:

```
$ sudo tlp-stat -g | grep min
/sys/class/drm/card0/gt_min_freq_mhz         =   300 [MHz]
$ sudo systemctl restart tlp
$ sudo tlp-stat -g | grep min
/sys/class/drm/card0/gt_min_freq_mhz         =   900 [MHz]
```

**Comment by linrunner** [comment]
Done. Sorry for the long delay.

Please test against the main branch.
