### ISSUE TITLE
Add an option to enable DISK_APM_LEVEL_ON_AC/BAT for external mass storage (e.g. USB hard drive)

### ISSUE THREAD

**Issue by tplzr** [linrunner/TLP#523]
**Describe the solution you'd like**
* Your use case(s)
I have an ARM Single-board computer with rootfs on a USB hard drive (many SBCs don't have SATA). It runs 24/7 and I'd like to make it as power efficient as possible.
* What you want to happen
I'd like to set USB HDD APM level using `DISK_APM_LEVEL_ON_AC/BAT`

**Describe alternatives you've considered**
I currently use `hdparm` directly to set APM level

**Comment by linrunner** [comment]
I've converted the internal denylist to a parameter. See the commit for details and a link to the bug report, which is from 2010.

Please test the feature ad report. For Debian or Ubuntu you may use the alpha packages found [here](https://download.linrunner.de/packages/).

Regarding the wildcards, i'd prefer a separate issue.

**Comment by linrunner** [comment]
Now also works when plugging in USB disks.

**Comment by linrunner** [comment]
@tplzr : please test and report.
