### ISSUE TITLE
How do I disable my desktop PC from waking up from hibernation and sleep?

### ISSUE THREAD

**Issue by Joe23232** [linrunner/TLP#525]
Whenever I put my desktop PC to either sleep or hibernation, if I move the mouse it will wake the PC up. I believe I have to suspend my USB devices or something but it is enabled but it still doesn't turn it off, is there some setting to disable wake from hibernation or sleep from my mouse and keyboard?

I am using TLPUI.

**Comment by linrunner** [comment]
Hi, TLP has no setting for that. Good luck.

**Comment by Joe23232** [comment]
Hey man, but can't TLP disable USB ports?
