### ISSUE TITLE
Battery status shown as "charging" when charge threshold reached

### ISSUE THREAD

**Issue by ivdimitro** [linrunner/TLP#527]
Just to clarify - I am not sure if this bug or feature request. 

**Describe the bug**

When battery charge threshold value is set the charging of the battery stops as expected. The issue is that the battery widget of Plasma shows the battery as "charging" indefinitely. 

**Expected behavior**

The battery is considered as charged when the threshold value is reached. 

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Configure charging thresholds for the battery. 
2. Discharge the battery to the min level
3. Charge the battery. 

**Additional context**

>  $ sudo tlp-stat
> [sudo] password for idimitro: 
> --- TLP 1.3.1 --------------------------------------------
> 
> >+++ Configured Settings:
> defaults.conf L0004: TLP_ENABLE="1"
> defaults.conf L0005: TLP_PERSISTENT_DEFAULT="0"
> defaults.conf L0006: DISK_IDLE_SECS_ON_AC="0"
> defaults.conf L0007: DISK_IDLE_SECS_ON_BAT="2"
> defaults.conf L0008: MAX_LOST_WORK_SECS_ON_AC="15"
> defaults.conf L0009: MAX_LOST_WORK_SECS_ON_BAT="60"
> defaults.conf L0010: CPU_ENERGY_PERF_POLICY_ON_AC="balance_performance"
> defaults.conf L0011: CPU_ENERGY_PERF_POLICY_ON_BAT="balance_power"
> defaults.conf L0012: SCHED_POWERSAVE_ON_AC="0"
> defaults.conf L0013: SCHED_POWERSAVE_ON_BAT="1"
> defaults.conf L0014: NMI_WATCHDOG="0"
> defaults.conf L0015: DISK_DEVICES="nvme0n1 sda"
> defaults.conf L0016: DISK_APM_LEVEL_ON_AC="254 254"
> defaults.conf L0017: DISK_APM_LEVEL_ON_BAT="128 128"
> defaults.conf L0018: DISK_IOSCHED="keep keep"
> defaults.conf L0019: SATA_LINKPWR_ON_AC="med_power_with_dipm max_performance"
> defaults.conf L0020: SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"
> defaults.conf L0021: AHCI_RUNTIME_PM_TIMEOUT="15"
> defaults.conf L0022: PCIE_ASPM_ON_AC="default"
> defaults.conf L0023: PCIE_ASPM_ON_BAT="default"
> defaults.conf L0024: RADEON_POWER_PROFILE_ON_AC="default"
> defaults.conf L0025: RADEON_POWER_PROFILE_ON_BAT="default"
> defaults.conf L0026: RADEON_DPM_PERF_LEVEL_ON_AC="auto"
> defaults.conf L0027: RADEON_DPM_PERF_LEVEL_ON_BAT="auto"
> defaults.conf L0028: WIFI_PWR_ON_AC="off"
> /etc/tlp.conf L0265: WIFI_PWR_ON_BAT="off"
> defaults.conf L0030: WOL_DISABLE="Y"
> defaults.conf L0031: SOUND_POWER_SAVE_ON_AC="0"
> /etc/tlp.conf L0277: SOUND_POWER_SAVE_ON_BAT="0"
> /etc/tlp.conf L0283: SOUND_POWER_SAVE_CONTROLLER="N"
> defaults.conf L0034: BAY_POWEROFF_ON_AC="0"
> defaults.conf L0035: BAY_POWEROFF_ON_BAT="0"
> defaults.conf L0036: BAY_DEVICE="sr0"
> defaults.conf L0037: RUNTIME_PM_ON_AC="on"
> /etc/tlp.conf L0303: RUNTIME_PM_ON_BAT="on"
> defaults.conf L0039: RUNTIME_PM_DRIVER_BLACKLIST="amdgpu mei_me nouveau nvidia pcieport radeon"
> /etc/tlp.d/10-corpoBuntu.conf L0002: USB_AUTOSUSPEND="0"
> /etc/tlp.conf L0336: USB_BLACKLIST_BTUSB="1"
> /etc/tlp.conf L0342: USB_BLACKLIST_PHONE="1"
> defaults.conf L0043: USB_BLACKLIST_PRINTER="1"
> defaults.conf L0044: USB_BLACKLIST_WWAN="0"
> defaults.conf L0045: USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN="0"
> defaults.conf L0046: RESTORE_DEVICE_STATE_ON_STARTUP="0"
> /etc/tlp.d/10-corpoBuntu.conf L0019: RESTORE_THRESHOLDS_ON_BAT="1"
> defaults.conf L0048: NATACPI_ENABLE="1"
> defaults.conf L0049: TPACPI_ENABLE="1"
> defaults.conf L0050: TPSMAPI_ENABLE="1"
> /etc/tlp.d/10-corpoBuntu.conf L0007: START_CHARGE_THRESH_BAT0="40"
> /etc/tlp.d/10-corpoBuntu.conf L0008: STOP_CHARGE_THRESH_BAT0="50"
> /etc/tlp.d/10-corpoBuntu.conf L0013: START_CHARGE_THRESH_BAT1="40"
> /etc/tlp.d/10-corpoBuntu.conf L0014: STOP_CHARGE_THRESH_BAT1="50"
> 
> >+++ System Info
> System         = LENOVO ThinkPad T480 20L6S7JY0K
> BIOS           = N24ET59W (1.34 )
> Release        = KDE neon User Edition 5.19
> Kernel         = 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64
> /proc/cmdline  = BOOT_IMAGE=/BOOT/ubuntu_eoiuhp@/vmlinuz-5.4.0-45-generic root=ZFS=rpool/ROOT/ubuntu_eoiuhp ro
> Init system    = systemd v245 (245.4-4ubuntu3.2)
> Boot mode      = UEFI
> 
> >+++ TLP Status
> State          = enabled
> RDW state      = enabled
> Last run       = 08:58:45,  29886 sec(s) ago
> Mode           = AC
> Power source   = AC
> 
> >+++ Processor
> CPU model      = Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
> 
> >/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu1/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu1/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu1/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu2/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu2/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu2/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu3/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu3/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu3/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/cpu4/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu4/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu4/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu4/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/cpu5/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu5/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu5/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu5/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/cpu6/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu6/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu6/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu6/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/cpu7/cpufreq/scaling_driver    = intel_pstate
> /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor  = powersave
> /sys/devices/system/cpu/cpu7/cpufreq/scaling_available_governors = performance powersave
> /sys/devices/system/cpu/cpu7/cpufreq/scaling_min_freq  =   400000 [kHz]
> /sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq  =  3600000 [kHz]
> /sys/devices/system/cpu/cpu7/cpufreq/energy_performance_preference = balance_performance [HWP.EPP]
> /sys/devices/system/cpu/cpu7/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
> 
> >/sys/devices/system/cpu/intel_pstate/min_perf_pct      =  11 [%]
> /sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
> /sys/devices/system/cpu/intel_pstate/no_turbo          =   0
> /sys/devices/system/cpu/intel_pstate/turbo_pct         =  58 [%]
> /sys/devices/system/cpu/intel_pstate/num_pstates       =  33
> 
> >/sys/module/workqueue/parameters/power_efficient       = Y
> /proc/sys/kernel/nmi_watchdog                          = 0
> 
> >+++ Temperatures
> /proc/acpi/ibm/thermal = 55 -128 0 0 0 0 0 0 0 0 65 0 0 0 0 0 [°C]
> /proc/acpi/ibm/fan     =  3163 [/min]
> 
> >+++ File System
> /proc/sys/vm/laptop_mode               =     0
> /proc/sys/vm/dirty_writeback_centisecs =  1500
> /proc/sys/vm/dirty_expire_centisecs    =  1500
> /proc/sys/vm/dirty_ratio               =    20
> /proc/sys/vm/dirty_background_ratio    =    10
> /proc/sys/fs/xfs/xfssyncd_centisecs    =  3000
> 
> >+++ Storage Devices
> Devices = nvme0n1 sda
> 
> >/dev/nvme0n1:
>   Type      = NVMe
>   Model     = WDC PC SN720 SDAQNTW-512G-1001          
>   Firmware  = 10190101
>   Scheduler = [none] mq-deadline (multi queue)
> 
>   Runtime PM: control = auto, autosuspend_delay_ms = (not available)
> 
>   SMART info:
>     Critical Warning:                   0x00
>     Temperature:                        45 Celsius
>     Available Spare:                    100%
>     Available Spare Threshold:          10%
>     Percentage Used:                    4%
>     Data Units Written:                 56,907,725 [29.1 TB]
>     Power Cycles:                       589
>     Power On Hours:                     3,596
>     Unsafe Shutdowns:                   140
>     Media and Data Integrity Errors:    0
> 
> >/dev/sda:
>   Type      = USB
>   Model     = Generic SD MMC
>   Firmware  = unknown
>   APM Level = none/disabled
>   Status    = standby
>   Scheduler = [mq-deadline] none (multi queue)
> 
>   Runtime PM: control = on, autosuspend_delay_ms =   -1
> 
> >+++ AHCI Link Power Management (ALPM)
> No AHCI-enabled host controller detected.
> 
> >+++ Docks and Device Bays
> /sys/devices/platform/dock.0: battery_bay   = battery present
> 
> >+++ Intel Graphics
> /sys/module/i915/parameters/enable_dc        = -1 (use per-chip default)
> /sys/module/i915/parameters/enable_fbc       =  1 (enabled)
> /sys/module/i915/parameters/enable_psr       =  0 (disabled)
> /sys/module/i915/parameters/modeset          = -1 (use per-chip default)
> 
> /sys/class/drm/card0/gt_min_freq_mhz         =   300 [MHz]
> /sys/class/drm/card0/gt_max_freq_mhz         =  1100 [MHz]
> /sys/class/drm/card0/gt_boost_freq_mhz       =  1100 [MHz]
> /sys/kernel/debug/dri/0/i915_ring_freq_table: 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000 1050 1100 [MHz] 
> 
> >+++ Wireless
> bluetooth = on
> wifi      = on
> wwan      = none (no device)
> 
> hci0(btusb)                   : bluetooth, connected
> wlp3s0(iwlwifi)               : wifi, not connected, power management = off
> 
> >+++ Audio
> /sys/module/snd_hda_intel/parameters/power_save            = 0
> /sys/module/snd_hda_intel/parameters/power_save_controller = N
> 
> +++ PCIe Active State Power Management
> /sys/module/pcie_aspm/parameters/policy = [default] performance powersave powersupersave (using BIOS preferences)
> 
> +++ Runtime Power Management
> Device blacklist = (not configured)
> Driver blacklist = amdgpu mei_me nouveau nvidia pcieport radeon
> 
> /sys/bus/pci/devices/0000:00:00.0/power/control = on   (0x060000, Host bridge, skl_uncore)
> /sys/bus/pci/devices/0000:00:02.0/power/control = on   (0x030000, VGA compatible controller, i915)
> /sys/bus/pci/devices/0000:00:04.0/power/control = on   (0x118000, Signal processing controller, proc_thermal)
> /sys/bus/pci/devices/0000:00:08.0/power/control = on   (0x088000, System peripheral, no driver)
> /sys/bus/pci/devices/0000:00:14.0/power/control = on   (0x0c0330, USB controller, xhci_hcd)
> /sys/bus/pci/devices/0000:00:14.2/power/control = on   (0x118000, Signal processing controller, intel_pch_thermal)
> /sys/bus/pci/devices/0000:00:16.0/power/control = auto (0x078000, Communication controller, mei_me)
> /sys/bus/pci/devices/0000:00:1c.0/power/control = on   (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:00:1c.6/power/control = auto (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:00:1d.0/power/control = auto (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:00:1d.2/power/control = auto (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:00:1f.0/power/control = on   (0x060100, ISA bridge, no driver)
> /sys/bus/pci/devices/0000:00:1f.2/power/control = on   (0x058000, Memory controller, no driver)
> /sys/bus/pci/devices/0000:00:1f.3/power/control = on   (0x040300, Audio device, snd_hda_intel)
> /sys/bus/pci/devices/0000:00:1f.4/power/control = on   (0x0c0500, SMBus, i801_smbus)
> /sys/bus/pci/devices/0000:00:1f.6/power/control = on   (0x020000, Ethernet controller, e1000e)
> /sys/bus/pci/devices/0000:03:00.0/power/control = on   (0x028000, Network controller, iwlwifi)
> /sys/bus/pci/devices/0000:04:00.0/power/control = auto (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:05:00.0/power/control = auto (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:05:01.0/power/control = auto (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:05:02.0/power/control = auto (0x060400, PCI bridge, pcieport)
> /sys/bus/pci/devices/0000:06:00.0/power/control = on   (0x088000, System peripheral, thunderbolt)
> /sys/bus/pci/devices/0000:3c:00.0/power/control = on   (0x0c0330, USB controller, xhci_hcd)
> /sys/bus/pci/devices/0000:3d:00.0/power/control = on   (0x010802, Non-Volatile memory controller, nvme)
> 
> +++ USB
> Autosuspend         = disabled
> Device whitelist    = (not configured)
> Device blacklist    = (not configured)
> Bluetooth blacklist = enabled
> Phone blacklist     = enabled
> WWAN blacklist      = disabled
> 
> Bus 004 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 3.0 root hub (hub)
> Bus 003 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 2.0 root hub (hub)
> Bus 002 Device 004 ID 17ef:7214 control = on,   autosuspend_delay_ms = 2000 -- Lenovo  (r8152)
> Bus 002 Device 003 ID 17ef:7216 control = auto, autosuspend_delay_ms =    0 -- Lenovo USB3.0 Hub (hub)
> Bus 002 Device 002 ID 0bda:0316 control = on,   autosuspend_delay_ms = 2000 -- Realtek Semiconductor Corp. USB3.0-CRW (usb-storage)
> Bus 002 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 3.0 root hub (hub)
> Bus 001 Device 008 ID 06cb:009a control = on,   autosuspend_delay_ms = 2000 -- Synaptics, Inc.  (no driver)
> Bus 001 Device 006 ID 5986:2113 control = auto, autosuspend_delay_ms = 2000 -- Acer, Inc Integrated Camera (uvcvideo)
> Bus 001 Device 004 ID 8087:0a2b control = auto, autosuspend_delay_ms = 2000 -- Intel Corp.  (btusb)
> Bus 001 Device 007 ID 0b0e:034d control = on,   autosuspend_delay_ms = 2000 -- GN Netcom USB2.0 Hub (snd-usb-audio, usbhid)
> Bus 001 Device 005 ID 17ef:7215 control = on,   autosuspend_delay_ms = 2000 -- Lenovo  (no driver)
> Bus 001 Device 003 ID 17ef:7224 control = auto, autosuspend_delay_ms =    0 -- Lenovo USB2.0 Hub (hub)
> Bus 001 Device 009 ID 04f3:2398 control = on,   autosuspend_delay_ms = 2000 -- Elan Microelectronics Corp. Touchscreen (usbhid)
> Bus 001 Device 002 ID 046d:c52b control = on,   autosuspend_delay_ms = 2000 -- Logitech, Inc. Unifying Receiver (usbhid)
> Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 2.0 root hub (hub)
> 
> +++ Battery Features: Charge Thresholds and Recalibrate
> natacpi    = active (data, thresholds)
> tpacpi-bat = active (recalibrate)
> tp-smapi   = inactive (ThinkPad not supported)
> 
> +++ ThinkPad Battery Status: BAT0 (Main / Internal)
> /sys/class/power_supply/BAT0/manufacturer                   = SMP
> /sys/class/power_supply/BAT0/model_name                     = 01AV421
> /sys/class/power_supply/BAT0/cycle_count                    =     52
> /sys/class/power_supply/BAT0/energy_full_design             =  24000 [mWh]
> /sys/class/power_supply/BAT0/energy_full                    =  21290 [mWh]
> /sys/class/power_supply/BAT0/energy_now                     =  11980 [mWh]
> /sys/class/power_supply/BAT0/power_now                      =      0 [mW]
> /sys/class/power_supply/BAT0/status                         = Unknown (threshold may prevent charging)
> 
> /sys/class/power_supply/BAT0/charge_start_threshold         =     40 [%]
> /sys/class/power_supply/BAT0/charge_stop_threshold          =     50 [%]
> tpacpi-bat.BAT0.forceDischarge                              =      0
> 
> Charge                                                      =   56.3 [%]
> Capacity                                                    =   88.7 [%]
> 
> +++ ThinkPad Battery Status: BAT1 (Ultrabay / Slice / Replaceable)
> /sys/class/power_supply/BAT1/manufacturer                   = LGC
> /sys/class/power_supply/BAT1/model_name                     = 01AV490
> /sys/class/power_supply/BAT1/cycle_count                    =     43
> /sys/class/power_supply/BAT1/energy_full_design             =  23940 [mWh]
> /sys/class/power_supply/BAT1/energy_full                    =  21950 [mWh]
> /sys/class/power_supply/BAT1/energy_now                     =  10750 [mWh]
> /sys/class/power_supply/BAT1/power_now                      =      0 [mW]
> /sys/class/power_supply/BAT1/status                         = Unknown (threshold may prevent charging)
> 
> /sys/class/power_supply/BAT1/charge_start_threshold         =     40 [%]
> /sys/class/power_supply/BAT1/charge_stop_threshold          =     50 [%]
> tpacpi-bat.BAT1.forceDischarge                              =      0
> 
> Charge                                                      =   49.0 [%]
> Capacity                                                    =   91.7 [%]
> 
> +++ Charge total                                            =   52.6 [%]

![battery_indicator](https://user-images.githubusercontent.com/6159024/92134945-6fbd9300-ee0a-11ea-971b-d1efa1b721f5.jpg)

**Comment by linrunner** [comment]
>  The issue is that the **battery widget of Plasma** shows the battery as "charging" indefinitely.

> /sys/class/power_supply/BAT0/status = Unknown (**threshold may prevent charging**)
> /sys/class/power_supply/BAT1/status = Unknown (**threshold may prevent charging**)

Hi, 

in fact tlp-stat shows the status you expect (the kernel says "unknown" instead of "idle" for this), the Plasma widget doesn't show the status you expect. The [FAQ](https://linrunner.de/tlp/faq/battery.html#why-does-the-panel-applet-show-the-battery-state-charging-despite-charge-thresholds-are-effective) tells the details.

So why did you file your issue _here_? 

Good luck.

**Comment by ivdimitro** [comment]
Hi, I opened the case because my expectation for the functionality was that - when threshold reached battery marked as "charged". 
Thanks for the clarification. I will check with the KDE widget.
