### ISSUE TITLE
Dynamically change CPU_ENERGY_PERF_POLICY_ON_AC from balance_performance to performance based on system load

### ISSUE THREAD

**Issue by Rush** [linrunner/TLP#535]
**Is your feature request related to a problem? Please describe.**

1) The performance of my laptop on `balance_performance` seems to be much lower than on `peformance`. I want the highest performance possible but not keep the clocks high when laptop is idle. I want temps to be low so that boosts can stay up when needed and in order for boost to stay high, there needs be room for temperature increase.
![image](https://user-images.githubusercontent.com/115926/94319400-24e9f380-ff50-11ea-9933-a3bb644cfa42.png)

2) When set to performance, everything is way smoother but all cores seem to be running on very high clockspeeds even when idle!
![image](https://user-images.githubusercontent.com/115926/94318411-1ef31300-ff4e-11ea-9519-00b975e38540.png)

**Describe the solution you'd like**
TLP could periodically check for high CPU usage. If CPU usage is over a threshold (for example, compiling, running unit tests), then it should enable `performance` HWP mode. Once CPU usage goes below threshold, the mode should switch back to `balance_performance`.

**Describe alternatives you've considered**

I used to run lenovo_fix aka throttled. It does what I want but it never reverts back to balance_performance
https://github.com/erpalma/throttled/issues/213

**Additional context**

**Comment by linrunner** [comment]
Periodic checks require a daemon, which is currently not included in TLP's architecture. A daemon in turn, would require a fundamental redesign of TLP, which I do not intend to do.

I suggest you look into https://github.com/AdnanHodzic/auto-cpufreq
