### ISSUE TITLE
Thinkpad T470s - thresholds not working

### ISSUE THREAD

**Issue by LaosPL** [linrunner/TLP#536]
Ubuntu 20.04.1, all installed and set as on the pictures attached.
[url=https://naforum.zapodaj.net/27ad3ebd36d6.png.html][img]https://naforum.zapodaj.net/thumbs/27ad3ebd36d6.png[/img][/url]
[url=https://naforum.zapodaj.net/c44c8f30a562.png.html][img]https://naforum.zapodaj.net/thumbs/c44c8f30a562.png[/img][/url]
[url=https://naforum.zapodaj.net/1db868a8cfa0.png.html][img]https://naforum.zapodaj.net/thumbs/1db868a8cfa0.png[/img][/url]

https://naforum.zapodaj.net/27ad3ebd36d6.png.html
https://naforum.zapodaj.net/c44c8f30a562.png.html
https://naforum.zapodaj.net/1db868a8cfa0.png.html

Battery thresholds not working.

**Comment by linrunner** [comment]
Hi,

your issue cannot be processed without complete outputs and steps to reproduce as described in the [issue template](https://github.com/linrunner/TLP/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Provide them via https://gist.github.com/ please.

**Screenshots are not accepted.**
