### ISSUE TITLE
Missing PPA for Ubuntu 20.10

### ISSUE THREAD

**Issue by smith558** [linrunner/TLP#542]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)

**Describe the bug**

Getting packages for Ubuntu 21.04. Getting `404 Not Found [IP: 91.189.95.83 80]` on `sudo apt-get update` after the initial installation.

**Expected behavior**

Checking for new release.

**To Reproduce**

Run in terminal on Ubuntu 21.04
`sudo add-apt-repository ppa:linrunner/tlp`
`sudo apt-get update && sudo apt-get upgrade`
`sudo apt-get install tlp tlp-rdw`
`sudo apt-get update`

**Additional context**
Operating System: Ubuntu 20.10
Kernel: Linux 5.8.0-26-generic
Architecture: x86-64
![image](https://user-images.githubusercontent.com/44023416/98028897-a9108000-1e06-11eb-83ab-432646771fab.png)

**Comment by linrunner** [comment]
Hi,

you confused me, because 21.04 does not exist yet and it is not called "Gorilla Groovy". What you mean is Ubuntu 20.10 "Groovy Gorilla" (note the order).

Anyway: there is an empty PPA for 20.10 now and the error message should have disappeared. Thanks for your hint.

**Comment by smith558** [comment]
Thx!
