### ISSUE TITLE
Some driver blacklist doesn't work

### ISSUE THREAD

**Issue by korongmambu** [linrunner/TLP#543]
**Describe the bug**

As the title says above some `driver blacklist` doesn't work, so I try too on `device blacklist` still doesn't work.  

**Expected behavior**

`tlp` blacklist some drivers and/or devices who I put in `/etc/tlp.d/00-template.conf`.

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Q: Does the problem occur on battery or AC or both?
   A: Both.
2. Actions to reproduce the behaviour:
   - Put `RUNTIME_PM_BLACKLIST="00:02.0 00:03.0 00:16.0 00:1b.0 00:1c.0 00:1c.2 00:1c.3 00:1c.4 04:00.0"` & `RUNTIME_PM_DRIVER_BLACKLIST="i915 mei_me nouveau nvidia pcieport snd_hda_intel"` in `/etc/tlp.d/00-template.conf`.
   - Run `tlp-stat`, check drivers and/or devices who got blacklist in `+++ Runtime Power Management` section.
3. Full output of `tlp-stat`:
   - On AC mode: https://gist.github.com/korongmambu/fc0f718e296a2f76d8427f4bfe8bf145
   - On battery mode: https://gist.github.com/korongmambu/3dc60473c204e61a72a107f1c9b2b3c6

**Comment by linrunner** [comment]
Your issue cannot be processed without complete outputs as required by the the [issue template](https://github.com/linrunner/TLP/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Provide them via https://gist.github.com/ please.

**Comment by korongmambu** [comment]
Sorry, this is my first report on github. Also english is not my native language, I hope you understand.

**Comment by linrunner** [comment]
No problem. I gather you are trying to force said devices to `on` by blacklisting them. 

This is not what `RUNTIME_PM{_DRIVER}_BLACKLIST` actually does and unfortunately what you want is not possible with the current TLP version.

I took your issue as an opportunity to improve the [documentation](https://linrunner.de/tlp/settings/runtimepm.html):

> * Exclusion of a device means that the value on or auto as initialized by the kernel default at system startup is used and TLP won’t touch it at all
> * A device initialized to auto by the kernel cannot be set to on by entering it into RUNTIME_PM_BLACKLIST

[TLP 1.4](https://github.com/linrunner/TLP/blob/master/changelog) will add `RUNTIME_PM_DISABLE` which implements your requirement. If you like to test the alpha version, you may build and install the package `tlp-git` from the AUR which tracks my master branch.

Remember to check the [changelog](https://github.com/linrunner/TLP/blob/master/changelog) for changed parameter names in 1.4.

Before you do that i suggest you clean up your configuration files:

- **/etc/default/tlp** is deprecated --> delete it
- I don't see **/etc/tlp.conf** -->  check if it's there, if not remove the package `tlp, remove everything in **/etc/tlp.d/**, then install `tlp` again`
- Dont' change **/etc/tlp.d/00-template.conf** but copy it to **01-my.conf** (for example) and enter your individual settings there

**Comment by linrunner** [comment]
Do you have any news?

**Comment by linrunner** [comment]
I am still interested in your test results, but I will close here for the time being.
