### ISSUE TITLE
Thinkpad T14 AMD rapid charge

### ISSUE THREAD

**Issue by parfenovds** [linrunner/TLP#544]
Not sure that's a right place to put it, but..
I got thinkpad t14 amd. It has a "rapid charge" feature and the [sertificate](https://certification.ubuntu.com/hardware/202006-27980). All workd (kubuntu 20.10), but no rapid charge.
So, is there any possibility that described feature will be on TLP one day?
Or am I totally wrong and TLP has (and won't have) nothing to do with that?
Thanks!

**Comment by linrunner** [comment]
I suggest you ask in the Lenovo forum about Kernel support for this.
