### ISSUE TITLE
High power consumption after suspend/resume

### ISSUE THREAD

**Issue by pmj642** [linrunner/TLP#551]
**Describe the bug**

I've noticed on 3-4 occasions now that when my device is plugged and I close the lid to let it charge, if I remove the plug while in suspend then on resuming the power consumption is high. When I then run `sudo tlp-stat -s` then it becomes normal, which is strange as it's not even `sudo tlp start`.

**Expected behavior**

Power consumption should be normal in the above mentioned situation.

**Additional context**

Powertop output on starting 
![powertop_out_high_consumption](https://user-images.githubusercontent.com/18064158/106514123-de0d9b00-64f9-11eb-8b4b-47bc77b1fb4b.png)

tlp-stat -s output shows that its running in bat mode 
![tlp_stat](https://user-images.githubusercontent.com/18064158/106513277-c1bd2e80-64f8-11eb-9aaf-c47ba36b9a04.png)
after tlp-stat -s command 
![normal_consumption_after](https://user-images.githubusercontent.com/18064158/106513342-dbf70c80-64f8-11eb-801a-ff7acbdfa817.png)

**Comment by linrunner** [comment]
Please have a look at the issue template (again) to see what information is mandatory for an issue to be processed. In any case, screenshots are completely unsuitable.

I can assure you that `tlp-stat -s` does not make any changes to power saving settings. Maybe your laptop just needs some time to recognize the change of the power source after the resume.

I would start by checking the "tunables" tab in powertop for changes occuring.

**Comment by pmj642** [comment]
Yes, I'm aware that `tlp-stat -s` doesn't make any changes. Doing `tlp start` works too. And initially when this issue occurred it went on for about an hour until I restarted tlp to reduce the power consumption.
 
I'll make note of the config next time the issue occurs and post an issue. As of now, I'm closing this issue. Thanks.

**Comment by linrunner** [comment]
Feel free to reopen here when you have more evidence.
