### ISSUE TITLE
fast dischard

### ISSUE THREAD

**Issue by johnTux** [linrunner/TLP#553]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

fast dischard

**Expected behavior**

behavior by default before install and after remove tlp

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. problem occur on battery

**Additional context**

after remove tlp i get a fast dischard battery on my thinkpad laptop

how to recovery to default mode which was before install tlp?

**Comment by linrunner** [comment]
Uninstalling the package and rebooting is sufficient to restore the original state. If this does not help, your problem is not with TLP.

Unfortunately, your actual problem description is not understandable. What does "dischard" mean? It is not an english word.
