### ISSUE TITLE
Fedora 33 acpi_call error

### ISSUE THREAD

**Issue by alvesadrian** [linrunner/TLP#554]
Hi am getting this error on Fedora 33:
[  326.493303] acpi_call: Loading of unsigned module is rejected
[  326.601503] acpi_call: Loading of unsigned module is rejected
[  330.022297] acpi_call: Loading of unsigned module is rejected
[  330.125462] acpi_call: Loading of unsigned module is rejected
[  330.218560] acpi_call: Loading of unsigned module is rejected
[  330.445991] acpi_call: Loading of unsigned module is rejected
[  330.540130] acpi_call: Loading of unsigned module is rejected

~ ❯❯❯ sudo tlp-stat -b
--- TLP 1.3.1 --------------------------------------------

+++ Battery Features: Charge Thresholds and Recalibrate
natacpi    = active (data, thresholds)
tpacpi-bat = inactive (kernel module 'acpi_call' load error)
tp-smapi   = inactive (ThinkPad not supported)

+++ ThinkPad Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = SMP
/sys/class/power_supply/BAT0/model_name                     = 01AV471
/sys/class/power_supply/BAT0/cycle_count                    =    115
/sys/class/power_supply/BAT0/energy_full_design             =  48010 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  44670 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  39050 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   5241 [mW]
/sys/class/power_supply/BAT0/status                         = Discharging

/sys/class/power_supply/BAT0/charge_start_threshold         =     96 [%]
/sys/class/power_supply/BAT0/charge_stop_threshold          =    100 [%]

Charge                                                      =   87.4 [%]
Capacity                                                    =   93.0 [%]

tpacpi-bat = inactive (kernel module 'acpi_call' load error)

~ ❯❯❯ uname -a
Linux x280 5.10.18-200.fc33.x86_64 #1 SMP Tue Feb 23 22:06:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
~ ❯❯❯

**Comment by linrunner** [comment]
The error message alone tells what the problem is. In addition, the [installation instructions](https://linrunner.de/tlp/installation/fedora.html#thinkpads-only) give a hint on what to do:

> You must disable Secure Boot to use the ThinkPad specific packages

If you only want thresholds - which are already supported by your kernel - and do no intend to use recalibration, then you don't need acpi_call at all.
