### ISSUE TITLE
OT: HP elitebook - battery drain when powered off

### ISSUE THREAD

**Issue by herrdeh** [linrunner/TLP#572]
Hello, I know this is OT here, but hopefully, I can find experts around here to obtain help. My HP Elitebook 8440p looses its battery charge in ~1day when powered off (not suspended, not hibernated). There are several google hints on that, HP machines seem to be affected more often. Suspicious is the WiFi unit which may not power down properly.

It's running on ubuntu20 now, but all predecessors were affected as well. Hardware is:
Prozessor | Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz
RAM | 4GB
more hardware info attached.
[hardinfo_eliteboot.txt](https://github.com/linrunner/TLP/files/6952704/hardinfo_eliteboot.txt)

Could somebody help me out with a step-by-step checklist to narrow down the issue - or other useful advice.

Thanks a lot in advance,
Wolf

**Comment by linrunner** [comment]
You say yourself that this is off topic. So I'll close here right away.
