### ISSUE TITLE
Switch baterries when the critical level is reached

### ISSUE THREAD

**Issue by rapiz1** [linrunner/TLP#576]
**Is your feature request related to a problem? Please describe.**

I use Thinkpad T460s which is shipped with dual batteries. I find that a battery is used up to 0% before switching to another battery. I suppose it's bad for the battery life.
 
**Describe the solution you'd like**

1. When a battery's charge drops to 5%, switch the power source to another battery

**Describe alternatives you've considered**

Nope

**Additional context**

I've searched the Internet but with no luck. Some say it's impossible because the switch is done by the hardware.  I wonder how this works on Windows. IIRC, batteries are used up to 5%, not 0%.

**Comment by linrunner** [comment]
Hi, this is already covered by the [FAQ](https://linrunner.de/tlp/faq/misc.html)

> Features excluded from TLP intentionally
> *  ThinkPad battery balancing i.e. selecting the active battery: the Lenovo firmware offers no way to do this, neither manual nor automatic
