### ISSUE TITLE
Can't install tlp via ppa on LinuxMint (Ubuntu)

### ISSUE THREAD

**Issue by All3xJ** [linrunner/TLP#578]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

I installed tlp doing this:
```
sudo add-apt-repository ppa:linrunner/tlp
sudo apt update
```

But I get this message:
```
Error:9 http://ppa.launchpad.net/linrunner/tlp/ubuntu focal InRelease  
The following signatures could not be verified because the public key is not available: NO_PUBKEY 2B3F92F902D65EFF
W: GPG Error: http://ppa.launchpad.net/linrunner/tlp/ubuntu focal InRelease: The following signatures could not be verified because the public key is not available: NO_PUBKEY 2B3F92F902D65EFF
E: The repository "http://ppa.launchpad.net/linrunner/tlp/ubuntu focal InRelease" is not signed.
N: Updating from this repository cannot be performed safely and is therefore disabled by default.
N: See the apt-secure(8) man page for repository creation and user configuration.
```

**Comment by linrunner** [comment]
Hi, that's a problem with _add-apt-repository_ or your network connection (or maybe your Min installion). _add-apt-repository_  didn't download the repo key from Launchpad.

Try to remove, then add again:

    sudo add-apt-repository --remove ppa:linrunner/tlp
    sudo add-apt-repository ppa:linrunner/tlp
