### ISSUE TITLE
Wrong order of reading tlp.conf(.d)-files

### ISSUE THREAD

**Issue by WhitePeter** [linrunner/TLP#579]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[ ] I've attached all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (not applicable)

**Describe the bug**

The order of reading the drop-ins and *then* tlp.conf is wrong in combination with "last match wins".

**Expected behavior**

1. Intrinsic defaults
2. /etc/tlp.conf
3. /etc/tlp.conf.d/*.conf
(last match wins)

**Additional context**

The usual way of handling drop-ins on Debian-based systems, and most certainly on other distros as well, is the described expected behaviour. The simple reason is that the distro package manager can safely replace the main config (here: /etc/tlp.conf) with a newer version, if necessary, not having to ask permission, if the admin/user has all their overrides in drop-ins (ie /etc/tlp.conf.d/*.conf) and never touched the main config.

See how Debian handles changed conffiles: ~~does the installed version differ from the new version~~ has admin changed the conffile? If yes, ask what to do, if not silently replace with new version.
I believe Debian were at the forefront of the migration to drop-ins and many others followed, IIRC. Case in point: `systemctl edit foo.service` will create a drop-in in \<servicedir\>/foo.service.d/**override.conf**, the name speaks volumes. ;) The latter is just an example of what one usually expects drop-ins to do. But for that to work, the **drop-in must be read last**.

So far tlp is the only software that I have come across that does it the other way around.

Another way of doing this would have the identical outcome
1. /etc/tlp.conf.d/*.conf
2. /etc/tlp.conf
3. Intrinsic defaults
(**first match wins**)

Now, this is not a pressing matter, since tlp obviously does not ship with any uncommented settings in /etc/tlp.conf. But in the long run the changed behaviour should be the better solution. You could simply ship an new /etc/tlp.conf and never have to touch the intrinsic defaults. The way I see it, tlp.conf is for documenting the intrinsic defaults, mainly. So, if you have to change the defaults *and* document them in tlp.conf, then why not *just* change tlp.conf? My proposal would make that very easy and, as I said, this is the usual way of dealing with drop-ins.

**Comment by linrunner** [comment]
Hi, 

thanks for your input. 

The reason for reading **tlp.conf** _after_ **/etc/tlp.d/*.conf** - was that the user configuration should have priority over config snippets installed by an OEM.

No _practical_ problems have been reported to me so far due to this "being different" of TLP. Since changing it again could lead to problems, I want to keep it that way.
