### ISSUE TITLE
AMDGPU graphics reset/crash when RADEON_DPM_PERF_LEVEL_ON_AC is set to high

### ISSUE THREAD

**Issue by acarasimon96** [linrunner/TLP#588]
- [x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
- [x] I've attached all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

### Describe the bug

After upgrading TLP to 1.4.0, my ThinkPad laptop would stop responding a few seconds after I plug it in to AC power while `RADEON_DPM_PERF_LEVEL_ON_AC` is set to `high` in the config file. The display would freeze and sometimes show corruption artifacts. In extreme cases, the display would blank out, and my system would reboot without warning.

### Steps to reproduce

1. Make sure that the installed version of TLP is 1.4.0, and that it is enabled in the `tlp.conf` and running.
2. Change the value of `RADEON_DPM_PERF_LEVEL_ON_AC` to `"high"` (with quotes) in `tlp.conf` and restart TLP
3. If you're on a TTY, switch to a desktop session (you don't have to log in)
3. Plug in the laptop to AC power
4. Wait a few seconds until the computer wouldn't respond. Return to step 4 if the laptop doesn't freeze or turn off after you've waited for a while.

### Additional context

Although I haven't tested it yet, I'm sure that this behavior would also occur on battery if `RADEON_DPM_PERF_LEVEL_ON_BATT` is set to `high` in the config file.

I understand that this can be considered as a kernel- or firmware-related upstream issue (see <https://gitlab.freedesktop.org/drm/amd/-/issues/934>), but the weird thing about this is that it only happens specifically with TLP 1.4.0. Therefore, I would love to see a workaround being implemented until that mentioned upstream bug ticket finally gets fixed.

Here are the specs of my laptop and relevant software details:
- **Model:** Lenovo ThinkPad E595
- **CPU:** AMD Ryzen 7 3700U
- **GPU:** AMD Radeon RX Vega 10 iGPU (Picasso generation)
- **Distribution:** Manjaro
- **Kernel versions:** 5.14.9, 5.10.70
- **linux-firmware version:** 20210919.d526e041 (also occurred with 20210818.c46b8c3 installed)
- **TLP version:** 1.4.0
- **DE:** KDE Plasma 5.22.5
- **Compositor:** KWin
- **Display Manager:** SDDM

**Gist links:**

- [tlp-stat output](https://gist.github.com/acarasimon96/e3e99d1fc9e5490787247ed0fb5d68b9#file-tlp-stat-txt)
- [Part of `journalctl` logs around the time of graphics reset episode](https://gist.github.com/acarasimon96/e3e99d1fc9e5490787247ed0fb5d68b9#file-journal-txt)

**Comment by linrunner** [comment]
You're right, I consider this a kernel (or firmware) bug. I do not plan to implement a workaround. TLP would consist of nothing else if I did this every time.
