### ISSUE TITLE
Fan turning on and off constantly on Lenovo Thinkpad T580.

### ISSUE THREAD

**Issue by SuperSentient** [linrunner/TLP#591]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**
Ever since the last update for TLP my laptop fan has been going on and off constantly.

Fan not working properly going from idle to full power for fan every few seconds. 

**Expected behavior**
In the past the fan would go on and off every few minutes or so.

How the fan worked in the past. 

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Does the problem occur on battery or AC or both? Battery.
2. Actions to reproduce the behaviour
3. Shell commands entered and their output
4. **Full output of `tlp-stat` via https://gist.github.com/ for *all*
   matching cases of 1.** 

--- TLP 1.4.0 --------------------------------------------

+++ Configured Settings:
defaults.conf L0004: TLP_ENABLE="1"
defaults.conf L0005: TLP_WARN_LEVEL="3"
defaults.conf L0006: TLP_PERSISTENT_DEFAULT="0"
defaults.conf L0007: DISK_IDLE_SECS_ON_AC="0"
defaults.conf L0008: DISK_IDLE_SECS_ON_BAT="2"
defaults.conf L0009: MAX_LOST_WORK_SECS_ON_AC="15"
defaults.conf L0010: MAX_LOST_WORK_SECS_ON_BAT="60"
defaults.conf L0011: CPU_ENERGY_PERF_POLICY_ON_AC="balance_performance"
defaults.conf L0012: CPU_ENERGY_PERF_POLICY_ON_BAT="balance_power"
defaults.conf L0013: SCHED_POWERSAVE_ON_AC="0"
defaults.conf L0014: SCHED_POWERSAVE_ON_BAT="1"
defaults.conf L0015: NMI_WATCHDOG="0"
defaults.conf L0016: DISK_DEVICES="nvme0n1 sda"
defaults.conf L0017: DISK_APM_LEVEL_ON_AC="254 254"
defaults.conf L0018: DISK_APM_LEVEL_ON_BAT="128 128"
defaults.conf L0019: DISK_APM_CLASS_DENYLIST="usb ieee1394"
defaults.conf L0020: DISK_IOSCHED="keep keep"
defaults.conf L0021: SATA_LINKPWR_ON_AC="med_power_with_dipm max_performance"
defaults.conf L0022: SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"
defaults.conf L0023: AHCI_RUNTIME_PM_ON_AC="on"
defaults.conf L0024: AHCI_RUNTIME_PM_ON_BAT="auto"
defaults.conf L0025: AHCI_RUNTIME_PM_TIMEOUT="15"
defaults.conf L0026: PCIE_ASPM_ON_AC="default"
defaults.conf L0027: PCIE_ASPM_ON_BAT="default"
defaults.conf L0028: RADEON_DPM_PERF_LEVEL_ON_AC="auto"
defaults.conf L0029: RADEON_DPM_PERF_LEVEL_ON_BAT="auto"
defaults.conf L0030: RADEON_POWER_PROFILE_ON_AC="default"
defaults.conf L0031: RADEON_POWER_PROFILE_ON_BAT="default"
defaults.conf L0032: WIFI_PWR_ON_AC="off"
defaults.conf L0033: WIFI_PWR_ON_BAT="on"
defaults.conf L0034: WOL_DISABLE="Y"
defaults.conf L0035: SOUND_POWER_SAVE_ON_AC="1"
defaults.conf L0036: SOUND_POWER_SAVE_ON_BAT="1"
defaults.conf L0037: SOUND_POWER_SAVE_CONTROLLER="Y"
defaults.conf L0038: BAY_POWEROFF_ON_AC="0"
defaults.conf L0039: BAY_POWEROFF_ON_BAT="0"
defaults.conf L0040: BAY_DEVICE="sr0"
defaults.conf L0041: RUNTIME_PM_ON_AC="on"
defaults.conf L0042: RUNTIME_PM_ON_BAT="auto"
defaults.conf L0043: RUNTIME_PM_DRIVER_DENYLIST="mei_me nouveau radeon"
defaults.conf L0044: USB_AUTOSUSPEND="1"
defaults.conf L0045: USB_EXCLUDE_AUDIO="1"
defaults.conf L0046: USB_EXCLUDE_BTUSB="0"
defaults.conf L0047: USB_EXCLUDE_PHONE="0"
defaults.conf L0048: USB_EXCLUDE_PRINTER="1"
defaults.conf L0049: USB_EXCLUDE_WWAN="0"
defaults.conf L0050: USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN="0"
defaults.conf L0051: RESTORE_DEVICE_STATE_ON_STARTUP="0"
defaults.conf L0052: RESTORE_THRESHOLDS_ON_BAT="0"
defaults.conf L0053: NATACPI_ENABLE="1"
defaults.conf L0054: TPACPI_ENABLE="1"
defaults.conf L0055: TPSMAPI_ENABLE="1"

+++ System Info
System         = LENOVO ThinkPad T580 20L9001VUS
BIOS           = N27ET36W (1.22 )
OS Release     = Linux Mint 19.2
Kernel         = 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-4.15.0-159-generic root=UUID=bc17c57b-1beb-49a6-8e41-d0d8beb0c5ea ro quiet splash vt.handoff=1
Init system    = systemd v237
Boot mode      = UEFI

+++ TLP Status
State          = enabled
RDW state      = not installed
Last run       = 03:33:26 PM,    392 sec(s) ago
Mode           = battery
Power source   = battery

+++ Processor
CPU model      = Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = performance powersave
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  3400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference = balance_power [HWP.EPP]
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 

/sys/devices/system/cpu/cpu1..cpu7: omitted for clarity, use -v to show all

/sys/devices/system/cpu/intel_pstate/status            = active
/sys/devices/system/cpu/intel_pstate/min_perf_pct      =  11 [%]
/sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
/sys/devices/system/cpu/intel_pstate/no_turbo          =   0
/sys/devices/system/cpu/intel_pstate/hwp_dynamic_boost = (not available)
/sys/devices/system/cpu/intel_pstate/turbo_pct         =  59 [%]
/sys/devices/system/cpu/intel_pstate/num_pstates       =  31

/sys/module/workqueue/parameters/power_efficient       = Y
/proc/sys/kernel/nmi_watchdog                          = 0

+++ Platform Profile
/sys/firmware/acpi/platform_profile                    = (not available)
/sys/firmware/acpi/platform_profile_choices            = (not available)
/sys/devices/platform/thinkpad_acpi/dytc_lapmode       = (not available)

+++ Temperatures
CPU temp               =    35 [°C]
/proc/acpi/ibm/fan     =     0 [/min]

+++ File System
/proc/sys/vm/laptop_mode               =     2
/proc/sys/vm/dirty_writeback_centisecs =  6000
/proc/sys/vm/dirty_expire_centisecs    =  6000
/proc/sys/vm/dirty_ratio               =    20
/proc/sys/vm/dirty_background_ratio    =    10

+++ Disks
Devices = nvme0n1 sda

/dev/nvme0n1: not present.

/dev/sda:
  Type       = SATA
  Disk ID    = ata-TOSHIBA_MQ01ACF050_39RKTD35T
  Model      = TOSHIBA MQ01ACF050                      
  Firmware   = AV0A3E  
  APM Level  = 128
  Status     = active/idle
  Host       = host3
  Scheduler  = noop deadline [cfq] (single queue)

  Runtime PM:
    /sys/block/sda/power/control = auto, autosuspend_delay_ms = 15000

  SMART info:
      4 Start_Stop_Count          =      315 
      5 Reallocated_Sector_Ct     =        0 
      9 Power_On_Hours            =       76 [h]
     12 Power_Cycle_Count         =      281 
    191 G-Sense_Error_Rate        =        7 
    193 Load_Cycle_Count          =     1158 
    194 Temperature_Celsius       =       27 (Min/Max 21/44)  [°C]

+++ AHCI Link Power Management (ALPM) :: SATA Links
/sys/bus/pci/devices/0000:00:17.0/ata1/host1/scsi_host/host1/link_power_management_policy = med_power_with_dipm 
/sys/bus/pci/devices/0000:00:17.0/ata2/host2/scsi_host/host2/link_power_management_policy = med_power_with_dipm 
/sys/bus/pci/devices/0000:00:17.0/ata3/host3/scsi_host/host3/link_power_management_policy = med_power_with_dipm  -- sda

+++ AHCI Port Runtime Power Management :: SATA/ATA Ports
/sys/bus/pci/devices/0000:00:17.0/ata1/power/control     = auto 
/sys/bus/pci/devices/0000:00:17.0/ata2/power/control     = auto 
/sys/bus/pci/devices/0000:00:17.0/ata3/power/control     = auto  -- sda

+++ Docks and Device Bays
/sys/devices/platform/dock.0: battery_bay   = battery present

+++ Intel Graphics
/sys/class/drm/card0/device/driver           = i915

/sys/class/drm/card0/power/rc6_enable        =  1 (enabled)
/sys/kernel/debug/dri/0/i915_fbc_status      = FBC disabled: FBC enabled (active or scheduled)
/sys/module/i915/parameters/enable_psr       =  0 (disabled)

/sys/class/drm/card0/gt_min_freq_mhz         =   300 [MHz]
/sys/class/drm/card0/gt_max_freq_mhz         =  1100 [MHz]
/sys/class/drm/card0/gt_boost_freq_mhz       =  1100 [MHz]
/sys/class/drm/card0/gt_RPn_freq_mhz         =   300 [MHz] (GPU min)
/sys/class/drm/card0/gt_RP0_freq_mhz         =  1100 [MHz] (GPU max)

+++ Wireless
bluetooth = off (software)
wifi      = on
wwan      = none (no device)

wlp4s0(iwlwifi)               : wifi, connected, power management = on

+++ Audio
/sys/module/snd_hda_intel/parameters/power_save            = 1
/sys/module/snd_hda_intel/parameters/power_save_controller = Y

+++ PCIe Active State Power Management
/sys/module/pcie_aspm/parameters/policy = [default] performance powersave powersupersave

+++ PCIe Runtime Power Management
Enable devices    = (disabled)
Disable devices   = (disabled)
Device denylist   = (disabled)
Driver denylist   = mei_me nouveau radeon

/sys/bus/pci/devices/0000:00:00.0/power/control = auto (0x060000, Host bridge, skl_uncore)
/sys/bus/pci/devices/0000:00:02.0/power/control = auto (0x030000, VGA compatible controller, i915)
/sys/bus/pci/devices/0000:00:04.0/power/control = auto (0x118000, Signal processing controller, proc_thermal)
/sys/bus/pci/devices/0000:00:08.0/power/control = auto (0x088000, System peripheral, no driver)
/sys/bus/pci/devices/0000:00:14.0/power/control = auto (0x0c0330, USB controller, xhci_hcd)
/sys/bus/pci/devices/0000:00:14.2/power/control = auto (0x118000, Signal processing controller, intel_pch_thermal)
/sys/bus/pci/devices/0000:00:16.0/power/control = auto (0x078000, Communication controller, mei_me)
/sys/bus/pci/devices/0000:00:17.0/power/control = auto (0x010601, SATA controller, ahci)
/sys/bus/pci/devices/0000:00:1c.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1c.6/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1d.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:00:1f.0/power/control = auto (0x060100, ISA bridge, no driver)
/sys/bus/pci/devices/0000:00:1f.2/power/control = auto (0x058000, Memory controller, no driver)
/sys/bus/pci/devices/0000:00:1f.3/power/control = auto (0x040300, Audio device, snd_hda_intel)
/sys/bus/pci/devices/0000:00:1f.4/power/control = auto (0x0c0500, SMBus, no driver)
/sys/bus/pci/devices/0000:00:1f.6/power/control = auto (0x020000, Ethernet controller, e1000e)
/sys/bus/pci/devices/0000:04:00.0/power/control = auto (0x028000, Network controller, iwlwifi)
/sys/bus/pci/devices/0000:07:00.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:08:00.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:08:01.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:08:02.0/power/control = auto (0x060400, PCI bridge, pcieport)
/sys/bus/pci/devices/0000:09:00.0/power/control = auto (0x088000, System peripheral, thunderbolt)
/sys/bus/pci/devices/0000:3f:00.0/power/control = auto (0x0c0330, USB controller, xhci_hcd)

+++ USB
Autosuspend       = enabled
Device allowlist  = (not configured)
Device denylist   = (not configured)
Exclude audio     = enabled
Exclude bluetooth = disabled
Exclude phones    = disabled
Exclude printers  = enabled
Exclude WWAN      = disabled

Bus 004 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 3.0 root hub (hub)
Bus 003 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 2.0 root hub (hub)
Bus 002 Device 002 ID 0bda:0316 control = auto, autosuspend_delay_ms = 2000 -- Realtek Semiconductor Corp. (usb-storage)
Bus 002 Device 001 ID 1d6b:0003 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 3.0 root hub (hub)
Bus 001 Device 005 ID 06cb:009a control = auto, autosuspend_delay_ms = 2000 -- Synaptics, Inc. (no driver)
Bus 001 Device 004 ID 13d3:56a6 control = auto, autosuspend_delay_ms = 2000 -- IMC Networks (uvcvideo)
Bus 001 Device 002 ID 046d:c52f control = on,   autosuspend_delay_ms = 2000 -- Logitech, Inc. Unifying Receiver (usbhid)
Bus 001 Device 001 ID 1d6b:0002 control = auto, autosuspend_delay_ms =    0 -- Linux Foundation 2.0 root hub (hub)

+++ Battery Care
Plugin: thinkpad
Supported features: charge thresholds, recalibration
Driver usage:
* natacpi (thinkpad_acpi) = inactive (ThinkPad not supported)
* tpacpi-bat (acpi_call)  = active (charge thresholds, recalibration)
Parameter value ranges:
* START_CHARGE_THRESH_BAT0/1:  0(off)..96(default)..99
* STOP_CHARGE_THRESH_BAT0/1:   1..100(default)

+++ ThinkPad Battery Status: BAT0 (Main / Internal)
/sys/class/power_supply/BAT0/manufacturer                   = SMP
/sys/class/power_supply/BAT0/model_name                     = 00UR891
/sys/class/power_supply/BAT0/cycle_count                    =      7
/sys/class/power_supply/BAT0/energy_full_design             =  32010 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  30820 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  30570 [mWh]
/sys/class/power_supply/BAT0/power_now                      =      0 [mW]
/sys/class/power_supply/BAT0/status                         = Idle

tpacpi-bat.BAT0.startThreshold                              =      0 [%]
tpacpi-bat.BAT0.stopThreshold                               =    100 [%]
tpacpi-bat.BAT0.forceDischarge                              =      0

Charge                                                      =   99.2 [%]
Capacity                                                    =   96.3 [%]

+++ ThinkPad Battery Status: BAT1 (Ultrabay / Slice / Replaceable)
/sys/class/power_supply/BAT1/manufacturer                   = LGC
/sys/class/power_supply/BAT1/model_name                     = 01AV490
/sys/class/power_supply/BAT1/cycle_count                    =     18
/sys/class/power_supply/BAT1/energy_full_design             =  23940 [mWh]
/sys/class/power_supply/BAT1/energy_full                    =  22380 [mWh]
/sys/class/power_supply/BAT1/energy_now                     =  14510 [mWh]
/sys/class/power_supply/BAT1/power_now                      =   7544 [mW]
/sys/class/power_supply/BAT1/status                         = Discharging

tpacpi-bat.BAT1.startThreshold                              =      0 [%]
tpacpi-bat.BAT1.stopThreshold                               =    100 [%]
tpacpi-bat.BAT1.forceDischarge                              =      0

Charge                                                      =   64.8 [%]
Capacity                                                    =   93.5 [%]

+++ Charge total                                            =   84.7 [%]

**Additional context**

**Comment by linrunner** [comment]
So how do you want to proceed? I don't see evidence for a regression in TLP yet.

**Comment by linrunner** [comment]
I consider the issue as completed. Report here if there are any new findings.
