### ISSUE TITLE
TLP does not switch between AC and battery automatically.

### ISSUE THREAD

**Issue by Samisafool** [linrunner/TLP#592]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

TLP does not switch between AC and battery automatically.

**Expected behavior**

It should switch between the two automatically.

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Start TLP on AC
2. Run ````tlp-stat````
3. See mode is AC
4. Disconnect AC
5. Run ````tlp-stat````
6. See mode is still AC

And vice-versa

Github gists:
[Started on AC, stat on AC](https://gist.github.com/Samisafool/ed96473f3390b4399e8a6672ae6bdc05)
[Started on AC, stat on battery](https://gist.github.com/Samisafool/dfa8240329b055f927902a293758efe3)
[Started on battery, stat on battery](https://gist.github.com/Samisafool/3ed9280689a9b744d4a104ff256ef24e)
[Started on battery, stat on AC](https://gist.github.com/Samisafool/1713f8c85ec2f773cf5d29be19433b5f)

**Additional context**

Fedora 34, default TLP configuration as far as I'm aware.
Might be related to #147

**Comment by Samisafool** [comment]
After a reboot, this isn't reproducible.

**Comment by linrunner** [comment]
Report back here if there is new evidence.

**Comment by mityax** [comment]
I still have this problem on fedora 38, also with the default tlp settings.

I'm not sure if it's the only case, but I definitely observe this every time my laptop battery is entirely empty and I boot it with the AC cable plugged in (therefore the battery has 0% during boot). The cpu is always in power saving mode then, and doesn't automatically switch back to performance mode.

`sudo tlp auto` or a reboot fixes it.

**Comment by mityax** [comment]
@linrunner thanks for the reply – just to clarify, I should file the bug report in this repo and not in some repo of the fedora distro, right? (sorry for the noob question, I've wanted to be one of the "install tlp and forget it" users and have little clue on it's workings and development :D)

**Comment by linrunner** [comment]
I don't understand where you got the idea that you should open another issue here after I pointed out that I was not responsible.

Fedora bug tracker: https://bugzilla.redhat.com/
Instructions: https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/
Sample SELinux bug: https://bugzilla.redhat.com/show_bug.cgi?id=2013439
