### ISSUE TITLE
Battery Care support for sony-laptop driver

### ISSUE THREAD

**Issue by faithanalog** [linrunner/TLP#594]
I own a Sony Vaio VGN-P588E. This laptop is supported by the [sony-laptop linux kernel driver](https://github.com/torvalds/linux/blob/1d4590f5069bff7d41d7ed1a7e7674fb9d6d502a/drivers/platform/x86/sony-laptop.c), which exposes a couple charging controls:

- `/sys/devices/platform/sony-laptop/battery_care_limiter`
- `/sys/devices/platform/sony-laptop/battery_highspeed_charging`

Seeing battery care support expanded beyond the thinkpad line in 1.4.0, I figured I'd request support for this in TLP.

`/sys/devices/platform/sony-laptop/battery_care_limiter` is an integer from 0-100 indicating a battery percentage. Charging stops when the battery reaches this point. The actual control is very coarse though. Based on [sony_nc_battery_care_limit_store()](https://github.com/torvalds/linux/blob/1d4590f5069bff7d41d7ed1a7e7674fb9d6d502a/drivers/platform/x86/sony-laptop.c#L1986) it looks like the only supported values are `50`, `80`, and `100`. If you write any other value the driver will round up to the next supported value.

`/sys/devices/platform/sony-laptop/battery_highspeed_charging` is either `0` or `1`. In theory, this affects the rate at which the battery can charge. On my device in particular I can't tell subjectively if it has an effect and I haven't measured, but it might be something that works on different devices.

There is no control to set a threshold for when charging starts, only for when it stops.

On my device, both of these values persist through reboot, but I don't know if that's universally true. It looks like some laptops can store battery limit on the embedded controller and some can store it on the battery itself, but in any case the driver doesn't expose that choice.

I referenced it above, but here's another link to the driver code: [sony-laptop.c](https://github.com/torvalds/linux/blob/1d4590f5069bff7d41d7ed1a7e7674fb9d6d502a/drivers/platform/x86/sony-laptop.c)

There is also a documentation file for the driver at `linux/Documentation/admin-guide/laptops/sony-laptop.rst` but I'm not linking it because it's out of date and doesn't have any mention of these battery controls.

Based on the code, it seems this driver more broadly supports any device with a SNY5001 or SNY6001 chip, but I don't have any additional information other than that these are used in parts of the sony vaio product line.

Tangential to this issue, there is also a `/sys/devices/platform/sony-laptop/wwanpower` and `[...]/bluetoothpower` file to control those radios, but that control is also exposed though the generic rfkill interface so don't bother looking into that.

**Comment by linrunner** [comment]
Hi, 

thanks for your hint. I'll schedule _battery_care_limiter_ with supported values 50, 80, and 100 for the next release. Please stay tuned to test on your hardware.

**Comment by faithanalog** [comment]
hey, they thanks for the reply. I have some additional info after further testing, and i know this is weird but it is what it is:

On my device, setting a battery limit of 100 seems to be functionally equivalent to setting a battery limit of 80, that is, it caps out at 80% charge. To actually let the battery charge to 100%, I have to set a limit of 0, which I believe tells the controller to disable the battery care feature entirely.

Not sure if thats true of both chips this driver supports, but that's the behavior I've got on my device. It's possible that the value for 100 works on the other chip, or maybe the driver devs just slightly misunderstood the meaning of the bitfield.

Either way,
Writing 0 = charge to 100%
Writing 50 = charge to 50%
Writing 80 = charge to 80%
Writing 100 = also charge to 80%

**Comment by linrunner** [comment]
This can be implemented, thank you for your research.

**Comment by linrunner** [comment]
I would like to know the following for the implementation:

1. When writing 0 to `battery_care_limiter`, what is returned when reading:  100?
2. Which battery device names do Sony laptops expose: BAT0, BAT1?

**Comment by linrunner** [comment]
Please also show the output of `tlp-stat -b` (with current TLP release)

**Comment by faithanalog** [comment]
Here you go! Demo of writing 0 to `battery_care_limiter`, followed by `tlp-stat -b` detecting `BAT0`

```
root@navi:~# echo 0 > /sys/devices/platform/sony-laptop/battery_care_limiter 
root@navi:~# cat /sys/devices/platform/sony-laptop/battery_care_limiter 
0
```

```
root@navi:~# tlp-stat -b
--- TLP 1.4.0 --------------------------------------------

+++ Battery Care
Plugin: generic
Supported features: none available

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = Sony Corporation
/sys/class/power_supply/BAT0/model_name                     = (not available)
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  16800 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  15950 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  13310 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   6855 [mW]
/sys/class/power_supply/BAT0/status                         = Charging

/sys/class/power_supply/BAT0/charge_control_start_threshold = (not available) 
/sys/class/power_supply/BAT0/charge_control_end_threshold   = (not available) 

Charge                                                      =   83.4 [%]
Capacity                                                    =   94.9 [%]
```

**Comment by linrunner** [comment]
Done. Please test with the main branch.

Please provide the output of:

    sudo tlp-stat -s
    sudo tlp setcharge 0 50
    sudo tlp-stat -b
    sudo tlp setcharge 0 80
    sudo tlp-stat -b
    sudo tlp setcharge 0 100
    sudo tlp-stat -b
    sudo tlp setcharge 0 42
    sudo tlp-stat -b

**Comment by faithanalog** [comment]
I put these in a bash script with `set -v` to print the command before results
```
sudo tlp-stat -s
sudo tlp setcharge 0 50
sudo tlp-stat -b
sudo tlp setcharge 0 80
sudo tlp-stat -b
sudo tlp setcharge 0 100
sudo tlp-stat -b
sudo tlp setcharge 0 42
sudo tlp-stat -b
```
results are included at the bottom this reply - looks to be working just fine. I also tried setting `STOP_CHARGE_THRESH_BAT0` in my tlp.conf and it's applying that setting correctly as well. cool!

```
sudo tlp-stat -s
--- TLP 1.4.0 --------------------------------------------

+++ System Info
System         = Sony Corporation J003JFF8 VGN-P588E
BIOS           = R2073U3
OS Release     = Debian GNU/Linux 10 (buster)
Kernel         = 5.10.57-antix.1-486-smp #1 SMP Sun Aug 8 14:07:29 EEST 2021 i686
/proc/cmdline  = root=UUID=53973bfe-d853-428b-a3d3-75a5898249ea ro  
Init system    = sysvinit
Boot mode      = BIOS (CSM, Legacy)

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 12:36:41 AM,    125 sec(s) ago
Mode           = AC
Power source   = AC

sudo tlp setcharge 0 50
Setting temporary charge threshold for all batteries:
  care limiter = 50
sudo tlp-stat -b
--- TLP 1.4.0 --------------------------------------------

+++ Battery Care
Plugin: sony
Supported features: charge threshold
Driver usage:
* vendor (sony_laptop) = active (charge threshold)
Parameter value range:
* STOP_CHARGE_THRESH_BAT0: 50, 80, 100(off) -- battery care limiter

/sys/devices/platform/sony-laptop/battery_care_limiter      =     50 [%]

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = Sony Corporation
/sys/class/power_supply/BAT0/model_name                     = (not available)
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  16800 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  15950 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  12820 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   2183 [mW]
/sys/class/power_supply/BAT0/status                         = Charging

Charge                                                      =   80.4 [%]
Capacity                                                    =   94.9 [%]

sudo tlp setcharge 0 80
Setting temporary charge threshold for all batteries:
  care limiter = 80
sudo tlp-stat -b
--- TLP 1.4.0 --------------------------------------------

+++ Battery Care
Plugin: sony
Supported features: charge threshold
Driver usage:
* vendor (sony_laptop) = active (charge threshold)
Parameter value range:
* STOP_CHARGE_THRESH_BAT0: 50, 80, 100(off) -- battery care limiter

/sys/devices/platform/sony-laptop/battery_care_limiter      =     80 [%]

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = Sony Corporation
/sys/class/power_supply/BAT0/model_name                     = (not available)
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  16800 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  15950 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  12820 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   2183 [mW]
/sys/class/power_supply/BAT0/status                         = Idle

Charge                                                      =   80.4 [%]
Capacity                                                    =   94.9 [%]

sudo tlp setcharge 0 100
Setting temporary charge threshold for all batteries:
  care limiter = 100
sudo tlp-stat -b
--- TLP 1.4.0 --------------------------------------------

+++ Battery Care
Plugin: sony
Supported features: charge threshold
Driver usage:
* vendor (sony_laptop) = active (charge threshold)
Parameter value range:
* STOP_CHARGE_THRESH_BAT0: 50, 80, 100(off) -- battery care limiter

/sys/devices/platform/sony-laptop/battery_care_limiter      =      0 (100) [%]

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = Sony Corporation
/sys/class/power_supply/BAT0/model_name                     = (not available)
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  16800 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  15950 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  12820 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   2183 [mW]
/sys/class/power_supply/BAT0/status                         = Idle

Charge                                                      =   80.4 [%]
Capacity                                                    =   94.9 [%]

sudo tlp setcharge 0 42
Error: care limiter (42) not specified or invalid (must be 50, 80 or 100). Aborted.
sudo tlp-stat -b
--- TLP 1.4.0 --------------------------------------------

+++ Battery Care
Plugin: sony
Supported features: charge threshold
Driver usage:
* vendor (sony_laptop) = active (charge threshold)
Parameter value range:
* STOP_CHARGE_THRESH_BAT0: 50, 80, 100(off) -- battery care limiter

/sys/devices/platform/sony-laptop/battery_care_limiter      =      0 (100) [%]

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = Sony Corporation
/sys/class/power_supply/BAT0/model_name                     = (not available)
/sys/class/power_supply/BAT0/cycle_count                    = (not supported)
/sys/class/power_supply/BAT0/energy_full_design             =  16800 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  15950 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  12820 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   2183 [mW]
/sys/class/power_supply/BAT0/status                         = Charging

Charge                                                      =   80.4 [%]
Capacity                                                    =   94.9 [%]
```

**Comment by linrunner** [comment]
Great.

**Comment by linrunner** [comment]
TLP 1.5 Beta 1 -> https://github.com/linrunner/TLP/issues/609

**Comment by linrunner** [comment]
Beta test is completed and TLP 1.5.0 is [out](https://linrunner.de/tlp/news.html). Have fun!
