### ISSUE TITLE
Wi-Fi power saving mode active while charging

### ISSUE THREAD

**Issue by pflanzenandi** [linrunner/TLP#600]
Wi-Fi power saving mode is active, while the laptop is being charged. 
Removing and plugging the charger back in, sometimes removes the power saving mode.

Checked with _iwconfig_ because the Wi-Fi speed was slow.

[tlp-stat](https://gist.github.com/pflanzenandi/e38620c637d8056c4259989cb33c75d6)

**Comment by linrunner** [comment]
Probably some other tool: NetworkManager, Desktop PM App, ...

**Comment by linrunner** [comment]
May I ask about the cause?

**Comment by pflanzenandi** [comment]
I have not found an explanation. I also do not want to permanently disable the mode. 
I could possibly install the previous TLP version and see if it behaves the same way.
