### ISSUE TITLE
[Coreboot] bat.d/thinkpad: Use feature-detection instead of Model whitelist

### ISSUE THREAD

**Issue by t-8ch** [linrunner/TLP#601]
**Is your feature request related to a problem? Please describe.**

I have a T400 running with Coreboot. Coreboot does not support SMAPI but instead exposes the battery controls via ACPI methods that are handled by thinkpad_acpi.
Currently `bat.d/05-thinkpad` has a list of devices that are hardlocked to SMAPI instead of ACPI which includes the T400.
This leads to battery controls being unavailable in TLP.

**Describe the solution you'd like**

It would be nice if TLP could first check the availability of the actual sysfs files for natacpi to detect its availability and only afterwards consult the hardcoded list.

**Comment by linrunner** [comment]
Oh well, yet another special case ...

Please test and report

    tlp-stat -b

**Comment by t-8ch** [comment]
Thanks, will do! Unfortunately I only will have access to that device sometime next week, so it be a while.

**Comment by t-8ch** [comment]
I can confirm this works, thanks a lot!

**Comment by linrunner** [comment]
Great. Thanks for testing.

**Comment by linrunner** [comment]
TLP 1.5 Beta 1 is out -> https://github.com/linrunner/TLP/issues/609

**Comment by linrunner** [comment]
Beta test is completed and TLP 1.5.0 is [out](https://linrunner.de/tlp/news.html). Have fun!
