### ISSUE TITLE
Stop tlp from interefering with cpu_energy_perf_policy

### ISSUE THREAD

**Issue by throwaway69420-69420** [linrunner/TLP#607]
I want to stop tlp from interefering with cpu_energy_perf_policy so that I can set it manually from power-profiles-daemon since kde is shipping it with the desktop environment now.

**Comment by linrunner** [comment]
Configure 

    CPU_ENERGY_PERF_POLICY_ON_AC=
    CPU_ENERGY_PERF_POLICY_ON_BAT=

Before you misuse the issue tracker again for a pure support question, i expect you to have read the documentation. 

The [settings intro](https://linrunner.de/tlp/settings/introduction.html#parameter-syntax) states:

> Parameters with intrinsic default may be disabled by entering an empty string: RUNTIME_PM_DRIVER_DENYLIST=""

**/etc/tlp.conf** states
>  - Default *: intrinsic default that is effective when the parameter is missing
>      or disabled by a leading '#'; **use PARAM="" to disable an intrinsic default**

Thanks for your attention.
