### ISSUE TITLE
Battery care for MSI

### ISSUE THREAD

**Issue by salva09** [linrunner/TLP#610]
Is there a way for MSI laptops to be supported? I saw somewhere else (I don't remember exactly) what was the exact registry in the EC to change the thresholds, but I don't think there's a module like the others brands. There's also OpenFreezeCenter, but it doesn't work very well and isn't packaged properly.

**Comment by linrunner** [comment]
If you want that, you have to show a viable way. TLP needs a kernel interface e.g. sysfs nodes like

    /sys/class/power_supply/BAT0/charge_control_start_threshold
    /sys/class/power_supply/BAT0/charge_control_end_threshold

or similar. To the best of my knowledge there is no such thing for MSI.
