### ISSUE TITLE
[manjaro] Removed TLP but the threshold is still alive. 

### ISSUE THREAD

**Issue by Lolis4TheWin** [linrunner/TLP#611]
I uninstalled tlp and tlpui via pacman gui (or what is that called), but the battery threshold is still there. How could i remove it? 

I lost battery performance with tlp, and i want to try something else, but this annoys me. 

What could i do? I removed the config too and tryed restarting.

**Comment by linrunner** [comment]
The issue tracker is not a support forum. Please see the [FAQ](https://linrunner.de/tlp/faq/battery.html#how-do-i-disable-the-charge-thresholds).
