### ISSUE TITLE
Removing tlp with battery thresholds 

### ISSUE THREAD

**Issue by dsyzling** [linrunner/TLP#617]
I've been forced to remove tlp with archlinux and gnome due to conflicts with power-profile-daemon. Since I have a thinkpad laptop I'd been using battery thresholds. These thresholds still remain after the removal of tlp and with the lack of support in power-profile-daemon I now find myself with no way to reset or control these thresholds - especially forcing the laptop to recharge fully if need be. 

Is this a known issue, should I have reset the thresholds before uninstalling? If I remove acpi_call as well will this reset the thresholds? Or do I have to temporarily remove and reinstall the battery?

Alternatively given I've removed tlp and tlp-rdw for now and was happy with the performance, should I mask the power-profile-daemon and reinstall tlp - I assume there's no ongoing conflict between these packages - just if you prefer the power profiles to be controlled through the gnome gui and bar?

**Comment by linrunner** [comment]
Hi, 

disabling the thresholds is described in the [FAQ](https://linrunner.de/tlp/faq/battery.html#how-do-i-disable-the-charge-thresholds). How they work and why they are retained after uninstallation is also explained in several places there.

Distribution packages for TLP 1.5 intentionally include power-profiles-daemon as a conflict. Masking the service only leads to consequential problems within power-profiles-daemon.

Please ask support questions in the forum of your distribution (or in another Linux forum of your choice). The issue tracker is reserved for bug reports. Thanks for your understanding.
