### ISSUE TITLE
[Huawei MateBook] keeps charge at STOP_CHARGE_THRESH_BAT0 value

### ISSUE THREAD

**Issue by muikku** [linrunner/TLP#624]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

When I have configured values like this:
START_CHARGE_TRESH_BAT0=10
STOP_CHARGE_TRESH_BAT0=80

I expected battery to drop to 10% then charging to 80%, right?
But it never goes below 80%

**To Reproduce**

Steps to reproduce the unexpected behavior:
I installed tlp, config start and stop values like above, start tlp, observe battery charge and tlp-status
https://gist.github.com/muikku/35248ec389dad1c93e94ab504bf96006

**Comment by linrunner** [comment]
Hi, 

please check the FAQ _carefully_ before opening on issue:

- [Why does the battery not start to discharge when the stop threshold is reached during charging?](https://linrunner.de/tlp/faq/battery.html#why-does-the-battery-not-start-to-discharge-when-the-stop-threshold-is-reached-during-charging)
- [How to choose good battery charge thresholds?](https://linrunner.de/tlp/faq/battery.html#how-to-choose-good-battery-charge-thresholds)
 
Thanks.
