### ISSUE TITLE
Gigabyte Aero battery driver? Battery care works in Windows...

### ISSUE THREAD

**Issue by truvatech** [linrunner/TLP#625]
Found a Gigabyte Kernel, but with only a dozen or so supported models.

What is crazy is on Windows, Gigabyte offers a "control panel" software that allows to limit the battery charging threshhold, like TLP, and when that is set in Windows, it actually saves and stops charging at that threshold even when booting into Linux, so this must be set somewhere at the BIOs level?! Is this possible?

My point is, Gigabyte offers this feature in Windows, so could it mean it would be relatively easy to implement this with TLP?

I know it is probably not a common laptop, but the setting for some reason stopped working, and I am trying to avoid Windows and ideally won't need to dualboot in the near-future, so would like to know if there is a relatively easy way to get this feature to work from within Linux with TLP.

Thank you,
My laptop is Gigabyte Aero 15x
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/platform/x86/gigabyte-wmi.c?id=HEAD

**Comment by linrunner** [comment]
Hi. This kernel driver obviously does not contain _charge_control_ options. So there is no point in opening an issue here, you would have to contact the maintainer of the kernel driver if he wants to develop something. I can't help you here.
