### ISSUE TITLE
Setting the CPI scaling governor does not work (in BAT and AC mode)

### ISSUE THREAD

**Issue by LukasPietzschmann** [linrunner/TLP#632]
I want to set the cpu scaling governor depending on whether my laptop is plugged in, or not.
Therefor I use the following two settings in my /etc/tlp.conf file (full config file: https://gist.github.com/LukasPietzschmann/e68ef374c1906a9bb2a15355a59b6fdd):
```
CPU_SCALING_GOVERNOR_ON_AC=ondemand
CPU_SCALING_GOVERNOR_ON_BAT=powersave
```
I already rebooted several times, but the scaling governor doesn't get set at all, as it stays at schedutil (which was already set, before I installed tlp). I'm not sure if I configured something wrong, or if this just does not work with my system.
`sudo tlp-stat` shows the following: https://gist.github.com/LukasPietzschmann/40140ca1320ea932e02cbecb3802ed31

**Comment by linrunner** [comment]
Hi, the `tlp-stat` output shows that your two settings for the governor are not recognised by TLP. The most common reason for this is that the leading `#` in **tlp.conf** was not removed. Is this your actual and complete **tlp.conf** or a manually created extract?
