### ISSUE TITLE
Warnings in journal about systemd-rfkill.service/socket even though RDW is not enabled

### ISSUE THREAD

**Issue by VorpalBlade** [linrunner/TLP#639]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

In the system journal I get a lot (like 10x per boot up?) of these messages:
```
May 22 10:40:27 hostname tlp[1108]: Warning: systemd-rfkill.service is not masked, radio device switching may not work as configured.
May 22 10:40:27 hostname tlp[1108]: >>> Invoke 'systemctl mask systemd-rfkill.service' to correct this.
May 22 10:40:27 hostname tlp[1108]: Warning: systemd-rfkill.socket is not masked, radio device switching may not work as configured.
May 22 10:40:27 hostname tlp[1108]: >>> Invoke 'systemctl mask systemd-rfkill.socket' to correct this.
May 22 10:40:27 hostname tlp[1149]: Warning: systemd-rfkill.service is not masked, radio device switching may not work as configured.
May 22 10:40:27 hostname tlp[1149]: >>> Invoke 'systemctl mask systemd-rfkill.service' to correct this.
May 22 10:40:27 hostname tlp[1149]: Warning: systemd-rfkill.socket is not masked, radio device switching may not work as configured.
May 22 10:40:27 hostname tlp[1149]: >>> Invoke 'systemctl mask systemd-rfkill.socket' to correct this.
```

However I don't have any radio device management enabled in tlp. All I have enabled outside the stock config is Thinkpad battery management. In fact I only installed the `tlp` package in Arch Linux, not the `tlp-rdw`. Thus I believe this warning is incorrect.

**Expected behavior**

If the feature is not enabled, the warning shouldn't be displayed. It should especially not be displayed a total of 30(!) times per boot up! This spams the system log and makes it harder to find actually relevant warnings from other services.

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Does the problem occur on battery or AC or both?: Both
2. Actions to reproduce the behaviour
    1. Install tlp and don't change default config. Do not install tlp-rdw
    2. Enable tlp.service with systemctl
    3. Reboot and check `journalctl -b -p warning`
    4. Observe spurious warnings
5. Shell commands entered and their output
     `journalctl -b -p warning | grep tlp`: Output is above
7. **Full output of `tlp-stat` via https://gist.github.com/ for *all*
   matching cases of 1** (not as file attachment, no screenshots): https://gist.github.com/VorpalBlade/5ed30d1a231da9ed1cf79d364be30c29

**Additional context**

* Laptop is a Thinkpad T480 with switchable nvidia/intel graphics.
* OS is Arch Linux
* tlp package version is 1.5.0-5.

**Comment by VorpalBlade** [comment]
I disagree, since I don't have any of the mentioned options enabled. So the warning should be issued dynamically based on *if* I'm using that config option specifically, not based on if it possible I *might* use that config option.

And if I am using one of those options by mistake I want to be told *which* one is causing it so I can disable that config option.

**Comment by VorpalBlade** [comment]
I had a look at the code and I believe what is needed is for the `$RFKILL_SERVICES` case in check_services_activation_status to be conditioned on those relevant options being enabled, and skip the warning if not. I might make a PR for this later.

Possibly tlp-stat should still show something though, with a note that the *current* config options don't conflict.

I suggest a read only associative array (if bash can do that, I'm more used to zsh) in `tlp-func-base.in` listing the config options and what values they must have to be disabled. If the config options have different values than that allowlist, display the warning, and also tell the user which is the offending config option.

**Comment by linrunner** [comment]
As I said in #640: I insist on a complete installation for support reasons, otherwise you get these warnings. If only the syslog bothers you, why don't you suppress the warnings with `TLP_WARN_LEVEL=2`?

But to accommodate you, for 1.6 I will consider if and how I can move all rfkill features to **tlp-rdw**.

**Comment by VorpalBlade** [comment]
> As I said in https://github.com/linrunner/TLP/pull/640: I insist on a complete installation for support reasons, otherwise you get these warnings. If only the syslog bothers you, why don't you suppress the warnings with TLP_WARN_LEVEL=2?

I was not aware of this. And yes, it is only the syslog thing that bothers me. I will try that option.

**Comment by linrunner** [comment]
I have now solved the issue so that users who have not configured the affected settings are not annoyed by warnings.

Please test with the main branch and report.

**Comment by linrunner** [comment]
Hi @VorpalBlade : TLP 1.6 Beta 1 is out and contains the change -> https://github.com/linrunner/TLP/issues/700

**Comment by linrunner** [comment]
Beta test is completed and TLP 1.6.0 is [out](https://linrunner.de/tlp/news.html). Have fun!

Sincere thanks to all testers! :+1:
