### ISSUE TITLE
TLP on Hp laptop ProBook

### ISSUE THREAD

**Issue by dwarning** [linrunner/TLP#648]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

Using the HP ProBook 6440b I activated in /etc/tpl.conf

START_CHARGE_THRESH_BAT0=75
STOP_CHARGE_THRESH_BAT0=80

But for tlp-stat -b I got:
sudo tlp-stat -b
--- TLP 1.5.0 --------------------------------------------

+++ Battery Care
Plugin: generic
Supported features: none available

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   = Hewlett-Packard
/sys/class/power_supply/BAT0/model_name                     = Primary
/sys/class/power_supply/BAT0/cycle_count                    =      0 (or not supported)
/sys/class/power_supply/BAT0/charge_full_design             =   6361 [mAh]
/sys/class/power_supply/BAT0/charge_full                    =   6361 [mAh]
/sys/class/power_supply/BAT0/charge_now                     =   6361 [mAh]
/sys/class/power_supply/BAT0/current_now                    =      0 [mA]
/sys/class/power_supply/BAT0/status                         = Full

/sys/class/power_supply/BAT0/charge_control_start_threshold = (not available) 
/sys/class/power_supply/BAT0/charge_control_end_threshold   = (not available) 

Charge                                                      =  100.0 [%]
Capacity                                                    =  100.0 [%]

Did that mean that HP Probook is not supported for for battery care? What are the requirements to support this? Special driver or kernel features?

**Comment by linrunner** [comment]
Hi. The documentation already addresses your question:

> **Prerequisites**
> In order to use charge thresholds or recalibration with TLP:
> *  The hardware must have the appropriate capability
> *  A suitable kernel driver must make these capabilities usable under Linux
>
> As for obtaining kernel drivers, there are two options:
> *  Drivers that are maintained in the Linux kernel and shipped with each distribution. They are loaded automatically on supported laptops and do not require any user action.
> *  So-called “external kernel drivers”, which are not part of the Linux kernel and require the user to install additional, distribution specific packages. This case applies to ThinkPads only and is described in Installation.
>Note
> If the hardware does not have the capability or no suitable driver exists, then TLP battery care cannot control it. *Please do not submit issues for hardware lacking kernel driver support for charge control options. Providing kernel drivers is not part of the TLP project.*
>
> [...]
>
> **Unsupported Hardware**
> For all laptop vendors/brands without charge control options the output of tlp-stat -b looks like this:
> `+++ Battery Care`
`Plugin: generic`
 `Supported features: none available`

[Battery Care Vendor Specifics](https://linrunner.de/tlp/settings/bc-vendors.html)
