### ISSUE TITLE
⌨️💡Keyboard light on when laptop sleep🛌

### ISSUE THREAD

**Issue by KwaraMiguel** [linrunner/TLP#655]
👋 i have Lenovo ideapad gaming 3 and the keyboard remain on when i don't use it for sometime and the screen goes `off.unlike`  the normal suspension which usually turn off both screen and keyboard light.please you modify the code to also turn off the keyboard light when it goes to sleep.
🙏 Thanks for you time and have a good day

**Comment by linrunner** [comment]
Hi, 

screen and keyboard backlight are controlled by the graphical desktop environment. On my laptops (with GNOME) the keyboard backlight goes off as soon as the screen turns off.

TLP is not aware what happens in the GUI and does not know when, for example, the screen is locked or turn off. TLP also principally does not make changes to things controlled by the desktop. This avoids conflicts and makes it transparent for the user what controls what.

In your case you have to look into the desktop environment. Maybe a kernel interface to control your hardware is missing.
