### ISSUE TITLE
Possible to disable wifi at suspend and renable it at resume with tlp?

### ISSUE THREAD

**Issue by Ottaviocr** [linrunner/TLP#659]
I have been having problems with my Thinkpads (all of them running Debian stable) randomly waking up from suspend (to ram) after 5-6 hours. After long troubleshoots, it looks like this may be caused by the wifi card waking up the system. This is not caused by ltp but I wonder if tlp can be configured to disable wifi just before suspending and turn it on again after resuming, without fiddling with systemctl or other init scripts.

<pre>
$ uname -a
Linux t440 6.0.0-0.deb11.2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.3-1~bpo11+1 (2022-10-29) x86_64 GNU/Linux

$ cat /etc/debian_version 
11.2

$ dpkg -l|grep tlp
ii  tlp                                               1.5.0-1~bpo11+1                        all          Optimize laptop battery life
ii  tlp-rdw                                           1.5.0-1~bpo11+1                        all          Radio device wizard

$ cat /proc/acpi/wakeup 
Device	S-state	  Status   Sysfs node
LID	  S4	*enabled   platform:PNP0C0D:00
SLPB	  S3	*enabled   platform:PNP0C0E:00
IGBE	  S4	*disabled  pci:0000:00:19.0
EXP2	  S4	*enabled   pci:0000:00:1c.1
XHCI	  S3	*disabled  pci:0000:00:14.0
EHC1	  S3	*disabled  pci:0000:00:1d.
</pre>

lspci snippet of wifi card

<pre>
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 83)
	Subsystem: Intel Corporation Dual Band Wireless-AC 7260
	Flags: bus master, fast devsel, latency 0, IRQ 50, IOMMU group 12
	Memory at f0400000 (64-bit, non-prefetchable) [size=8K]
	Capabilities: [c8] Power Management version 3
	Capabilities: [d0] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [40] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Device Serial Number 7c-7a-91-ff-ff-ba-29-67
	Capabilities: [14c] Latency Tolerance Reporting
	Capabilities: [154] Vendor Specific Information: ID=cafe Rev=1 Len=014 <?>
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi
</pre>

tlp-stat  here [tlp-stat](https://gist.github.com/Ottaviocr/c63ae1fc4e6391ea7557c20bfad0c0c8)

Let me know if you need any more outputs.

**Comment by linrunner** [comment]
> I wonder if tlp can be configured to disable wifi just before suspending and turn it on again after resuming

This is a kernel orhardware issue and I do not want to add yet another workaround for that in TLP. Sorry.

**Comment by Ottaviocr** [comment]
For posterity, I created a file in /lib/systemd/system-sleep/custom

<pre>
#!/bin/sh

case $1 in
    pre)  /usr/bin/wifi off     
                /usr/bin/sleep 5
            ;;
    post) /usr/bin/sleep 5 
           /usr/bin/wifi on
            ;;
esac
</pre>

Make sure you "chmod +x" this file.

**Comment by linrunner** [comment]
Fair enough.
