### ISSUE TITLE
Is it harmful to leave your laptop on ac while `tlp setcharge` is set for long periods of time and/or for heavy loads?

### ISSUE THREAD

**Issue by lukevds** [linrunner/TLP#661]
Sorry if this isn't the appropriate place to ask this. 
I think doing this while the battery charge threshold is set to 40-45% could help preserve the battery, but I'm not sure if energy goes through it and degrades it even more. If it ISN'T harmful, I could help write some documentation about this.

**Comment by linrunner** [comment]
Hi,

in modern laptops, the battery is always used as a buffer for fast load peaks, even on AC. However, this also happens without charging thresholds being set. However, charging thresholds ensure that the battery is not immediately recharged in small increments in this case.

I don't think it's the documentation's job to disprove all sorts of false assumptions about the harmfulness of features or to replace a lecture on electrical engineering. 

Btw: the issue tracker is reserved for bug reports. Please ask hardware questions in an internet forum of your choice. Thanks for your understanding.
