### ISSUE TITLE
Question: How to manually enable wifi when it got disabled by tlp?

### ISSUE THREAD

**Issue by tobip** [linrunner/TLP#663]
Lets say I set this in tlp: 
`DEVICES_TO_DISABLE_ON_STARTUP="bluetooth wifi wwan"`

What would be the proper way to manually enable wifi when I want to use it?
`rfkill` doesn't seem to work in that case.

**Comment by linrunner** [comment]
You may use the NetworkManager applet integrated in most desktop environments or alternatively the TLP command `wifi on` (https://linrunner.de/tlp/usage/radio.html).

For the future I ask you to respect that the issue tracker is reserved for bug reports. Please ask support questions in the forum of your distribution (or in another Linux forum of your choice). Thanks for your understanding.
