### ISSUE TITLE
CPU freqency not going to maximum when setting default governor to performance in Intel CPUs

### ISSUE THREAD

**Issue by OshankKashyap** [linrunner/TLP#677]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/)

## Describe The Bug
TLP is not setting the CPU frequency to maximum when the power is on the battery and the performance governor is set to `performance` in Intel CPUs. The Frequency should be at **3900MHz** but it is stuck at **1833MHz** for some reason. I tried changing the frequency manually but nothing seems to work.

## Expected Behaviour
The maximum frequency of the CPU should be set to **3900MHz** when the device is on battery.

## To Reproduce
1. Does the problem occur on the battery or AC or both? : Battery only
2. Laptop with an Intel Processor.
3. Use This configuration for TLP
```
# Test File
TLP_ENABLE=1

# Battery Configuration
#START_CHARGE_THRESH_BAT0=0
#STOP_CHARGE_THRESH_BAT0=0

# CPU Configuration
CPU_MIN_PERF_ON_AC=10
CPU_MAX_PERF_ON_AC=100
CPU_MIN_PERF_ON_BAT=10
CPU_MAX_PERF_ON_BAT=100

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=1

CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=performance
```

4. Shell command entered - `sudo /usr/local/bin/pstate-frequency --get`
**Output**:
```
pstate-frequency <3.12.0>
    CPU_DRIVER   -> intel_pstate
    CPU_GOVERNOR -> performance
    TURBO        -> 0 [ON]
    CPU_MIN      -> 10% [400MHz]
    CPU_MAX      -> 47% [1833MHz]
```
5. Output of `tlp-stat` - [https://gist.github.com/OshankKashyap/8383261d1ad5765903035aa4fbf7cd7a](https://gist.github.com/OshankKashyap/8383261d1ad5765903035aa4fbf7cd7a)

**Comment by linrunner** [comment]
Your issue cannot be processed without complete outputs as described in the [issue template](https://github.com/linrunner/TLP/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Provide them via https://gist.github.com/ please.
_______________________________________________

**Comment by OshankKashyap** [comment]
Updated! Please check it

**Comment by linrunner** [comment]
I don't see an issue with TLP here, your settings are applied correctly.

I guess the problem is the _intel_pstate_ driver, which does not release the turbo frequencies. Possibly also a restriction imposed by the BIOS. At least nothing that would be in scope here.

**Comment by OshankKashyap** [comment]
I checked my BIOS settings but everything seems to be good in shape. Before TLP I was using this thing [pstate-frequency](https://github.com/pyamsoft/pstate-frequency) and it was able to set the CPU frequency to maximum when on Battery.

Here is the command that I ran -
`sudo /usr/local/bin/pstate-frequency --set --plan performance`

Output:
```
pstate-frequency <3.12.0>
    CPU_DRIVER   -> intel_pstate
    CPU_GOVERNOR -> performance
    TURBO        -> 0 [ON]
    CPU_MIN      -> 10% [400MHz]
    CPU_MAX      -> 100% [3900MHz]
```

Here's the tlp stat - [https://gist.github.com/OshankKashyap/5534c23fd280f620040e1b92e3d8eebf](https://gist.github.com/OshankKashyap/5534c23fd280f620040e1b92e3d8eebf)

**Comment by linrunner** [comment]
I have looked at the pstate-frequency code. Interesting.

It not only writes **/sys/devices/system/cpu/intel_pstate/{min,max}_perf_pct**, but also calculates and writes **/sys/devices/system/cpu/cpu0/cpufreq/scaling_{min.max}_freq** accordingly. 

TLP does not do the latter without additional configuration. With the systems I know so far, it is not necessary.

Try to add the following to your config

```
CPU_SCALING_MIN_FREQ_ON_AC=400000
CPU_SCALING_MAX_FREQ_ON_AC=3900000
CPU_SCALING_MIN_FREQ_ON_BAT=400000
CPU_SCALING_MAX_FREQ_ON_BAT=3900000

```

**Comment by OshankKashyap** [comment]
It is working as expected.
Thanks!

**Comment by linrunner** [comment]
Thanks for your feedback.
