### ISSUE TITLE
Support end of line comments

### ISSUE THREAD

**Issue by OJFord** [linrunner/TLP#681]
**Is your feature request related to a problem? Please describe.**

I was tearing my hair out thinking my drop-in configuration wasn't being read, checking versions, trying `.conf.d` instead (despite the documented and installed `.d` location), removed to `tlp.conf` which then complained it couldn't find it, seemingly supporting that.

I eventually found this little nugget in the docs:
> Comments after parameters are not allowed, the whole line will be silently ignored:
>
> EXAMPLE="dont use like this" # Parameter in front is ignored!

Which is very counter-intuitive, and just silently failing (even though it's documented - I wouldn't think to look for it when it's so common, I know whole-line comments are supported, and it doesn't error).

**Describe the solution you'd like**

I'd like it to be allowed, it's particularly useful in `USB_BLACKLIST` or similar lists of magic numbers:
```
USB_BLACKLIST+="1337:dead" # Acme Keyboard One
USB_BLACKLIST+="1337:beef" # Acme Mouse 3000
```

**Describe alternatives you've considered**

Parse error to make the problem a lot more apparent.

**Additional context**

`tlp-stat -u` would show "(not configured)" after `systemctl restart tlp`.

If you're thinking keyboard & mouse shouldn't be implicitly autosuspended, so shouldn't need blacklisting (I noticed when not configured, they were already `control=on`, not `auto`) - they certainly seemed to be (wouldn't wake from sleep) but not (now working) after adding. Perhaps because they're connected via hubs which _are_ `auto`; is there some detection of 
'parent' hubs that need to also not be autosuspended that applies only to explicitly blacklisted devices or something?

**Comment by linrunner** [comment]
Hi, in fact this is already implemented. Coming with Release 1.6.

https://github.com/linrunner/TLP/blob/main/changelog#L13
https://github.com/linrunner/TLP/commit/135756dbd36c6c980de51fdc1160a499e483a304

**Comment by OJFord** [comment]
Oh fantastic, thanks!

**Comment by linrunner** [comment]
Hi @OJFord  : TLP 1.6 Beta 1 is out and contains the change -> https://github.com/linrunner/TLP/issues/700
