### ISSUE TITLE
TPL and power-profiles-daemon compatability

### ISSUE THREAD

**Issue by E-daw** [linrunner/TLP#686]
**Is your feature request related to a problem? Please describe.**
Currently, power-profiles-daemon is integrated into KDE and Gnome so that users can change their platform profiles with integration into each desktop managers UI. Lenovo laptops use platform profiles to change their bios setting performance modes and this functionality is somewhat important to save battery and get the max performance when necessary. Unfortunately power-profiles-daemon has no where near the same battery saving functionality TLP does. I'm not able to easily set my governers, limit clock speeds and disable turbo, along with all the other features TLP provides. So while I gain the functionality of switching bios performance profiles with PPD, my battery life still suffers because I'm not able to explicitly set a CPU governor or modify turbo settings without writing a script somewhere else in the system. 

I'm not entirely sure why one disables the other when the only conflict is [this](https://github.com/linrunner/TLP/issues/564#issuecomment-909116794) . It can easily be fixed with tlpui and the supposed conflict would be resolved.

Alternatively, I guess TLP could offer the same UI service power-profiles-daemon does by integrating platform profile switching into the ui and system settings of Gnome and KDE.

somewhat off topic from the feature request but why do KDE and Gnome prefer power-profiles-daemon over TLP? Power-profile-daemon has extremely limiting functionality compared to TLP.

**Comment by linrunner** [comment]
Hi,

all settings applied by p-p-d are also found in **tlp.conf**:

1. `CPU_ENERGY_PERF_POLICY_ON_AC/BAT`
2. `CPU_BOOST_ON_AC/BAT` - not active by default
3. `PLATFORM_PROFILE_ON_AC/BAT` - not active by default

So if you enable PLATFORM_PROFILE_ON_AC/BAT and CPU_BOOST_ON_AC/BAT, TLP controls the same settings as p-p-d.

The crucial difference is: TLP implements an "automatic transmission", i.e. depending on the power source the AC or BAT profile is applied, while p-p-d implements a "manual transmission" with three "gears", so to speak.

I have no plans to change TLP's conception in the direction of a "manual transmission".

It's like always in life: you have to choose one or the other. There is no such thing as all the features you want in one tool.
