### ISSUE TITLE
T480 hot swap

### ISSUE THREAD

**Issue by vdbash** [linrunner/TLP#690]
I have a Lenovo T480 with ubuntu 22.04 with main(internal or BAT0) and auxiliary batteries (BAT1). When the device using the external battery (BAT1 discharging), if I remove it I expect the power source automatically switch to main battery and device stays on. But the what actually happens is that the device looses the power and shuts down. Then I can restart the laptop with internal battery. Now if I add the external battery again it does not recognized and tlp-stat tells me that only BAT0 is available.

**Comment by linrunner** [comment]
Which battery is discharged is solely up to Lenovo's embedded controller (EC) firmware, TLP has no control over this.

I recommend resetting the EC using the emergency reset hole on the bottom (refer to the hardware maintenance manual). If this does not help, there is a hardware problem (battery or system board).

**Comment by vdbash** [comment]
Hi
The problem is not which battery discharging, the problem is that it is not
doing a hot swap. When I remove the external battery while the internal
battery has 80% charge, the laptop shouldn't lose power and go off. Anyway,
you can consider it a bug report if you like since you already closed the
thread. I have uninstalled TLP and now I can hot swap

**Comment by vdbash** [comment]
Thanks. Appreciate it.
