### ISSUE TITLE
Should TLP start after multi-user.target?

### ISSUE THREAD

**Issue by AkinoKaede** [linrunner/TLP#697]
When I exec `systemctl start tlp` to start tlp, it will be stucks.  `multi-user.target` was not reached which caused by udev stucks.

I deleted `multi-user.target` in `After` from systemd file, it was fixed.

So should TLP run after multi-user.target?

I had a similar problem with other software. EmixamPP/linux-enable-ir-emitter#101

```
# /usr/lib/systemd/system/tlp.service

# tlp - systemd startup/shutdown service
#
# Copyright (c) 2022 Thomas Koch <linrunner at gmx.net> and others.
# This software is licensed under the GPL v2 or later.

[Unit]
Description=TLP system startup/shutdown
After=NetworkManager.service
Before=shutdown.target
Documentation=https://linrunner.de/tlp

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/tlp init start
ExecReload=/usr/bin/tlp start
ExecStop=/usr/bin/tlp init stop

[Install]
WantedBy=multi-user.target
```

**Comment by AkinoKaede** [comment]
这似乎是因为 systemd-udevd 引起的

**Comment by AkinoKaede** [comment]
This seems to be caused by systemd-udevd

**Comment by AkinoKaede** [comment]
In my view, I think  `multi-user.target` should be reached after TLP started. But TLP will be started after `multi-user.target` .

**Comment by linrunner** [comment]
Hi. Works as designed. `tlp.service` should run as late as possible in the boot process, hence the `After=multi-user.target`. 

Does this happen during boot or only when you start the service manually?

Generally I require complete outputs as described in the [issue template](https://github.com/linrunner/TLP/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Provide them via https://gist.github.com/ please.
______________________________________________

**Comment by linrunner** [comment]
I see. Thanks for the feedback.
