### ISSUE TITLE
CalVer versioning scheme

### ISSUE THREAD

**Issue by up-to-you** [linrunner/TLP#699]
**Is your feature request related to a problem? Please describe.**

TLP releases are infrequent and require users to build and install it from the source

**Describe the solution you'd like**

Switch to CalVer or any other convenient for the Maintainer more frequent versioning scheme

**Your use case(s)**

The Main branch contains tremendous amount of bugfixes/features/hardware support since 1.5.0 release which was published about 1.5 year ago.
Would be nice to obtain all this new stuff as simple package update.

**Comment by linrunner** [comment]
LOL. If it's not fast enough for you, you have to contribute.
