### ISSUE TITLE
EPP doesn't get set on connect/disconnect from the wall, doesn't set the user setting on battery power [ubuntu 22.04(tlp 1.5.0), kernel 6.4] [T14 gen3] [amd-pstate-epp] 

### ISSUE THREAD

**Issue by NavyPurpleVeil** [linrunner/TLP#704]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

EPP is kept at "Performance at all times"

**Expected behavior**

Just like scalling_governor, the setting gets set.

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Install ubuntu 22.04 and 6.4 kernel (used liquorix kernel), add amd_pstate=active in /etc/default/grub, grub-mkconfig.
2. Uncommented EPP setting from /etc/tlp.conf
3. Connect/disconnect the power.

**Additional context**
/etc/tlp.conf
[tlp.conf](https://github.com/linrunner/TLP/files/12409941/tlp.conf.txt)

tlp-state -p
https://gist.github.com/NavyPurpleVeil/01927371fee1800a683983fdaf89e079

**Comment by linrunner** [comment]
Your issue will be processed without **complete** tlp-stat outputs for AC and BAT as described in the [issue template](https://github.com/linrunner/TLP/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Provide them via https://gist.github.com/ please.

**Comment by linrunner** [comment]
Unfortunately I just noticed that you are using amd-pstate. CPU_ENERGY_PERF_POLICY_ON_AC/BAT in TLP 1.5 does not support amd-pstate. This cannot work. Sorry

Please install 1.6-beta.1 and test again -> https://download.linrunner.de/packages/

I still want the full t**lp-stat** outputs for AC and battery (for the beta).

**Comment by linrunner** [comment]
Due to inactivity I'll close here. Please let know if 1.6. works for you.
