### ISSUE TITLE
`START_CHARGE_THRESH_BAT0` value is not taking effect

### ISSUE THREAD

**Issue by MaZED-UP** [linrunner/TLP#715]
# Laptop: Thinkpad E14 Gen4 w/ Intel i5 12th Gen CPU & Nvidia MX550 (disabled).

I have set these values as shown:

```
 532   │ # Battery charge level below which charging will begin.
 533   │ START_CHARGE_THRESH_BAT0=75
 534   │ # Battery charge level above which charging will stop.
 535   │ STOP_CHARGE_THRESH_BAT0=85
```
But when I list the values using `sudo tlp-stat -b` I find that `START_CHARGE_THRESH_BAT0` is set to `0`:

```
--- TLP 1.6.1 --------------------------------------------

+++ Battery Care
Plugin: thinkpad
Supported features: charge thresholds, recalibration
Driver usage:
* natacpi (thinkpad_acpi) = active (charge thresholds, recalibration)
Parameter value ranges:
* START_CHARGE_THRESH_BAT0/1:  0(off)..96(default)..99
* STOP_CHARGE_THRESH_BAT0/1:   1..100(default)
...
/sys/class/power_supply/BAT0/charge_control_start_threshold =      0 [%]
/sys/class/power_supply/BAT0/charge_control_end_threshold   =     85 [%]
/sys/class/power_supply/BAT0/charge_behaviour               = [auto] inhibit-charge force-discharge

Charge                                                      =   84.5 [%]
Capacity                                                    =  101.3 [%]
```
The battery percentage is always at 85% when the laptop is charging and not discharging until it reaches 75% as expected.
Even when I run `sudo tlp setcharge 75 85` nothing changes in the battery report.

**Comment by linrunner** [comment]
Hi. 

> The battery percentage is always at 85% when the **laptop is charging** and not discharging until it reaches 75% **as expected**.

I suspect you are subject to the misunderstanding described in the  [FAQ](https://linrunner.de/tlp/faq/battery.html#faq-discharging-misconception).

If not: a diagnosis is not possible with arbitrarily abbreviated outputs. Your issue will not be processed without **complete** tlp-stat outputs for AC as required by the [template](https://github.com/linrunner/TLP/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). . 

Provide them via https://gist.github.com/ please.
_______________________________________________

**Comment by linrunner** [comment]
https://linrunner.de/tlp/faq/battery.html#tlp-recalibrate-terminates-with-an-error-message
