### ISSUE TITLE
Nvidia Optimus with proprietary driver

### ISSUE THREAD

**Issue by Tarballwalf** [linrunner/TLP#716]
On my system, with an Nvidia card (RTX 3060), `SOUND_POWER_SAVE_ON_AC=1` is required for the GPU to suspend even with the proprietary Nvidia driver.

Documentation [here](https://linrunner.de/tlp/faq/powercon.html#nvidia-optimus-with-nouveau-driver) should to be updated to reflect this for the proprietary driver also.

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Set `SOUND_POWER_SAVE_ON_AC=0`
2. Notice how the GPU will not turn off after unplugging the charger 
3. Set `SOUND_POWER_SAVE_ON_AC=1`
4. GPU will now turn off

[TLP output](https://gist.github.com/Tarballwalf/40816e3a4985cf6c75cff700d7795769)

**Additional context**
Yes, I know sound power save is on in the default configuration, but my stupid ass decided to turn it off. I go by the principal of: if on ac, give it all you can. if on batt, save as much. reading the documentation and seeing that was related to nouveau, I dediced to ignore the setting because it's for nouveau, why would I need it for the Nvidia proprietary driver? for a while I thought it was an Nvidia issue, afterwards I found a fix by forcing RUNTIME PM on ac too. but that was wacky and the GPU would not turn off automatically, booting with the charger plugged.

**Comment by linrunner** [comment]
Hi, interesting. Could you please show `tlp-stat` output on AC too?

**Comment by Tarballwalf** [comment]
Sure.

[TLP AC output](https://gist.github.com/Tarballwalf/a79f6b74a3b11e7a8123ca17bd680b25)

**Comment by linrunner** [comment]
Documentation change done.


Interesting that the power down of the GPU also works with _control = on_. What happens when you configure  `RUNTIME_PM_ON_AC="on"` in addition to `SOUND_POWER_SAVE_ON_AC=1`?

**Comment by Tarballwalf** [comment]
with `RUNTIME_PM_ON_AC="auto"`, GPU will stay powered off even on AC.

Another way this can be done is manually with the pcie ids, using `RUNTIME_PM_ENABLE="01:00.0 01:00.1"`. In this case I have noticed that both the GPU id and the sound controller id needs to be specified. 
This use case is applicable if the user does not wan to append `RUNTIME_PM_ON_AC="auto"` but wants to turn off the GPU on AC.

Here are the tlp outputs for both situations
[TLP with RUNTIME_PM_ON_AC=auto](https://gist.github.com/Tarballwalf/435cd4bd27c3ae512d7393c1f1ce5894)
[TLP with RUNTIME_PM_ENABLE](https://gist.github.com/Tarballwalf/3011c75dd81b3d05b422da66b65029eb)

Both options now will turn of the gpu even when booting with the charger plugged in.

**Comment by linrunner** [comment]
Thanks. I added your further remarks to the docs.

**Comment by Tarballwalf** [comment]
Just a heads up, it's `sure` not `shure` :D
Also I guess we can close this issue for now.

![image](https://github.com/linrunner/TLP/assets/56345519/108a78ee-e10a-41e2-8a6c-8bb5c5bf885a)

**Comment by linrunner** [comment]
Done.
