### ISSUE TITLE
please support screen time 

### ISSUE THREAD

**Issue by newyorkthink** [linrunner/TLP#718]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. Ex. I repeatedly ran into [...]

**Describe the solution you'd like**

A clear and concise description of:

* Your use case(s)
* What you want to happen

**Describe alternatives you've considered**

**Additional context**

Add any other context and references about the feature request here:

* New kernel interfaces: please provide links to the description and usage examples
* Sample shell code

**Comment by linrunner** [comment]
Your request lacks any explanation of what is required. I will not deal with it without further details. Sorry.
