### ISSUE TITLE
 DEVICES_TO_DISABLE_ON_STARTUP doesn't work for wifi

### ISSUE THREAD

**Issue by vrgovinda** [linrunner/TLP#719]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

I have enabled the  DEVICES_TO_DISABLE_ON_STARTUP="bluetooth nfc wifi wwan" line in /etc/tlp.conf

The Bluetooth gets disabled but the WiFi doesn't.

**Expected behavior**

Both should get disabled at startup. 

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Does the problem occur on battery or AC or both?
battery

2. Actions to reproduce the behaviour

- open sudo nano /etc/tlp.conf
- uncomment  DEVICES_TO_DISABLE_ON_STARTUP="bluetooth nfc wifi wwan"
- save and exit.

4. Shell commands entered and their output
5. **Full output of `tlp-stat` via https://gist.github.com/ for *all*
   matching cases of 1** (not as file attachment, no screenshots)

[tlp-stat output](https://gist.github.com/vrgovinda/89b6e15e10514b79cbe6d858c04af77b)

**Additional context**

**Comment by linrunner** [comment]
Does

    wifi off

work?

**Comment by vrgovinda** [comment]
> Does
> 
> ```
> wifi off
> ```
> 
> work?

Do you mean ` DEVICES_TO_DISABLE_ON_STARTUP="bluetooth nfc wifi off wwan"`

**Comment by linrunner** [comment]
Also please show the output of another terminal command:

    sudo service tlp status

**Comment by linrunner** [comment]
Due to inactivity I'll close here. Nevertheless, you are welcome to post new findings about your problem here.
