### ISSUE TITLE
7945hx CCD Parking

### ISSUE THREAD

**Issue by LuisB79** [linrunner/TLP#721]
Hi, since we are in the new age of 16 core laptops that have 2 ccd, could something be added for it to park one ccd for power savings?

**Comment by linrunner** [comment]
Thats is the job of the CPU driver/governor/scheduler, which has to do this automatically. I have already rejected switching off individual cores. Besides, I am not aware of any kernel interfaces for this.

**Comment by LuisB79** [comment]
lmao
