### ISSUE TITLE
Set `BAT/energy_full` manually

### ISSUE THREAD

**Issue by marcfehling** [linrunner/TLP#731]
As described in https://github.com/linrunner/TLP/issues/389#issuecomment-1949886330, I get inaccurate readings for `energy_full` after setting charge thresholds for my Lenovo notebook battery. I would like to recover the value for `energy_full` from the time before the threshold values were set. Recalibration does not restore the value.

I would like to suggest a feature to manually specify a value for `energy_full`, if that's realizable with this project. This way I could get the correct battery charge percentage again.

In the original comment above, you identified my problem as a hardware issue. I consider changing the battery, and until I find a replacement I would get the correct readings with this feature.

**Comment by linrunner** [comment]
Workarounds for hardware defects will not be implemented in TLP. Period.

For the future, please respect the rule that the issue tracker is not the place for supporting hardware issues in general and battery defects in particular. Thank you for taking note.

https://github.com/linrunner/TLP/blob/main/.github/Bug_Reporting_Howto.md
