### ISSUE TITLE
Nearly destroyed my non-laptop Ubuntu system, simply by installing tlp

### ISSUE THREAD

**Issue by wwone** [linrunner/TLP#733]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

**Expected behavior**

I accidentally installed tlp on a NUC11, which is a mini-pc that does NOT have a battery.

I expected it to be a no-op, and, realizing my error, I would be able to uninstall it.

HOWEVER, the presence of this running daemon stopped nearly all
Linux operations. In particular it prevented me from running
"sudo", so I could NOT stop anything, fix anything, or uninstall anything.

I could not run most GUI programs, especially browsers. The
internet ground to a halt.

The boot and startup-shutdown processes on the machine
hung massively .  A manual forced power-off was necessary
in order to reboot. Until I tried forced power-off, reboots were 
hanging 10-20 minutes each time.

**To Reproduce**

I would NOT recommend this product on a non-laptop, and 
I never want to ever reproduce this experience.

Perhaps a warning on the FAQ about installing on a non-laptop
machine might be in order?

Steps to reproduce the unexpected behavior:

1. Does the problem occur on battery or AC or both?
2. Actions to reproduce the behaviour
3. Shell commands entered and their output
4. **Full output of `tlp-stat` via https://gist.github.com/ for *all*
   matching cases of 1** (not as file attachment, no screenshots)

**Additional context**

I was able to run Linux from a thumb drive. I removed
the file /usr/sbin/tlp, while running under sudo in the "demo" 
system. All of the problems melted away. I was able
to reboot my installed Linux system without delay or
problems. I was able to run: 
"sudo apt remove tlp". The product is no longer on
my system.

Linux NUC1 5.15.0-101-generic #111~20.04.1-Ubuntu SMP Mon Mar 11 15:44:43 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by linrunner** [comment]
Hi, I'm sorry that you had such a bad experience. However, I do not share your opinion that TLP is generally not suitable for non-laptops.
