### ISSUE TITLE
Ubuntu PPA uses weak algorithm (rsa1024) warning, it's not a problem but still needs to be improved.

### ISSUE THREAD

**Issue by iHarryPotter178** [linrunner/TLP#743]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**
In Ubuntu Noble, 24.04 lts, it shows a warning that the TLP PPA uses weak algorithom, though it's not a problem, seeing that everytime is annoying and and it definitly needs to be improved.

**Expected behavior**

It should use stronger encryption so that warning doesn't appear.

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Simply add the PPA in Ubuntu noble and do an sudo apt update, the warning should be at the end.

**Comment by linrunner** [comment]
Without knowing the actual message, I can't say much about it.  Can you please copy the message from the terminal here?

**Comment by iHarryPotter178** [comment]
As theres nothing to do, I'll close this as complete

**Comment by zyf0330** [comment]
After remove and re-add, this problem is solved.
```
sudo add-apt-repository -r ppa:linrunner/tlp
sudo add-apt-repository ppa:linrunner/tlp
```

**Comment by linrunner** [comment]
Launchpad fixed it.
