### ISSUE TITLE
What does TLP stand for? Add it to README

### ISSUE THREAD

**Issue by DeflateAwning** [linrunner/TLP#746]
What does TLP stand for? Please add it to the README.

If it's a legacy acronym, it's still interesting info to include at the bottom or something.

If it's just random letters, that'd be nice to say explicitly too

**Comment by linrunner** [comment]
Please have the courtesy to look at the FAQ first: https://linrunner.de/tlp/faq/misc.html#what-does-tlp-stand-for

**Comment by DeflateAwning** [comment]
This is a little infuriating, but whatever I guess.

It looks like an acronym, and thus I believe this info should be a little easier to find than in the "Misc > FAQ" section
