### ISSUE TITLE
Multiple AC (and batt?) profiles

### ISSUE THREAD

**Issue by amanofbits** [linrunner/TLP#748]
Hey, thanks for your work, TLP is very helpful.

**Is your feature request related to a problem? Please describe.**

I guess it's no secret that nowadays laptops use USB type-c for external power, and powering them from external batteries (power banks) is becoming a usual thing, especially if you have frequent outages or plan to stay off grid for some time, etc. The problem is that there is no difference in how an external battery and a real AC adapter are treated, they're all "AC" from software's POW, while there can certainly be very different "power saving vs performance" demands for them.

Even more, if one has e.g. frequent outages, there's often a need to switch AC and external battery several times a day. You can have different config files in some place and just change them when you need, but then again, you may want to have another set of profiles for internal battery (like one for the usual workflow, and maximum power savings for occasional events). That's 4 profiles already and they may become cumbersome to manage.

**Describe the solution you'd like**

I believe it's not possible to have automatic detection of the type of external power source now. Even if we had, there's always that specific power bank manufacturer that does not do things right, so we're left with manual switching.

I find it not very convenient to mess with files manually every time, and I think it'd be a lot better if it could be done e.g. like `tlp use ac_powerbank bat_max_savings` or `tlp use default`, or `tlp use ac_performance`, etc., which would take settings, specific for that profiles and apply them.

I quickly made a small [tool](https://github.com/amanofbits/tcprofiles) that does exactly this for my own needs but I think it would be best to embed this feature into TLP itself.
The tool uses one config template that looks like regular TLP config file with only one addition - ini-like sections that define different configuration profiles. Any existing TLP config file can be used as template - all settings outside of any section just counts to the "default" profile and will be overridden when more specific one selected. I think this is a good way to implement this feature without breaking compatibility with existing configuration files.

**Describe alternatives you've considered**

The alternative is manual config files management which is possible but don't look very convenient. It's easy to mess settings, especially in the process of fine-tuning them.

**Comment by linrunner** [comment]
Hi. I do not plan to introduce additional profiles, you can find some arguments why not in #730.

As for your use case with the powerbank, I suggest you use manual mode

    sudo tlp bat

**Comment by amanofbits** [comment]
Hey, thanks for your answer.
I read #730 and completely understand your motivation. Although my approach is simpler, won't break backwards compatibility and is entirely transparent to the users that don't need it, it indeed may be a bit cumbersome to use in case of layered configuration, and will bring additional complexity to the code.
Also thanks for the `tlp bat` tip, I'll try it.
Have a good day!
