### ISSUE TITLE
Ubuntu kernel 6.8.0-39-generic fails to boot

### ISSUE THREAD

**Issue by igarca** [linrunner/TLP#754]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**

Linux Mint 22 does not boot if tlp is installed and/or enabled. After mint logo, before desktop (cinnamon) appears, I get a black screen.

**Expected behavior**

Laptop (thinkpad t480) booting and shutting down normally.

**To Reproduce**

- tlp-stat | tlp disabled: https://gist.github.com/igarca/90d43f391312be31309158dde94baeea
- tlp-stat | tlp enabled on battery: https://gist.github.com/igarca/89b7c2da9f295ab78117dd985dfacf83
- tlp-stat | tlp enabled with AC: https://gist.github.com/igarca/d374a15e5e2c64be73c9ff1f6f9c6cbc
- inxi -Fxxrzc0: https://gist.github.com/igarca/b85a80d8bb453cb47966dd1c13963815

**Additional context**
I thought it was due to a LM 22 upgrading issue, so I decided to do fresh install. The problem seemed to be resolved, but after I installed some apps, the problem came back. After testing, I am quite sure that tlp is causing the problem. 80% of the times it does not boot, and sometimes it does not even shutdown. 
I have the feeling that failing to boot is more likely to happen when using battery than when using AC, but I'm not very sure about this.
When tlp was installed I think it recommended me installing "tp-smapi-dkms smartmontools linux-tools-generic | linux-tools", not sure how relevant it is though.

**Comment by linrunner** [comment]
Hi,

in fact, I recently had boot hangs with my X1 Carbon 6th, the same hardware generation as your T480. 

I found out that it was due to the kernel 6.8.0-39-generic. The problems do not occur with 6.8.0-38-generic. Please try booting with the -38.

**Comment by igarca** [comment]
Hi,

Thank you. I booted a couple of times with 6.8.0-38-generic with no issues.
Should I report it to Ubuntu?

**Comment by linrunner** [comment]
Yes, I would suggest that.

**Comment by igarca** [comment]
Apparently it's been solved with 6.8.0-40-generic. I no longer experience boot hangs.

**Comment by linrunner** [comment]
Great. Thanks for your feedback
