### ISSUE TITLE
Get rid of Perl

### ISSUE THREAD

**Issue by fulalas** [linrunner/TLP#756]
Is there any plans to migrate TLP to pure Bash?

I noticed that apart from some `printf` in the Bash files that can easily be migrated to pure Bash, like this:

```
perl -e 'printf ("%-59s = %6.1f [%%]\n", "Capacity", 100.0 * '"$ef"' / '"$ed"');'
```

->

```
printf "%-59s = %6.1f [%%]\n" "Capacity" "$(echo "scale=1; 100.0 * $ef / $ed" | bc)"
``` 

You have just 3 actual Perl source files that are not that big.

This would be a huge improvement since Perl is not just a big package, but also a dependency that the user/distro needs to be aware of, update, etc.

**Comment by linrunner** [comment]
Hi, thanks for your suggestion.

You have overlooked a few things here: 
1. Scripts are not bash but Posix shell, look at the shebangs
2. Bash can only do integer arithmetic
3. **tlp-readconf** in particular has a critical, central function

Implementing your suggestion would require many hours of work and a costly revalidation of the functionality, if it would work at all. 

The expected benefit is disproportionate to the effort involved.
