### ISSUE TITLE
Allow per-device overriding of USB autosuspend_delay_ms

### ISSUE THREAD

**Issue by garyp** [linrunner/TLP#98]
The webcam on my ThinkPad T430 never autosuspends with the default 2000ms delay and uses up a fair amount of power when idle (according to powertop). Setting `autosuspend_delay_ms` to 0 drops the power usage without adversely affecting the camera. However, tlp is always resetting `autosuspend_delay_ms` to 2000 and there's no way to override it other than to disable autosuspend for the device completely (by adding it to `USB_BLACKLIST`).

Can you either add an option to tell tlp to ignore a certain USB device (i.e. don't change its settings at all) or add an option to override `autosuspend_delay_ms` for specific devices? Thanks!

**Comment by linrunner** [comment]
0.7 released

**Comment by garyp** [comment]
0.7 fixed the problem for me. Thanks!

**Comment by linrunner** [comment]
Thanks for your feedback.
